interface RemoteTest {
	readonly attribute long fortyTwo;

	object createObject(string name);
	oneway void die();
};

interface Calculator {
	long add(long a, long b);
	string concat(string a, string b);
};
