#! /usr/bin/env python
Import('env')

env.subdirs('tests')

kutils_sources = """
kcmoduleinfo.cpp
kcmoduleloader.cpp
kcmodulecontainer.cpp
kcmoduleproxy.cpp
kcmoduleproxyIface.skel
kcmoduleproxyIfaceImpl.cpp 
kcmultidialog.cpp
kfind.cpp
kfinddialog.cpp
kmultitabbar.cpp 
kplugininfo.cpp
kpluginselector.cpp
kreplace.cpp
kreplacedialog.cpp
"""

include_headers = """
kcmodulecontainer.h
kcmoduleinfo.h
kcmoduleloader.h
kcmoduleproxy.h
kcmultidialog.h
kfind.h
kfinddialog.h
kmultitabbar.h
kplugininfo.h
kpluginselector.h
kreplace.h
kreplacedialog.h
"""

ksettings_sources = """
ksettings/componentsdialog.cpp
ksettings/dialog.cpp
ksettings/dispatcher.cpp
ksettings/pluginpage.cpp
"""

ksettings_headers = """
ksettings/componentsdialog.h
ksettings/dialog.h
ksettings/dispatcher.h
ksettings/pluginpage.h
"""

noinst_headers = """
kcmoduleproxyIface.h
kmultitabbar_p.h
kpluginselector_p.h
"""

for i in noinst_headers.split():
	env.Moc(i)
	
includes = '#/interfaces/kregexpeditor ksettings '

obj = env.kdeobj('shlib')
obj.target   = 'kutils'
obj.vnum     = '3.0.2'
obj.source   = kutils_sources + ksettings_sources
obj.includes = includes
obj.libpaths = ' ../dcop ../kdefx ../kwallet/client '
obj.libs     = ' DCOP kdefx kwalletclient '
obj.uselib   = 'QT QTCORE QTGUI QT3SUPPORT KDE4 KDECORE KDEUI KIO '
if not env['WINDOWS']:
	obj.libs += ' kdesu'
	obj.libpaths += ' ../kdesu '
obj.execute()

if env['MAC']:
	env.Depends('libkutils.3.0.2.dylib', '../kio/libkio.dylib')
elif not env['WINDOWS']:
	env.Depends('libkutils.so.3.0.2', '../kio/libkio.so')

env.bksys_insttype('KDEINCLUDE','',include_headers)
env.bksys_insttype('KDEINCLUDE', 'ksettings', ksettings_headers )

	
"""Unhandled Defines 
METASOURCES = AUTO
DOXYGEN_REFERENCES = kdecore kdeui kio
kde_servicetypes_DATA = kplugininfo.desktop
"""
