#! /bin/sh

TMPFN=db2pstmp$$

DB_STYLESHEET=""

case $1 in
	-d) DB_STYLESHEET="-d $2"
	shift 2
	;;
esac

if [ $# -gt 2 ]
then
  echo "Usage: `basename $0` [-d stylesheet.dsl] [filename.sgml]" >&2
  exit 1
fi

output="`echo $1 | sed 's,\.sgml$,.ps,;s,\.sgm$,.ps,;s,\.docbook$,.ps,'`"
outdvi="`echo $1 | sed 's,\.sgml$,.dvi,;s,\.sgm$,.dvi,;s,\.docbook$,.dvi,'`"
db2dvi $DB_STYLESHEET $1
dvips $outdvi -o $output

exit 0

