/* config-kidletime.h. Generated by cmake from config-kidletime.h.cmake */

#cmakedefine HAVE_XTEST 1

#cmakedefine HAVE_XSCREENSAVER 1

/* Define if you have the XSync extension */
#cmakedefine HAVE_XSYNC 1
