
all: Makefile
	cd .. && qmake CONFIG+=WIN9x -o Makefile.win9x && nmake -nologo -f Makefile.win9x

clean:
	del obj\*.obj

FORCE:

distclean: clean

####### Compile

####### Install

install:  

uninstall:  

