#include "artsflow.idl"
#include "kmedia2.idl"

interface ByteSoundProducer : SynthModule
{
	readonly attribute long samplingRate;
	readonly attribute long channels;
	readonly attribute long bits;

	async out byte stream outdata;
};

/*
 * This is a very simple sound server interface
 */

interface SimpleSoundServer
/*
 * Warning: This currently inherits a KMedia2 PlayObjectFactory for test
 *    purposes, but don't rely on that
 */
			: PlayObjectFactory
{
	readonly attribute StereoEffectStack outstack;

	/**
	 * tries to play the sound in "filename"
	 *
	 * returns an ID when success 0 when it fails
	 */
	long play(string filename);

	/**
	 * returns true if the sound in ID is still playing
	 */
	//bool isPlaying(long ID);

	/**
	 * stops a playing sound by ID
	 */
	//void stop(long ID);

	/**
	 * attaches a byte sound producer (read: a client which produces/mixes
	 * an audio stream itself and just wants playback via the soundserver)
	 */
	void attach(ByteSoundProducer producer);

	/**
	 * detaches a previous attached byte sound producer
	 */
	void detach(ByteSoundProducer producer);

	object createObject(string name);
};

/*
 * Test KMedia2 interface
 */

interface WavPlayObject : PlayObject, SynthModule
{
	out audio stream left,right;
};
