/**********************************************************************

	--- Qt Architect generated file ---

	File: AssertDialogData.cpp
	Last generated: Mon Sep 28 17:05:43 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "AssertDialogData.h"

#define Inherited QDialog


AssertDialogData::AssertDialogData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	frameBase = new QFrame( this, "FrameBase" );
	frameBase->setGeometry( 10, 10, 380, 250 );
	frameBase->setMinimumSize( 10, 10 );
	frameBase->setMaximumSize( 32767, 32767 );
	frameBase->setFrameStyle( 34 );

	bgActions = new QButtonGroup( this, "ButtonGroup" );
	bgActions->setGeometry( 20, 90, 360, 120 );
	bgActions->setMinimumSize( 10, 10 );
	bgActions->setMaximumSize( 32767, 32767 );
	connect( bgActions, SIGNAL(clicked(int)), SLOT(setAction(int)) );
	bgActions->setFrameStyle( 50 );
	bgActions->setTitle( "Select action to raise:" );
	bgActions->setAlignment( 1 );

	labelImage = new QLabel( this, "LabelImage" );
	labelImage->setGeometry( 310, 20, 74, 15 );
	labelImage->setMinimumSize( 10, 10 );
	labelImage->setMaximumSize( 32767, 32767 );
	labelImage->setText( "(Bug pixmap)" );
	labelImage->setAlignment( 1316 );
	labelImage->setMargin( -1 );

	labelHeadline = new QLabel( this, "LabelHeadline" );
	labelHeadline->setGeometry( 20, 20, 231, 17 );
	labelHeadline->setMinimumSize( 10, 10 );
	labelHeadline->setMaximumSize( 32767, 32767 );
	{
		QFont font( "helvetica", 14, 50, 1 );
		font.setStyleHint( (QFont::StyleHint)0 );
		font.setCharSet( (QFont::CharSet)0 );
		labelHeadline->setFont( font );
	}
	labelHeadline->setText( "You found a bug in this application." );
	labelHeadline->setAlignment( 289 );
	labelHeadline->setMargin( -1 );

	labelError = new QLabel( this, "LabelError" );
	labelError->setGeometry( 20, 50, 180, 15 );
	labelError->setMinimumSize( 10, 10 );
	labelError->setMaximumSize( 32767, 32767 );
	labelError->setText( "In the file blablabla.cc, line 163:" );
	labelError->setAlignment( 1289 );
	labelError->setMargin( -1 );

	buttonOK = new QPushButton( this, "PushButtonOK" );
	buttonOK->setGeometry( 20, 220, 51, 26 );
	buttonOK->setMinimumSize( 10, 10 );
	buttonOK->setMaximumSize( 32767, 32767 );
	connect( buttonOK, SIGNAL(clicked()), SLOT(accept()) );
	buttonOK->setText( "OK" );
	buttonOK->setAutoRepeat( FALSE );
	buttonOK->setAutoResize( TRUE );
	buttonOK->setAutoDefault( TRUE );


	resize( 400,270 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


AssertDialogData::~AssertDialogData()
{
}
void AssertDialogData::setAction(int)
{
}
