/**********************************************************************

	--- Qt Architect generated file ---

	File: SearchDialogData.cpp
	Last generated: Sat Feb 28 22:57:25 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "SearchDialogData.h"

#undef Inherited
#define Inherited QDialog


SearchDialogData::SearchDialogData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	comboSelector = new QComboBox( FALSE, this, "ComboBox_1" );
	comboSelector->setGeometry( 10, 10, 160, 30 );
	comboSelector->setMinimumSize( 10, 10 );
	comboSelector->setMaximumSize( 32767, 32767 );
	comboSelector->setSizeLimit( 10 );
	comboSelector->setAutoResize( FALSE );

	labelContains = new QLabel( this, "Label_1" );
	labelContains->setGeometry( 180, 10, 70, 30 );
	labelContains->setMinimumSize( 10, 10 );
	labelContains->setMaximumSize( 32767, 32767 );
	labelContains->setText( "" );
	labelContains->setAlignment( 292 );
	labelContains->setMargin( -1 );

	leWhat = new QLineEdit( this, "LineEdit_1" );
	leWhat->setGeometry( 260, 10, 130, 30 );
	leWhat->setMinimumSize( 10, 10 );
	leWhat->setMaximumSize( 32767, 32767 );
	leWhat->setText( "" );
	leWhat->setMaxLength( 32767 );
	leWhat->setEchoMode( QLineEdit::Normal );
	leWhat->setFrame( TRUE );

	buttonSearch = new QPushButton( this, "PushButton_1" );
	buttonSearch->setGeometry( 10, 80, 100, 30 );
	buttonSearch->setMinimumSize( 10, 10 );
	buttonSearch->setMaximumSize( 32767, 32767 );
	connect( buttonSearch, SIGNAL(clicked()), SLOT(accept()) );
	buttonSearch->setText( "" );
	buttonSearch->setAutoRepeat( FALSE );
	buttonSearch->setAutoResize( FALSE );

	buttonCancel = new QPushButton( this, "PushButton_2" );
	buttonCancel->setGeometry( 290, 80, 100, 30 );
	buttonCancel->setMinimumSize( 10, 10 );
	buttonCancel->setMaximumSize( 32767, 32767 );
	connect( buttonCancel, SIGNAL(clicked()), SLOT(reject()) );
	buttonCancel->setText( "" );
	buttonCancel->setAutoRepeat( FALSE );
	buttonCancel->setAutoResize( FALSE );

	frameHorLine = new QFrame( this, "Frame_1" );
	frameHorLine->setGeometry( 10, 60, 380, 10 );
	frameHorLine->setMinimumSize( 10, 10 );
	frameHorLine->setMaximumSize( 32767, 32767 );
	frameHorLine->setFrameStyle( 36 );

	resize( 400,120 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


SearchDialogData::~SearchDialogData()
{
}
