/* -*- C++ -*-
**********************************************************************

	--- Qt Architect generated file ---

	File: StringListDialogData.cpp
	Last generated: Sun Apr 12 18:03:55 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "StringListDialogData.h"

#define Inherited QDialog


StringListDialogData::StringListDialogData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	lbStrings = new QListBox( this, "ListBox_2" );
	lbStrings->setGeometry( 10, 40, 230, 150 );
	lbStrings->setMinimumSize( 10, 10 );
	lbStrings->setMaximumSize( 32767, 32767 );
	lbStrings->setFrameStyle( 51 );
	lbStrings->setLineWidth( 2 );
	lbStrings->setMultiSelection( FALSE );

	frameLine = new QFrame( this, "Frame_1" );
	frameLine->setGeometry( 10, 200, 270, 10 );
	frameLine->setMinimumSize( 10, 10 );
	frameLine->setMaximumSize( 32767, 32767 );
	frameLine->setFrameStyle( 36 );

	buttonOK = new QPushButton( this, "PushButton_1" );
	buttonOK->setGeometry( 10, 210, 100, 30 );
	buttonOK->setMinimumSize( 10, 10 );
	buttonOK->setMaximumSize( 32767, 32767 );
	connect( buttonOK, SIGNAL(clicked()), SLOT(accept()) );
	buttonOK->setText( "" );
	buttonOK->setAutoRepeat( FALSE );
	buttonOK->setAutoResize( FALSE );

	buttonCancel = new QPushButton( this, "PushButton_2" );
	buttonCancel->setGeometry( 180, 210, 100, 30 );
	buttonCancel->setMinimumSize( 10, 10 );
	buttonCancel->setMaximumSize( 32767, 32767 );
	connect( buttonCancel, SIGNAL(clicked()), SLOT(reject()) );
	buttonCancel->setText( "" );
	buttonCancel->setAutoRepeat( FALSE );
	buttonCancel->setAutoResize( FALSE );

	buttonUp = new QPushButton( this, "PushButton_3" );
	buttonUp->setGeometry( 250, 40, 30, 30 );
	buttonUp->setMinimumSize( 10, 10 );
	buttonUp->setMaximumSize( 32767, 32767 );
	connect( buttonUp, SIGNAL(clicked()), SLOT(upPressed()) );
	buttonUp->setText( "" );
	buttonUp->setAutoRepeat( FALSE );
	buttonUp->setAutoResize( FALSE );

	buttonDown = new QPushButton( this, "PushButton_4" );
	buttonDown->setGeometry( 250, 80, 30, 30 );
	buttonDown->setMinimumSize( 10, 10 );
	buttonDown->setMaximumSize( 32767, 32767 );
	connect( buttonDown, SIGNAL(clicked()), SLOT(downPressed()) );
	buttonDown->setText( "" );
	buttonDown->setAutoRepeat( FALSE );
	buttonDown->setAutoResize( FALSE );

	buttonDelete = new QPushButton( this, "PushButton_5" );
	buttonDelete->setGeometry( 250, 160, 30, 30 );
	buttonDelete->setMinimumSize( 10, 10 );
	buttonDelete->setMaximumSize( 32767, 32767 );
	connect( buttonDelete, SIGNAL(clicked()), SLOT(deletePressed()) );
	buttonDelete->setText( "" );
	buttonDelete->setAutoRepeat( FALSE );
	buttonDelete->setAutoResize( FALSE );

	leLine = new QLineEdit( this, "LineEdit_2" );
	leLine->setGeometry( 10, 10, 270, 20 );
	leLine->setMinimumSize( 10, 10 );
	leLine->setMaximumSize( 32767, 32767 );
	connect( leLine, SIGNAL(returnPressed()), SLOT(addString()) );
	leLine->setText( "" );
	leLine->setMaxLength( 32767 );
	leLine->setEchoMode( QLineEdit::Normal );
	leLine->setFrame( TRUE );

	resize( 290,250 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


StringListDialogData::~StringListDialogData()
{
}
void StringListDialogData::upPressed()
{
}
void StringListDialogData::downPressed()
{
}
void StringListDialogData::deletePressed()
{
}
void StringListDialogData::addString()
{
}
