/**********************************************************************

	--- Qt Architect generated file ---

	File: StringListSelectAndReorderSetData.cpp
	Last generated: Fri Aug 7 13:31:31 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include "StringListSelectAndReorderSetData.h"

#define Inherited QFrame


StringListSelectAndReorderSetData::StringListSelectAndReorderSetData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	lbPossible = new QListBox( this, "ListBox_2" );
	lbPossible->setGeometry( 20, 50, 150, 170 );
	lbPossible->setMinimumSize( 10, 10 );
	lbPossible->setMaximumSize( 32767, 32767 );
	lbPossible->setFrameStyle( 51 );
	lbPossible->setLineWidth( 2 );
	lbPossible->setMultiSelection( FALSE );

	buttonSelect = new QPushButton( this, "PushButton_5" );
	buttonSelect->setGeometry( 180, 50, 30, 30 );
	buttonSelect->setMinimumSize( 10, 10 );
	buttonSelect->setMaximumSize( 32767, 32767 );
	connect( buttonSelect, SIGNAL(pressed()), SLOT(selectPressed()) );
	buttonSelect->setText( "" );
	buttonSelect->setAutoRepeat( FALSE );
	buttonSelect->setAutoResize( FALSE );

	buttonUnselect = new QPushButton( this, "PushButton_6" );
	buttonUnselect->setGeometry( 180, 80, 30, 30 );
	buttonUnselect->setMinimumSize( 10, 10 );
	buttonUnselect->setMaximumSize( 32767, 32767 );
	connect( buttonUnselect, SIGNAL(pressed()), SLOT(unselectPressed()) );
	buttonUnselect->setText( "" );
	buttonUnselect->setAutoRepeat( FALSE );
	buttonUnselect->setAutoResize( FALSE );

	lbSelected = new QListBox( this, "ListBox_3" );
	lbSelected->setGeometry( 220, 50, 150, 170 );
	lbSelected->setMinimumSize( 10, 10 );
	lbSelected->setMaximumSize( 32767, 32767 );
	lbSelected->setFrameStyle( 51 );
	lbSelected->setLineWidth( 2 );
	lbSelected->setMultiSelection( FALSE );

	buttonUp = new QPushButton( this, "PushButton_7" );
	buttonUp->setGeometry( 380, 50, 30, 30 );
	buttonUp->setMinimumSize( 10, 10 );
	buttonUp->setMaximumSize( 32767, 32767 );
	connect( buttonUp, SIGNAL(pressed()), SLOT(up()) );
	buttonUp->setText( "" );
	buttonUp->setAutoRepeat( FALSE );
	buttonUp->setAutoResize( FALSE );

	buttonDown = new QPushButton( this, "PushButton_8" );
	buttonDown->setGeometry( 380, 80, 30, 30 );
	buttonDown->setMinimumSize( 10, 10 );
	buttonDown->setMaximumSize( 32767, 32767 );
	connect( buttonDown, SIGNAL(pressed()), SLOT(down()) );
	buttonDown->setText( "" );
	buttonDown->setAutoRepeat( FALSE );
	buttonDown->setAutoResize( FALSE );

	labelPossible = new QLabel( this, "Label_2" );
	labelPossible->setGeometry( 20, 20, 150, 20 );
	labelPossible->setMinimumSize( 10, 10 );
	labelPossible->setMaximumSize( 32767, 32767 );
	labelPossible->setText( "" );
	labelPossible->setAlignment( 292 );
	labelPossible->setMargin( -1 );

	labelSelected = new QLabel( this, "Label_3" );
	labelSelected->setGeometry( 220, 20, 150, 20 );
	labelSelected->setMinimumSize( 10, 10 );
	labelSelected->setMaximumSize( 32767, 32767 );
	labelSelected->setText( "" );
	labelSelected->setAlignment( 292 );
	labelSelected->setMargin( -1 );

	resize( 430,240 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


StringListSelectAndReorderSetData::~StringListSelectAndReorderSetData()
{
}
void StringListSelectAndReorderSetData::selectPressed()
{
}
void StringListSelectAndReorderSetData::unselectPressed()
{
}
void StringListSelectAndReorderSetData::up()
{
}
void StringListSelectAndReorderSetData::down()
{
}
