Import('env')

kdnssd_sources = """
domainbrowser.cpp publicservice.cpp query.cpp remoteservice.cpp
responder.cpp servicebase.cpp servicebrowser.cpp settings.kcfgc
"""

noinst_headers = """
sdevent.h
"""

includes = ' '

obj = env.kdeobj('shlib')
obj.target = 'kdnssd'
obj.vnum = '1.0'
obj.source = kdnssd_sources
obj.includes = includes
obj.libpaths = '../kdecore ../kdeui '
obj.libs = 'kdecore kdeui '
obj.uselib = 'QT QTCORE QTGUI QT3SUPPORT KDE4 DNSSD '
if env['WINDOWS']:
    obj.libs    += ' ws2_32'
obj.execute()

env.Depends('libkdnssd.so.1.0', '../kdecore/libkdecore.so')
dnssdinclude_headers = """
domainbrowser.h publicservice.h query.h remoteservice.h
servicebase.h servicebrowser.h settings.h
"""

env.bksys_insttype( 'KDEINCLUDE', 'dnssd', dnssdinclude_headers )

# TODO make this automatic in kdelibs?
if env['WINDOWS']:
	env.Depends( 'settings.h', '../kdecore/kconfig_compiler/kconfig_compiler.exe' )
else:
	env.Depends( 'settings.h', '../kdecore/kconfig_compiler/kconfig_compiler' )

