include(CheckIncludeFile)
include(CheckIncludeFiles)
include(CheckSymbolExists)
include(CheckFunctionExists)
include(CheckLibraryExists)
include(CheckPrototypeExists)
include(CheckTypeSize)

#check for libz using the cmake supplied FindZLIB.cmake
if(ZLIB_FOUND)
   set(HAVE_LIBZ 1)
else(ZLIB_FOUND)
   set(HAVE_LIBZ 0)
endif(ZLIB_FOUND)

if(BZIP2_FOUND)
   set(HAVE_BZIP2_SUPPORT 1)
   if(BZIP2_NEED_PREFIX)
      set(NEED_BZ2_PREFIX 1)
   endif(BZIP2_NEED_PREFIX)
else(BZIP2_FOUND)
   set(HAVE_BZIP2_SUPPORT 0)
endif(BZIP2_FOUND)

#check for png
if(PNG_FOUND)
   set(HAVE_LIBPNG 1)
else(PNG_FOUND)
   set(HAVE_LIBPNG 0)
endif(PNG_FOUND)

if(OPENEXR_FOUND)
   set(HAVE_EXR 1)
else(OPENEXR_FOUND)
   set(HAVE_EXR 0)
endif(OPENEXR_FOUND)

if(FAM_FOUND)
   set(HAVE_FAM 1)
else(FAM_FOUND)
   set(HAVE_FAM 0)
endif(FAM_FOUND)

if(JASPER_FOUND)
   set(HAVE_JASPER 1)
else(JASPER_FOUND)
   set(HAVE_JASPER 0)
endif(JASPER_FOUND)

if(LIBART_FOUND)
   set(HAVE_LIBART 1)
else(LIBART_FOUND)
   set(HAVE_LIBART 0)
endif(LIBART_FOUND)

if(PCRE_FOUND)
   set(HAVE_PCREPOSIX 1)
else(PCRE_FOUND)
   set(HAVE_PCREPOSIX 0)
endif(PCRE_FOUND)

if(OPENSSL_FOUND)
   set(HAVE_SSL 1)
else(OPENSSL_FOUND)
   set(HAVE_SSL 0)
endif(OPENSSL_FOUND)

if(CARBON_FOUND)
	set(HAVE_CARBON 1)
else(CARBON_FOUND)
	set(HAVE_CARBON 0)
endif(CARBON_FOUND)

#now check for dlfcn.h using the cmake supplied CHECK_include_FILE() macro

if (WIN32)
   set(CMAKE_REQUIRED_LIBRARIES ${KDEWIN32_LIBRARY} ws2_32)
   set(CMAKE_REQUIRED_INCLUDES  ${KDEWIN32_INCLUDES} )
endif (WIN32)

check_include_files(stdio.h HAVE_STDIO_H)
check_include_files(stdlib.h HAVE_STDLIB_H)
check_include_files(string.h HAVE_STRING_H)
check_include_files(strings.h HAVE_STRINGS_H)
check_include_files(ctype.h HAVE_CTYPE_H)
check_include_files(malloc.h HAVE_MALLOC_H)
check_include_files(memory.h HAVE_MEMORY_H)
check_include_files(dlfcn.h HAVE_DLFCN_H)
check_include_files(sys/time.h TIME_WITH_SYS_TIME)
check_include_files(float.h       HAVE_FLOAT_H)
check_include_files(crt_externs.h HAVE_CRT_EXTERNS_H)
check_include_files(dirent.h HAVE_DIRENT_H)
check_include_files(dld.h HAVE_DLD_H)
check_include_files(dl.h HAVE_DL_H)

check_include_files(alloca.h      HAVE_ALLOCA_H)
check_include_files(fstab.h       HAVE_FSTAB_H)
check_include_files(ieeefp.h      HAVE_IEEEFP_H)
check_include_files(limits.h      HAVE_LIMITS_H)
check_include_files("sys/types.h;libutil.h" HAVE_LIBUTIL_H)
check_include_files(util.h        HAVE_UTIL_H)
check_include_files(mntent.h      HAVE_MNTENT_H)
check_include_files("pthread.h;pthread_np.h" HAVE_PTHREAD_NP_H)
check_include_files(pty.h         HAVE_PTY_H)
check_include_files(sysent.h      HAVE_SYSENT_H)
check_include_files(sys/bitypes.h HAVE_SYS_BITYPES_H)
check_include_files(sys/dir.h     HAVE_SYS_DIR_H)
check_include_files(sys/filio.h   HAVE_SYS_FILIO_H)
check_include_files("sys/types.h;sys/mman.h" HAVE_SYS_MMAN_H)
check_include_files(sys/stat.h    HAVE_SYS_STAT_H)
check_include_files(sys/ucred.h   HAVE_SYS_UCRED_H)
check_include_files(sys/xattr.h   HAVE_SYS_XATTR_H)
check_include_files(sys/types.h   HAVE_SYS_TYPES_H)
check_include_files(sys/select.h  HAVE_SYS_SELECT_H)
check_include_files(sys/stropts.h HAVE_SYS_STROPTS_H)
check_include_files(sys/param.h   HAVE_SYS_PARAM_H)
check_include_files(sys/bitypes.h HAVE_SYS_BITYPES_H)
check_include_files(sys/ndir.h    HAVE_SYS_NDIR_H)
check_include_files(sys/mnttab.h  HAVE_SYS_MNTTAB_H)
check_include_files(sys/mntent.h  HAVE_SYS_MNTENT_H)
check_include_files("sys/param.h;sys/mount.h"  HAVE_SYS_MOUNT_H)
check_include_files(termios.h     HAVE_TERMIOS_H)
check_include_files(termio.h      HAVE_TERMIO_H)
check_include_files(unistd.h      HAVE_UNISTD_H)
check_include_files(stdint.h      HAVE_STDINT_H)
check_include_files(netinet/in.h  HAVE_NETINET_IN_H)
check_include_files(idna.h        HAVE_IDNA_H)
check_include_files(inttypes.h    HAVE_INTTYPES_H)
check_include_files(linux/awe_voice.h   HAVE_LINUX_AWE_VOICE_H)
check_include_files(locale.h      HAVE_LOCALE_H)
check_include_files(machine/soundcard.h HAVE_MACHINE_SOUNDCARD_H)
check_include_files(sys/soundcard.h HAVE_SYS_SOUNDCARD_H)
check_include_files(ndir.h        HAVE_NDIR_H)
check_include_files("sys/socket.h;net/if.h" HAVE_NET_IF_H)
check_include_files(nl_types.h    HAVE_NL_TYPES_H)
check_include_files(paths.h       HAVE_PATHS_H)
check_include_files(punycode.h    HAVE_PUNYCODE_H)
check_include_files(stringprep.h  HAVE_STRINGPREP_H)
check_include_files(values.h      HAVE_VALUES_H)

check_include_files(errno.h       HAVE_ERRNO_H)
check_include_files(sys/time.h    HAVE_SYS_TIME_H)
check_include_files(sys/timeb.h   HAVE_SYS_TIMEB_H)


check_include_files( X11/extensions/shape.h HAVE_X11_EXTENSIONS_SHAPE_H)
check_include_files( "X11/Xlib.h;X11/extensions/XShm.h"  HAVE_X11_EXTENSIONS_XSHM_H)
check_include_files( X11/ICE/ICElib.h       HAVE_X11_ICE_ICELIB_H)
check_include_files( X11/extensions/Xrender.h HAVE_XRENDER)


#check_symbol_exists(sockaddr_in6 "netinet/in.h" HAVE_STRUCT_SOCKADDR_IN6)
check_symbol_exists(LC_MESSAGES "locale.h" HAVE_LC_MESSAGES)
check_symbol_exists(res_init "sys/types.h;netinet/in.h;arpa/nameser.h;resolv.h" HAVE_RES_INIT)
check_symbol_exists(S_ISSOCK sys/stat.h HAVE_S_ISSOCK)

check_function_exists(posix_fadvise  HAVE_FADVISE)
check_function_exists(index     HAVE_INDEX)
check_function_exists(rindex    HAVE_RINDEX)
check_function_exists(memcpy    HAVE_MEMCPY)
check_function_exists(bcopy     HAVE_BCOPY)
check_function_exists(backtrace HAVE_BACKTRACE)
check_function_exists(getservbyname_r HAVE_DECL_GETSERVBYNAME_R)
check_function_exists(getservbyname_r HAVE_GETSERVBYNAME_R)
check_function_exists(freeaddrinfo HAVE_FREEADDRINFO)
check_function_exists(gai_strerror HAVE_GAI_STRERROR)
check_function_exists(getcwd    HAVE_GETCWD)
check_function_exists(getgroups HAVE_GETGROUPS)
check_function_exists(getcwd    HAVE_GETCWD)
check_function_exists(gethostbyname2 HAVE_GETHOSTBYNAME2)
check_function_exists(gethostbyname2_r HAVE_GETHOSTBYNAME2_R)
check_function_exists(gethostbyname HAVE_GETHOSTBYNAME)
check_function_exists(gethostbyname_r HAVE_GETHOSTBYNAME_R)
check_function_exists(gethostname HAVE_GETHOSTNAME)
check_function_exists(getnameinfo HAVE_GETNAMEINFO)
check_function_exists(getpagesize HAVE_GETPAGESIZE)
check_function_exists(getpeereid  HAVE_GETPEEREID)
check_function_exists(getpeername HAVE_GETPEERNAME)
check_function_exists(getprotobyname_r HAVE_GETPROTOBYNAME_R)
check_function_exists(getpt       HAVE_GETPT)
check_function_exists(getservbyport_r HAVE_GETSERVBYPORT_R)
check_function_exists(getsockname     HAVE_GETSOCKNAME)
check_function_exists(getsockopt      HAVE_GETSOCKOPT)
check_function_exists(gettimeofday    HAVE_GETTIMEOFDAY)
check_function_exists(grantpt         HAVE_GRANTPT)
check_function_exists(if_nametoindex  HAVE_IF_NAMETOINDEX)
check_function_exists(madvise         HAVE_MADVISE)
check_function_exists(mmap            HAVE_MMAP)
check_function_exists(munmap          HAVE_MUNMAP)
check_function_exists(poll            HAVE_POLL)
check_function_exists(putenv          HAVE_PUTENV)
check_function_exists(readdir_r       HAVE_READDIR_R)
check_function_exists(res_init        HAVE_RES_INIT)
check_function_exists(sendfile        HAVE_SENDFILE)
check_function_exists(setegid         HAVE_SETEGID)
check_function_exists(setfsent        HAVE_SETFSENT)
check_function_exists(setgroups       HAVE_SETGROUPS)
check_function_exists(setlocale       HAVE_SETLOCALE)
check_function_exists(setlocale       HAVE_SETPRIORITY)
check_function_exists(snprintf        HAVE_SNPRINTF)
check_function_exists(socket          HAVE_SOCKET)
check_function_exists(srandom         HAVE_SRANDOM)
check_function_exists(stpcpy          HAVE_STPCPY)
check_function_exists(strcasecmp      HAVE_STRCASECMP)
check_function_exists(strfmon         HAVE_STRFMON)
check_function_exists(strrchr         HAVE_STRRCHR)
check_function_exists(strcmp          HAVE_STRCMP)
check_function_exists(strchr          HAVE_STRCHR)
check_function_exists(strtoll         HAVE_STRTOLL)
check_function_exists(unlockpt        HAVE_UNLOCKPT)
check_function_exists(vsnprintf       HAVE_VSNPRINTF)
check_function_exists(_NSGetEnviron   HAVE_NSGETENVIRON)
check_function_exists(__argz_count    HAVE___ARGZ_COUNT)
check_function_exists(__argz_next     HAVE___ARGZ_NEXT)
check_function_exists(__argz_stringify HAVE___ARGZ_STRINGIFY)

check_library_exists(utempter addToUtmp "" HAVE_UTEMPTER)
check_library_exists(crypt crypt "" HAVE_CRYPT)
check_library_exists(volmgt volmgt_running "" HAVE_VOLMGT)

check_library_exists(util  openpty "" HAVE_OPENPTY)
if (HAVE_OPENPTY)
  set(UTIL_LIBRARY util)
endif (HAVE_OPENPTY)

# it seems this isn't used anywhere
#find_library(ICE_LIB NAMES ICE PATHS /usr/X11/lib)
#check_library_exists(${ICE_LIB} _IceTransNoListen "" HAVE__ICETRANSNOLISTEN)

#set(CMAKE_REQUIRED_LIBRARIES crypt)
#check_function_exists(crypt "" HAVE_CRYPT)
#set(CMAKE_REQUIRED_LIBRARIES util)
#check_function_exists(openpty "" HAVE_OPENPTY)
#set(CMAKE_REQUIRED_LIBRARIES)

#dlopen stuff
check_library_exists(dl dlopen ""  HAVE_LIBDL)
check_library_exists(dl dlerror ""  HAVE_DLERROR)
check_function_exists(shl_load HAVE_SHL_LOAD)
check_function_exists(dld_init HAVE_DLD)

check_function_exists(getaddrinfo HAVE_GETADDRINFO)
check_function_exists(getmntinfo HAVE_GETMNTINFO)
check_function_exists(inet_pton  HAVE_INET_PTON)
check_function_exists(inet_ntop  HAVE_INET_NTOP)
check_function_exists(initgroups HAVE_INITGROUPS)
check_function_exists(mkstemps   HAVE_MPSTEMPS)
check_function_exists(mkstemp    HAVE_MPSTEMP)
check_function_exists(mkstemps   HAVE_MKSTEMPS)
check_function_exists(mkstemp    HAVE_MKSTEMP)
check_function_exists(mkdtemp    HAVE_MKDTEMP)
check_function_exists(ptsname    HAVE_PTSNAME)
check_function_exists(random     HAVE_RANDOM)
check_function_exists(revoke     HAVE_REVOKE)
check_function_exists(strlcpy    HAVE_STRLCPY)
check_function_exists(strlcat    HAVE_STRLCAT)
check_function_exists(setenv     HAVE_SETENV)
check_function_exists(seteuid    HAVE_SETEUID)
check_function_exists(setmntent  HAVE_SETMNTENT)
check_function_exists(unsetenv   HAVE_UNSETENV)
check_function_exists(usleep     HAVE_USLEEP)
check_function_exists(_getpty    HAVE__GETPTY)

check_function_exists(_finite    HAVE_FUNC__FINITE)
check_function_exists(finite     HAVE_FUNC_FINITE)
check_function_exists(isinf      HAVE_FUNC_ISINF)
check_function_exists(isnan      HAVE_FUNC_ISNAN)

# check for prototypes

check_prototype_exists(mkstemps "stdlib.h;unistd.h" HAVE_MKSTEMPS_PROTO)
check_prototype_exists(mkdtemp "stdlib.h;unistd.h" HAVE_MKDTEMP_PROTO)
check_prototype_exists(mkstemp "stdlib.h;unistd.h" HAVE_MKSTEMP_PROTO)
check_prototype_exists(strlcat string.h HAVE_STRLCAT_PROTO)
check_prototype_exists(strlcpy string.h HAVE_STRLCPY_PROTO)
check_prototype_exists(random stdlib.h HAVE_RANDOM_PROTO)
check_prototype_exists(res_init "sys/types.h;netinet/in.h;arpa/nameser.h;resolv.h" HAVE_RES_INIT_PROTO)
check_prototype_exists(setenv stdlib.h HAVE_SETENV_PROTO)
check_prototype_exists(srandom stdlib.h HAVE_SRANDOM_PROTO)
check_prototype_exists(unsetenv stdlib.h HAVE_UNSETENV_PROTO)
check_prototype_exists(usleep unistd.h HAVE_USLEEP_PROTO)
check_prototype_exists(gethostname "stdlib.h;unistd.h" HAVE_GETHOSTNAME_PROTO)
check_prototype_exists(initgroups "unistd.h;sys/types.h;unistd.h;grp.h" HAVE_INITGROUPS_PROTO)
check_prototype_exists(setreuid unistd.h HAVE_SETREUID_PROTO)
check_prototype_exists(seteuid unistd.h HAVE_SETEUID_PROTO)

# check for existing datatypes

set(CMAKE_EXTRA_INCLUDE_FILES sys/socket.h)
check_type_size("struct ucred" HAVE_STRUCT_UCRED)

set(CMAKE_EXTRA_INCLUDE_FILES "sys/socket.h;netdb.h")
check_type_size("struct addrinfo" HAVE_STRUCT_ADDRINFO)

set(CMAKE_EXTRA_INCLUDE_FILES "sys/socket.h;netdb.h")
check_type_size("struct sockaddr_in6" HAVE_STRUCT_SOCKADDR_IN6)
SET(CMAKE_EXTRA_INCLUDE_FILES)  #reset CMAKE_EXTRA_INCLUDE_FILES

set(CONFIG_QT_DOCDIR "\"${QT_DOC_DIR}/html/\"")
set(CONFIG_KDELIBS_DOXYDIR "\"/tmp/\"")


