
#cheapo wannabe configure checks for stuff which isn't available before kdelibs/win/ has been built

# one '#' means it's not available
# three '###' means it is provided by windows itself

# set ( HAVE_BACKTRACE 1 )
# set ( HAVE_BCOPY 1 )
# set ( HAVE_CRYPT  1   )
# set ( HAVE_DECL_GETSERVBYNAME_R 1 )
# set ( HAVE_FADVISE 1 )
# set ( HAVE_FREEADDRINFO 1 )
### set ( HAVE_FUNC__FINITE 1
# set ( HAVE_FUNC_FINITE 1 )
# set ( HAVE_FUNC_ISINF 1 )
# set ( HAVE_FUNC_ISNAN 1 )
# set ( HAVE_GAI_STRERROR 1 )
# set ( HAVE_GETADDRINFO 1 )
### set ( HAVE_GETCWD 1
set ( HAVE_GETGROUPS 1 )
# set ( HAVE_GETHOSTBYNAME2 1 )
# set ( HAVE_GETHOSTBYNAME 1 )
# set ( HAVE_GETHOSTBYNAME2_R 1 )
# set ( HAVE_GETHOSTBYNAME_R 1 )
set ( HAVE_GETHOSTNAME 1 )
# set ( HAVE_GETNAMEINFO 1 )
# set ( HAVE_GETMNTINFO 1 )
set ( HAVE_GETPAGESIZE 1 )
# set ( HAVE_GETPEEREID 1 )
# set ( HAVE_GETPEERNAME 1 )
# set ( HAVE_GETPROTOBYNAME_R 1 )
# set ( HAVE_GETPT 1 )
# set ( HAVE_GETSERVBYNAME_R 1 )
# set ( HAVE_GETSERVBYPORT_R 1 )
# set ( HAVE_GETSOCKNAME 1 )
# set ( HAVE_GETSOCKOPT 1 )
set ( HAVE_GETTIMEOFDAY 1 )
# set ( HAVE_GRANTPT 1 )
# set ( HAVE_IF_NAMETOINDEX 1 )
# set ( HAVE_INDEX 1 )
# set ( HAVE_INITGROUPS 1 )
# set ( HAVE_INET_PTON 1 )
# set ( HAVE_INET_NTOP 1 )
# set ( HAVE_MADVISE 1 )
### set ( HAVE_MEMCPY 1
set ( HAVE_MMAP 1 )
set ( HAVE_MUNMAP 1 )
set ( HAVE_MKSTEMPS 1 )
# set ( HAVE_MKSTEMP 1 )
set ( HAVE_MKDTEMP 1 )
# set ( HAVE_OPENPTY 1 )
# set ( HAVE_POLL 1 )
### set ( HAVE_PUTENV 1
# set ( HAVE_PTSNAME 1 )
set ( HAVE_RANDOM 1 )
set ( HAVE_READDIR_R 1 )
# set ( HAVE_RES_INIT 1 )
# set ( HAVE_REVOKE 1 )
# set ( HAVE_RINDEX 1 )
# set ( HAVE_SENDFILE 1 )
# set ( HAVE_SETEGID 1 )
set ( HAVE_SETENV 1 )
# set ( HAVE_SETEUID 1 )
# set ( HAVE_SETFSENT 1 )
# set ( HAVE_SETGROUPS 1 )
### set ( HAVE_SETLOCALE 1
# set ( HAVE_SETMNTENT 1 )
### set ( HAVE_SETPRIORITY 1
# set ( HAVE_SHL_LOAD 1 )
set ( HAVE_SNPRINTF 1 )
set ( HAVE_SOCKET 1 )
set ( HAVE_SRANDOM 1 )
# set ( HAVE_STPCPY 1 )
set ( HAVE_STRCASECMP 1 )
### set ( HAVE_STRCHR 1
### set ( HAVE_STRCMP 1
# set ( HAVE_STRFMON 1 )
set ( HAVE_STRLCPY 1 )
set ( HAVE_STRLCAT 1 )
### set ( HAVE_STRRCHR 1
# set ( HAVE_STRTOLL 1 )
# set ( HAVE_UNLOCKPT 1 )
set ( HAVE_UNSETENV 1 )
set ( HAVE_USLEEP 1 )
# set ( HAVE_UTEMPTER 1 )
set ( HAVE_VSNPRINTF 1  ) 
# set ( HAVE__GETPTY 1 )
# set ( HAVE_NSGETENVIRON 1 )
# set ( HAVE___ARGZ_COUNT 1 )
# set ( HAVE___ARGZ_NEXT  1 )
# set ( HAVE___ARGZ_STRINGIFY 1 )

