/* config.h. Generated by cmake from config.h.cmake */

/* NOTE: only add something here if it is really needed by all of kdelibs.
   Otherwise please prefer adding to the relevant config-foo.h.cmake file,
   to minimize recompilations and increase modularity. */

/****************************/

#define kde_socklen_t socklen_t

#define KDELIBSUFF "${KDELIBSUFF}"

/****************************/

/* Define to 1 if you have stdlib.h */
#cmakedefine01   HAVE_STDLIB_H

/* Define to 1 if you have string.h */
#cmakedefine01   HAVE_STRING_H

/* Define to 1 if you have strings.h */
#cmakedefine01   HAVE_STRINGS_H

/* Define to 1 if you have malloc.h */
#cmakedefine01   HAVE_MALLOC_H

#cmakedefine01 HAVE_VOLMGT

#cmakedefine01 HAVE_ERRNO_H
#cmakedefine01 HAVE_STDINT_H
#cmakedefine01 HAVE_SYS_STAT_H
#cmakedefine01 HAVE_SYS_TYPES_H
#cmakedefine01 HAVE_SYS_PARAM_H
#cmakedefine01 HAVE_SYS_TIME_H
#cmakedefine01 HAVE_SYS_SELECT_H
#cmakedefine01 HAVE_SYSENT_H
#cmakedefine01 HAVE_SYS_MNTTAB_H
#cmakedefine01 HAVE_SYS_MNTENT_H
#cmakedefine01 HAVE_SYS_MOUNT_H
#cmakedefine01 HAVE_CRTDBG_H

#cmakedefine01 HAVE_ALLOCA_H
#cmakedefine01 HAVE_CRT_EXTERNS_H
#cmakedefine01 HAVE_FSTAB_H
#cmakedefine01 HAVE_MNTENT_H
#cmakedefine01 HAVE_PATHS_H
#cmakedefine01 HAVE_UNISTD_H

#cmakedefine01 HAVE_X11
#cmakedefine01 HAVE_XTEST

/* Define to 1 if you have the Xcursor library */
#cmakedefine01 HAVE_XCURSOR

/* Define to 1 if you have the Xfixes library */
#cmakedefine01 HAVE_XFIXES

/* Define to 1 if you have the Xrender library */
#cmakedefine01 HAVE_XRENDER

#cmakedefine01   HAVE_BACKTRACE
#cmakedefine01   HAVE_GETMNTINFO
#cmakedefine01   HAVE_GETPAGESIZE
#cmakedefine01   HAVE_INITGROUPS
#cmakedefine01   HAVE_FDATASYNC
#cmakedefine01   HAVE_MADVISE
#cmakedefine01   HAVE_MMAP
#cmakedefine01   HAVE_MKSTEMPS
#cmakedefine01   HAVE_MKSTEMP
#cmakedefine01   HAVE_RANDOM
#cmakedefine01   HAVE_SENDFILE
#cmakedefine01   HAVE_SETENV
#cmakedefine01   HAVE_SETEUID
#cmakedefine01   HAVE_SETMNTENT
#cmakedefine01   HAVE_SRANDOM
#cmakedefine01   HAVE_STRCMP
#cmakedefine01   HAVE_STRLCPY
#cmakedefine01   HAVE_STRLCAT
#cmakedefine01   HAVE_STRCASESTR
#cmakedefine01   HAVE_STRRCHR
#cmakedefine01   HAVE_STRTOLL
#cmakedefine01   HAVE_UNSETENV
#cmakedefine01   HAVE_USLEEP
#cmakedefine01   HAVE_VSNPRINTF
#cmakedefine01   HAVE_NSGETENVIRON
#cmakedefine01   HAVE_GETTIMEOFDAY
#cmakedefine01   HAVE_GETGROUPLIST

#cmakedefine01 HAVE_S_ISSOCK

#cmakedefine01 TIME_WITH_SYS_TIME

/*********************/

#ifndef HAVE_S_ISSOCK
#define HAVE_S_ISSOCK
#define S_ISSOCK(mode) (1==0)
#endif

/*
 * On HP-UX, the declaration of vsnprintf() is needed every time !
 */

#if !HAVE_VSNPRINTF || defined(hpux)
#if __STDC__
#include <stdarg.h>
#include <stdlib.h>
#else
#include <varargs.h>
#endif
#ifdef __cplusplus
extern "C"
#endif
int vsnprintf(char *str, size_t n, char const *fmt, va_list ap);
#ifdef __cplusplus
extern "C"
#endif
int snprintf(char *str, size_t n, char const *fmt, ...);
#endif

#if HAVE_NSGETENVIRON && HAVE_CRT_EXTERNS_H
# include <sys/time.h>
# include <crt_externs.h>
# define environ (*_NSGetEnviron())
#endif

#cmakedefine01 GETMNTINFO_USES_STATVFS

/* Defined to if you have a d_type member in struct dirent */
#cmakedefine01 HAVE_DIRENT_D_TYPE

#include "kdecore/kdefakes.h"
