all: 
	@echo "This Makefile is only for the CVS repository"
	@echo "I will delete it before making the distribution"
	@echo ""
	aclocal 
	autoheader
	automake
	autoconf

dist:
	@aclocal ;\
	autoheader ;\
	automake --foreign --include-deps ;\
	autoconf ;\
	LIST=`find ./po -name "*.po"`; \
	for i in $$LIST; do \
	 file2=`echo $$i | sed -e "s#\.po#\.gmo#"`; \
	 msgfmt -o $$file2 $$i; \
	done
