QWidget
QWidget::QWidget(QWidget *parent=0, Qt::WFlags f=0)
QWidget::~QWidget()
int QWidget::devType() const
WId QWidget::winId() const
References QWidgetData::winid.
QStyle* QWidget::style() const
void QWidget::setStyle(QStyle *)
bool QWidget::isTopLevel() const
References windowType.
bool QWidget::isWindow() const
References windowType.
bool QWidget::isModal() const
References QWidgetData::window_modality.
Qt::WindowModality QWidget::windowModality() const
void QWidget::setWindowModality(Qt::WindowModality windowModality)
bool QWidget::isEnabled() const
References testAttribute.
Referenced by isEnabledToTLW.
bool QWidget::isEnabledTo(QWidget *) const
bool QWidget::isEnabledToTLW() const
References isEnabled.
void QWidget::setDisabled(bool)
void QWidget::setWindowModified(bool)
QRect QWidget::frameGeometry() const
const QRect& QWidget::geometry() const
QRect QWidget::normalGeometry() const
int QWidget::x() const
int QWidget::y() const
QPoint QWidget::pos() const
QSize QWidget::frameSize() const
QSize QWidget::size() const
int QWidget::width() const
int QWidget::height() const
QRect QWidget::rect() const
QRect QWidget::childrenRect() const
QRegion QWidget::childrenRegion() const
QSize QWidget::minimumSize() const
QSize QWidget::maximumSize() const
int QWidget::minimumWidth() const
int QWidget::minimumHeight() const
int QWidget::maximumWidth() const
int QWidget::maximumHeight() const
void QWidget::setMinimumSize(const QSize &)
void QWidget::setMinimumSize(int minw, int minh)
void QWidget::setMaximumSize(const QSize &)
void QWidget::setMaximumSize(int maxw, int maxh)
void QWidget::setMinimumWidth(int minw)
void QWidget::setMinimumHeight(int minh)
void QWidget::setMaximumWidth(int maxw)
void QWidget::setMaximumHeight(int maxh)
QSize QWidget::sizeIncrement() const
void QWidget::setSizeIncrement(const QSize &)
void QWidget::setSizeIncrement(int w, int h)
QSize QWidget::baseSize() const
void QWidget::setBaseSize(const QSize &)
void QWidget::setBaseSize(int basew, int baseh)
void QWidget::setFixedSize(const QSize &)
void QWidget::setFixedSize(int w, int h)
void QWidget::setFixedWidth(int w)
void QWidget::setFixedHeight(int h)
QPoint QWidget::mapToGlobal(const QPoint &) const
QPoint QWidget::mapFromGlobal(const QPoint &) const
QPoint QWidget::mapToParent(const QPoint &) const
QPoint QWidget::mapFromParent(const QPoint &) const
QPoint QWidget::mapTo(QWidget *, const QPoint &) const
QPoint QWidget::mapFrom(QWidget *, const QPoint &) const
QWidget* QWidget::window() const
QWidget* QWidget::topLevelWidget() const
const QPalette& QWidget::palette() const
void QWidget::setPalette(const QPalette &)
void QWidget::setBackgroundRole(QPalette::ColorRole)
QPalette::ColorRole QWidget::backgroundRole() const
void QWidget::setForegroundRole(QPalette::ColorRole)
QPalette::ColorRole QWidget::foregroundRole() const
const QFont& QWidget::font() const
void QWidget::setFont(const QFont &)
QFontMetrics QWidget::fontMetrics() const
References QWidgetData::fnt, QFontMetrics.
QFontInfo QWidget::fontInfo() const
References QWidgetData::fnt, QFontInfo.
QCursor QWidget::cursor() const
void QWidget::setCursor(const QCursor &)
void QWidget::unsetCursor()
void QWidget::setMouseTracking(bool enable)
References setAttribute.
bool QWidget::hasMouseTracking() const
References testAttribute.
bool QWidget::underMouse() const
References testAttribute.
void QWidget::setMask(const QBitmap &)
void QWidget::setMask(const QRegion &)
QRegion QWidget::mask() const
void QWidget::clearMask()
void QWidget::setWindowTitle(const QString &)
QString QWidget::windowTitle() const
void QWidget::setWindowIcon(const QIcon &icon)
QIcon QWidget::windowIcon() const
void QWidget::setWindowIconText(const QString &)
QString QWidget::windowIconText() const
void QWidget::setWindowRole(const QString &)
QString QWidget::windowRole() const
void QWidget::setWindowOpacity(qreal level)
qreal QWidget::windowOpacity() const
bool QWidget::isWindowModified() const
void QWidget::setToolTip(const QString &)
QString QWidget::toolTip() const
void QWidget::setStatusTip(const QString &)
QString QWidget::statusTip() const
void QWidget::setWhatsThis(const QString &)
QString QWidget::whatsThis() const
QString QWidget::accessibleName() const
void QWidget::setAccessibleName(const QString &name)
QString QWidget::accessibleDescription() const
void QWidget::setAccessibleDescription(const QString &description)
void QWidget::setLayoutDirection(Qt::LayoutDirection direction)
Qt::LayoutDirection QWidget::layoutDirection() const
void QWidget::unsetLayoutDirection()
bool QWidget::isRightToLeft() const
bool QWidget::isLeftToRight() const
bool QWidget::isActiveWindow() const
void QWidget::activateWindow()
void QWidget::clearFocus()
void QWidget::setFocus(Qt::FocusReason reason)
Qt::FocusPolicy QWidget::focusPolicy() const
void QWidget::setFocusPolicy(Qt::FocusPolicy policy)
bool QWidget::hasFocus() const
void QWidget::setFocusProxy(QWidget *)
QWidget* QWidget::focusProxy() const
Qt::ContextMenuPolicy QWidget::contextMenuPolicy() const
void QWidget::setContextMenuPolicy(Qt::ContextMenuPolicy policy)
void QWidget::grabMouse()
void QWidget::grabMouse(const QCursor &)
void QWidget::releaseMouse()
void QWidget::grabKeyboard()
void QWidget::releaseKeyboard()
int QWidget::grabShortcut(const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
void QWidget::releaseShortcut(int id)
void QWidget::setShortcutEnabled(int id, bool enable=true)
bool QWidget::updatesEnabled() const
void QWidget::setUpdatesEnabled(bool enable)
void QWidget::repaint()
void QWidget::update(int x, int y, int w, int h)
void QWidget::update(const QRect &)
void QWidget::update(const QRegion &)
void QWidget::repaint(int x, int y, int w, int h)
void QWidget::repaint(const QRect &)
void QWidget::repaint(const QRegion &)
void QWidget::setHidden(bool hidden)
void QWidget::show()
void QWidget::hide()
QT_MOC_COMPAT void QWidget::setShown(bool shown)
void QWidget::showMinimized()
void QWidget::showMaximized()
void QWidget::showFullScreen()
void QWidget::showNormal()
bool QWidget::close()
void QWidget::raise()
void QWidget::lower()
void QWidget::stackUnder(QWidget *)
void QWidget::move(int x, int y)
void QWidget::move(const QPoint &)
void QWidget::resize(int w, int h)
void QWidget::resize(const QSize &)
void QWidget::setGeometry(int x, int y, int w, int h)
void QWidget::setGeometry(const QRect &)
void QWidget::adjustSize()
bool QWidget::isVisible() const
References testAttribute.
bool QWidget::isVisibleTo(QWidget *) const
bool QWidget::isHidden() const
References testAttribute.
bool QWidget::isMinimized() const
bool QWidget::isMaximized() const
bool QWidget::isFullScreen() const
Qt::WindowStates QWidget::windowState() const
void QWidget::setWindowState(Qt::WindowStates state)
void QWidget::overrideWindowState(Qt::WindowStates state)
virtual QSize QWidget::sizeHint() const
virtual QSize QWidget::minimumSizeHint() const
QSizePolicy QWidget::sizePolicy() const
void QWidget::setSizePolicy(QSizePolicy)
Referenced by setSizePolicy.
void QWidget::setSizePolicy(QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
References setSizePolicy.
virtual int QWidget::heightForWidth(int) const
QRegion QWidget::visibleRegion() const
void QWidget::setContentsMargins(int left, int top, int right, int bottom)
void QWidget::getContentsMargins(int *left, int *top, int *right, int *bottom) const
QRect QWidget::contentsRect() const
QLayout* QWidget::layout() const
void QWidget::setLayout(QLayout *)
void QWidget::updateGeometry()
void QWidget::setParent(QWidget *parent)
void QWidget::setParent(QWidget *parent, Qt::WFlags f)
void QWidget::scroll(int dx, int dy)
void QWidget::scroll(int dx, int dy, const QRect &)
QWidget* QWidget::focusWidget() const
QWidget* QWidget::nextInFocusChain() const
bool QWidget::acceptDrops() const
void QWidget::setAcceptDrops(bool on)
void QWidget::addAction(QAction *action)
void QWidget::addActions(QList< QAction * > actions)
void QWidget::insertAction(QAction *before, QAction *action)
void QWidget::insertActions(QAction *before, QList< QAction * > actions)
void QWidget::removeAction(QAction *action)
QList<QAction*> QWidget::actions() const
QWidget * QWidget::parentWidget() const
void QWidget::setWindowFlags(Qt::WindowFlags type)
Qt::WindowFlags QWidget::windowFlags() const
References QWidgetData::window_flags.
void QWidget::overrideWindowFlags(Qt::WindowFlags type)
Qt::WindowType QWidget::windowType() const
References QWidgetData::window_flags.
Referenced by isTopLevel, isWindow.
QWidget * QWidget::childAt(int x, int y) const
QWidget* QWidget::childAt(const QPoint &p) const
Qt::HANDLE QWidget::handle() const
void QWidget::setAttribute(Qt::WidgetAttribute, bool on=true)
Referenced by setMouseTracking.
bool QWidget::testAttribute(Qt::WidgetAttribute) const
References QWidgetData::widget_attributes.
Referenced by hasMouseTracking, isEnabled, isHidden, isVisible, underMouse.
QPaintEngine* QWidget::paintEngine() const
void QWidget::ensurePolished() const
QInputContext* QWidget::inputContext()
void QWidget::setInputContext(QInputContext *)
bool QWidget::isAncestorOf(const QWidget *child) const
bool QWidget::autoFillBackground() const
void QWidget::setAutoFillBackground(bool enabled)
virtual QVariant QWidget::inputMethodQuery(Qt::InputMethodQuery) const
public QWidget::Q_SLOTS
Q_SIGNALS QWidget::__pad0__
bool QWidget::modal
Qt QWidget::WindowModality
bool QWidget::enabled
const QRect & QWidget::geometry
QRect QWidget::frameGeometry
QRect QWidget::normalGeometry
int QWidget::x
int QWidget::y
QPoint QWidget::pos
QSize QWidget::frameSize
QSize QWidget::size
int QWidget::width
int QWidget::height
QRect QWidget::rect
QRect QWidget::childrenRect
QRegion QWidget::childrenRegion
QSizePolicy QWidget::sizePolicy
QSize QWidget::minimumSize
QSize QWidget::maximumSize
int QWidget::minimumWidth
int QWidget::minimumHeight
int QWidget::maximumWidth
int QWidget::maximumHeight
QSize QWidget::sizeIncrement
QSize QWidget::baseSize
QPalette QWidget::palette
const QFont & QWidget::font
QCursor QWidget::cursor
bool QWidget::mouseTracking
bool QWidget::isActiveWindow
Qt QWidget::FocusPolicy
bool QWidget::focus
Qt QWidget::ContextMenuPolicy
bool QWidget::updatesEnabled
bool QWidget::visible
bool QWidget::minimized
bool QWidget::maximized
bool QWidget::fullScreen
QSize QWidget::sizeHint
QSize QWidget::minimumSizeHint
bool QWidget::acceptDrops
QString QWidget::windowTitle
QIcon QWidget::windowIcon
QString QWidget::windowIconText
double QWidget::windowOpacity
bool QWidget::windowModified
QString QWidget::toolTip
QString QWidget::statusTip
QString QWidget::whatsThis
QString QWidget::accessibleName
QString QWidget::accessibleDescription
Qt QWidget::LayoutDirection
bool QWidget::autoFillBackground
static void QWidget::setTabOrder(QWidget *, QWidget *)
static QWidget* QWidget::mouseGrabber()
static QWidget* QWidget::keyboardGrabber()
static QWidget* QWidget::find(WId)
bool QWidget::event(QEvent *)
virtual void QWidget::mousePressEvent(QMouseEvent *)
virtual void QWidget::mouseReleaseEvent(QMouseEvent *)
virtual void QWidget::mouseDoubleClickEvent(QMouseEvent *)
virtual void QWidget::mouseMoveEvent(QMouseEvent *)
virtual void QWidget::wheelEvent(QWheelEvent *)
virtual void QWidget::keyPressEvent(QKeyEvent *)
virtual void QWidget::keyReleaseEvent(QKeyEvent *)
virtual void QWidget::focusInEvent(QFocusEvent *)
virtual void QWidget::focusOutEvent(QFocusEvent *)
virtual void QWidget::enterEvent(QEvent *)
virtual void QWidget::leaveEvent(QEvent *)
virtual void QWidget::paintEvent(QPaintEvent *)
virtual void QWidget::moveEvent(QMoveEvent *)
virtual void QWidget::resizeEvent(QResizeEvent *)
virtual void QWidget::closeEvent(QCloseEvent *)
virtual void QWidget::contextMenuEvent(QContextMenuEvent *)
virtual void QWidget::tabletEvent(QTabletEvent *)
virtual void QWidget::actionEvent(QActionEvent *)
virtual void QWidget::dragEnterEvent(QDragEnterEvent *)
virtual void QWidget::dragMoveEvent(QDragMoveEvent *)
virtual void QWidget::dragLeaveEvent(QDragLeaveEvent *)
virtual void QWidget::dropEvent(QDropEvent *)
virtual void QWidget::showEvent(QShowEvent *)
virtual void QWidget::hideEvent(QHideEvent *)
virtual void QWidget::changeEvent(QEvent *)
int QWidget::metric(PaintDeviceMetric) const
virtual void QWidget::inputMethodEvent(QInputMethodEvent *)
void QWidget::resetInputContext()
void QWidget::updateMicroFocus()
void QWidget::create(WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
void QWidget::destroy(bool destroyWindow=true, bool destroySubWindows=true)
virtual bool QWidget::focusNextPrevChild(bool next)
bool QWidget::focusNextChild()
bool QWidget::focusPreviousChild()
QWidget::QWidget(QWidgetPrivate &d, QWidget *parent, Qt::WFlags f)
virtual void QWidget::styleChange(QStyle &)
virtual void QWidget::enabledChange(bool)
virtual void QWidget::paletteChange(const QPalette &)
virtual void QWidget::fontChange(const QFont &)
virtual void QWidget::windowActivationChange(bool)
virtual void QWidget::languageChange()
bool QWidget::testAttribute_helper(Qt::WidgetAttribute) const
QWidgetData* QWidget::data
friend class QBackingStoreDevice
friend class QWidgetBackingStore
friend class QApplication
friend class QApplicationPrivate
friend class QBaseApplication
friend class QPainter
friend class QPixmap
friend class QFontMetrics
Referenced by fontMetrics.
friend class QFontInfo
Referenced by fontInfo.
friend class QETWidget
friend class QLayout
friend class QWidgetItem
friend class QGLContext
friend class QX11PaintEngine
friend class QWin32PaintEngine
friend class QShortcutPrivate
void qt_syncBackingStore(QWidget *)
void qt_syncBackingStore(QRegion, QWidget *)
void qt_syncBackingStore(QRegion, QWidget *, bool)