#!/bin/sh
#
# creates bksys documentation  (requires doxygen >= 1.4.4)
# 
# (@) 2005 by Ralf Habacker 
#  
echo "/** @page design Design" >doc/design.dox
echo "<pre>" >>doc/design.dox
cat design >>doc/design.dox
echo "</pre> */" >>doc/design.dox 

doxygen doc/bksys.doxy
rm doc/design.dox

 