/* Automatically generated from date_object.cpp using ./create_hash_table. DO NOT EDIT ! */

#include "lookup.h"

namespace KJS {

const struct HashEntry dateTableEntries[] = {
   { "setMilliseconds", DateProtoFuncImp::SetMilliSeconds, DontEnum|DontDelete|ReadOnly|Function, 1, 0 },
   { "setYear", DateProtoFuncImp::SetYear, DontEnum|DontDelete|ReadOnly|Function, 1, 0 },
   { "toLocaleDateString", DateProtoFuncImp::ToLocaleDateString, DontEnum|DontDelete|ReadOnly|Function, 0, &dateTableEntries[64] },
   { 0, 0, 0, 0, 0 },
   { "toString", DateProtoFuncImp::ToString, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "setUTCSeconds", -DateProtoFuncImp::SetSeconds, DontEnum|DontDelete|ReadOnly|Function, 2, 0 },
   { "setHours", DateProtoFuncImp::SetHours, DontEnum|DontDelete|ReadOnly|Function, 4, 0 },
   { 0, 0, 0, 0, 0 },
   { "getTimezoneOffset", DateProtoFuncImp::GetTimezoneOffset, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "setSeconds", DateProtoFuncImp::SetSeconds, DontEnum|DontDelete|ReadOnly|Function, 2, 0 },
   { 0, 0, 0, 0, 0 },
   { "getUTCMinutes", -DateProtoFuncImp::GetMinutes, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "getUTCFullYear", -DateProtoFuncImp::GetFullYear, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { "toLocaleTimeString", DateProtoFuncImp::ToLocaleTimeString, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { "toDateString", DateProtoFuncImp::ToDateString, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "getUTCDate", -DateProtoFuncImp::GetDate, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { "getMinutes", DateProtoFuncImp::GetMinutes, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "getFullYear", DateProtoFuncImp::GetFullYear, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "setUTCMinutes", -DateProtoFuncImp::SetMinutes, DontEnum|DontDelete|ReadOnly|Function, 3, 0 },
   { 0, 0, 0, 0, 0 },
   { "setUTCFullYear", -DateProtoFuncImp::SetFullYear, DontEnum|DontDelete|ReadOnly|Function, 3, 0 },
   { "getDate", DateProtoFuncImp::GetDate, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "setUTCDate", -DateProtoFuncImp::SetDate, DontEnum|DontDelete|ReadOnly|Function, 1, 0 },
   { "setMinutes", DateProtoFuncImp::SetMinutes, DontEnum|DontDelete|ReadOnly|Function, 3, 0 },
   { "toTimeString", DateProtoFuncImp::ToTimeString, DontEnum|DontDelete|ReadOnly|Function, 0, &dateTableEntries[61] },
   { "setFullYear", DateProtoFuncImp::SetFullYear, DontEnum|DontDelete|ReadOnly|Function, 3, 0 },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "getUTCMilliseconds", -DateProtoFuncImp::GetMilliSeconds, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "setDate", DateProtoFuncImp::SetDate, DontEnum|DontDelete|ReadOnly|Function, 1, 0 },
   { 0, 0, 0, 0, 0 },
   { "getMonth", DateProtoFuncImp::GetMonth, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "toLocaleString", DateProtoFuncImp::ToLocaleString, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { "getTime", DateProtoFuncImp::GetTime, DontEnum|DontDelete|ReadOnly|Function, 0, &dateTableEntries[63] },
   { "getUTCDay", -DateProtoFuncImp::GetDay, DontEnum|DontDelete|ReadOnly|Function, 0, &dateTableEntries[65] },
   { "getYear", DateProtoFuncImp::GetYear, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { "valueOf", DateProtoFuncImp::ValueOf, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "toGMTString", DateProtoFuncImp::ToGMTString, DontEnum|DontDelete|ReadOnly|Function, 0, &dateTableEntries[66] },
   { 0, 0, 0, 0, 0 },
   { "getUTCSeconds", -DateProtoFuncImp::GetSeconds, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { "getHours", DateProtoFuncImp::GetHours, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { "toUTCString", -DateProtoFuncImp::ToString, DontEnum|DontDelete|ReadOnly|Function, 0, &dateTableEntries[62] },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "setTime", DateProtoFuncImp::SetTime, DontEnum|DontDelete|ReadOnly|Function, 1, &dateTableEntries[67] },
   { "getUTCMonth", -DateProtoFuncImp::GetMonth, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { "getDay", DateProtoFuncImp::GetDay, DontEnum|DontDelete|ReadOnly|Function, 0, &dateTableEntries[68] },
   { "getUTCHours", -DateProtoFuncImp::GetHours, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { "getSeconds", DateProtoFuncImp::GetSeconds, DontEnum|DontDelete|ReadOnly|Function, 0, 0 },
   { "getMilliseconds", DateProtoFuncImp::GetMilliSeconds, DontEnum|DontDelete|ReadOnly|Function, 0, &dateTableEntries[69] },
   { "setUTCMilliseconds", -DateProtoFuncImp::SetMilliSeconds, DontEnum|DontDelete|ReadOnly|Function, 1, &dateTableEntries[70] },
   { "setUTCHours", -DateProtoFuncImp::SetHours, DontEnum|DontDelete|ReadOnly|Function, 4, 0 },
   { "setMonth", DateProtoFuncImp::SetMonth, DontEnum|DontDelete|ReadOnly|Function, 2, 0 },
   { "setUTCMonth", -DateProtoFuncImp::SetMonth, DontEnum|DontDelete|ReadOnly|Function, 2, 0 },
   { "toGMTString", DateProtoFuncImp::ToGMTString, DontEnum|DontDelete|ReadOnly|Function, 0, 0 }
};

const struct HashTable dateTable = { 2, 71, dateTableEntries, 61 };

}; // namespace
