#!/usr/bin/env python

import os
Import('env')

obj = env.qt4obj('shlib',env)
obj.vnum     = '2.0.1'
obj.target   = 'libQtTest'
obj.source   = Split("""qtestcase.cpp 
    qtestlog.cpp qtesttable.cpp qtestdata.cpp qtestresult.cpp
    qasciikey.cpp qplaintestlogger.cpp qxmltestlogger.cpp
    qsignaldumper.cpp qabstracttestlogger.cpp""")
obj.cxxflags = '-DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_NO_DATASTREAM -DQTESTLIB_MAKEDLL'
obj.uselib   = 'QTCORE KDE4'
obj.execute()

"""
lib_LTLIBRARIES = libqttestlib.la

libqttestlib_la_SOURCES = qtestcase.cpp qtestlog.cpp qtesttable.cpp qtestdata.cpp qtestresult.cpp qasciikey.cpp qplaintestlogger.cpp qxmltestlogger.cpp qsignaldumper.cpp qabstracttestlogger.cpp
libqttestlib_la_LIBADD = $(LIB_QTCORE)
libqttestlib_la_LDFLAGS = $(KDE_RPATH) $(KDE_MT_LDFLAGS) $(all_libraries) -no-undefined -version-info 6:1:2

AM_CPPFLAGS = $(all_includes) -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_NO_DATASTREAM -DQTESTLIB_MAKEDLL

qttestlibdir = $(includedir)/QtTest
qttestlib_HEADERS = QtTest/qttest_global.h QtTest/qttestcase.h QtTest/qttesttable.h QtTest/qttestdata.h QtTest/QtTest QtTest/qttest.h QtTest/qsignalspy.h QtTest/qttestsystem.h QtTest/qttesteventloop.h QtTest/qttest_gui.h QtTest/qttestassert.h QtTest/qttestevent.h QtTest/qttestmouse.h QtTest/qttestkeyboard.h
"""
