#line 2 "scanner.cc"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 51
#define YY_END_OF_BUFFER 52
static yyconst short int yy_acclist[590] =
    {   0,
        5,    5,   52,    5,   50,   51,    1,    5,   50,   51,
        2,   51,    5,   50,   51,    5,   50,   51,    5,   17,
       50,   51,    5,   50,   51,    5,   12,   50,   51,    5,
       13,   50,   51,    5,   50,   51,    5,   15,   50,   51,
        5,   50,   51,    5,   50,   51,    5,   32,   46,   50,
       51,    5,   45,   50,   51,    5,   14,   50,   51,    5,
       16,   50,   51,    5,   18,   50,   51,    5,   21,   50,
       51,    5,   19,   50,   51,    5,   39,   50,   51,    5,
       39,   50,   51,    5,   39,   50,   51,    5,   39,   50,
       51,    5,   39,   50,   51,    5,   39,   50,   51,    5,

       39,   50,   51,    5,   39,   50,   51,    5,   39,   50,
       51,    5,   39,   50,   51,    5,   10,   50,   51,    5,
       11,   50,   51,    5,    5,    5,    5,   49,    5,    5,
        5,    9,    5,    7,    5,    5,    5,    5,    5,    4,
        5,    5,   43,    3,    5,    5,    6,    5,    5,   46,
        5,    5,    5,   47,    5,   45,    5,   20,    5,   39,
        5,   39,    5,   39,    5,   39,    5,   39,    5,   39,
        5,   39,    5,   39,    5,   39,    5,   39,    5,   39,
        5,   39,    4,    5,    5,    5,    5,    7,    5,    7,
        4,    5,    5,    5,   48,    5,    5,    4,    5,    4,

        5,    5,    3,    5,    3,    5,    3,    4,    5,    5,
        6,    5,    6,    5,   42,    5,    5,   41,    5,   47,
        5,   39,    5,   39,    5,   39,    5,   39,    5,   39,
        5,   39,    5,   39,    5,   39,    5,   39,    5,   39,
        5,   39,    5,   39,    4,    5,    4,    5,   49,    4,
        5,    4,    5,    5,    5,    4,    5,    7,    4,    5,
        4,    5,    5,    5,    5,    4,    5,    5,    5,   44,
        3,    5,    3,    4,    5,    4,    5,    4,    5,    6,
        5,    5,   39,    5,   39,    5,   39,    5,   39,    5,
       23,   39,    5,   39,    5,   39,    5,   39,    5,   39,

        5,   39,    5,   39,    5,   39,    4,    5,    4,    5,
        4,    5,    5,    5,    4,    5,    7,    4,    5,    7,
        4,    5,    5,    5,    3,    4,    5,    4,    5,    6,
        4,    5,    6,    5,    5,   40,    5,   39,    5,   39,
        5,   24,   39,    5,   22,   39,    5,   39,    5,   39,
        5,   39,    5,   39,    5,   39,    5,   39,    5,   39,
        4,    5,    4,    5,    4,    5,    7,    5,    3,    4,
        5,    4,    5,    6,    5,   30,   39,    5,   39,    5,
       28,   39,    5,   39,    5,   39,    5,   27,   39,    5,
       25,   39,    5,   39,    5,   39,    4,    5,    4,    5,

        5,    5,   39,    5,   39,    5,   39,    5,    5,    5,
       29,   39,    5,   26,   39,    5,    5,   31,   39,    5,
        5,   39,    5,    5,    5,    5,    5,   36,    5,    5,
        5,    5,    5,   34,    5,   39,    5,   36,    4,    5,
        5,    5,   34,    4,    5,    5,    5,    5,    4,    5,
        4,    5,    4,    5,    4,    5,   36,    5,    5,    9,
        5,    5,    4,    5,    4,    5,    4,    5,    4,    5,
       34,    5,    5,    5,    5,    5,   37,    5,    4,    5,
        4,    5,    5,    4,    5,    8,    9,    5,    4,    5,
        4,    5,    5,   37,    4,    5,    5,    5,    4,    5,

        5,    8,    4,    5,    4,    5,    4,    5,    4,    5,
        5,    4,    5,    4,    5,    4,    5,    4,    5,   37,
        5,    5,    4,    5,    5,   35,    4,    5,    4,    5,
        4,    5,    5,   33,    4,    5,    4,    5,    5,    5,
        5,    5,    5,   38,   35,    4,    5,   33,    4,    5,
        4,    5,    5,   38,    4,    5,    5,    4,    5,   35,
        4,    5,   33,    4,    5,    4,    5,    4,    5,    4,
        5,    4,    5,   38,    5,    4,    5,    4,    5,    4,
        5,    5,    4,    5,    5,    4,    5,    4,    5
    } ;

static yyconst short int yy_accept[330] =
    {   0,
        1,    2,    3,    4,    7,   11,   13,   16,   19,   23,
       26,   30,   34,   37,   41,   44,   47,   52,   56,   60,
       64,   68,   72,   76,   80,   84,   88,   92,   96,  100,
      104,  108,  112,  116,  120,  124,  125,  126,  127,  129,
      130,  131,  132,  133,  135,  136,  137,  138,  139,  140,
      142,  144,  146,  148,  149,  151,  152,  153,  155,  157,
      159,  161,  163,  165,  167,  169,  171,  173,  175,  177,
      179,  181,  183,  185,  186,  187,  189,  191,  193,  194,
      196,  197,  198,  200,  202,  203,  205,  206,  207,  210,
      212,  214,  216,  217,  219,  221,  223,  225,  227,  229,

      231,  233,  235,  237,  239,  241,  243,  245,  247,  250,
      252,  254,  255,  256,  259,  261,  263,  264,  265,  266,
      268,  269,  271,  271,  273,  276,  278,  281,  282,  284,
      286,  288,  290,  293,  295,  297,  299,  301,  303,  305,
      307,  309,  311,  313,  314,  315,  318,  321,  323,  324,
      325,  328,  331,  334,  335,  337,  339,  341,  344,  347,
      349,  351,  353,  355,  357,  359,  361,  363,  365,  368,
      369,  372,  375,  378,  380,  383,  385,  387,  390,  393,
      395,  397,  399,  401,  402,  404,  406,  408,  409,  410,
      413,  416,  417,  420,  421,  423,  424,  425,  425,  426,

      427,  429,  430,  431,  431,  432,  433,  435,  437,  438,
      438,  439,  441,  442,  443,  443,  444,  446,  447,  448,
      449,  449,  451,  453,  455,  458,  459,  460,  461,  462,
      463,  463,  465,  467,  469,  472,  473,  474,  474,  475,
      476,  478,  479,  479,  481,  483,  484,  484,  484,  486,
      488,  489,  489,  491,  493,  494,  494,  495,  497,  498,
      499,  499,  501,  502,  503,  503,  505,  507,  509,  509,
      511,  512,  512,  514,  516,  518,  521,  522,  523,  523,
      525,  527,  529,  531,  531,  533,  535,  535,  537,  539,
      540,  541,  541,  542,  543,  545,  546,  548,  549,  551,

      551,  553,  554,  554,  555,  557,  558,  561,  564,  564,
      566,  566,  568,  570,  572,  575,  576,  578,  578,  580,
      582,  583,  583,  585,  586,  586,  588,  590,  590
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    1,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   27,
       32,   32,   32,   33,   34,   32,   32,   32,   35,   36,
       37,   32,   32,   38,   32,   32,   32,   39,   32,   32,
        1,   40,    1,    1,   41,    1,   42,   43,   44,   45,

       46,   47,   32,   32,   48,   32,   49,   50,   51,   52,
       53,   54,   32,   55,   56,   57,   58,   59,   32,   60,
       61,   32,   62,    1,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1
    } ;

static yyconst short int yy_base[358] =
    {   0,
        0,    0, 1075, 1062, 1061, 1076,   62,   64, 1015,   63,
     1014, 1013,   54, 1012,   61,   65,   74,   79,   66, 1011,
     1010, 1009, 1007,  134,  977,  976,   35,  964,  974,   46,
      956,  951,  962,  997,  996,  994,   72,  196,  992,  197,
      232,   97, 1076,  103,  104,  201,   99,  105,  287,  990,
      199,  115,  987,  111,  208,  249,  244,  336,  291,  983,
        0,  964,  958,  950,  939,  931,  943,   71,  941,  925,
      924,  918,  264,  296,  366,  125,  198,  204,  237,  960,
      213,  396,  955,  188,  305,  209,  947,  230,  231,  932,
      243,  331,  340,  356,    0,  910,  905,  864,  857,  858,

      861,  842,  842,  848,  829,  829,  816,  276,  839,  416,
      451,  443,  510,  274,  282,  316,  386,  435,  549,  828,
      387,  446,  809,  328,  287,  417,  813,  460,  787,  787,
      763,  750,    0,  752,  762,  756,  740,  743,  738,  717,
      480,  483,  585,  503,  519,  309,  418,  329,  388,  288,
      464,  761,  375,  514,  552,  736,  738,    0,    0,  703,
      697,  706,  705,  679,  679,  681,  605,  644,  358,  501,
      447,  708,    0,  690,    0,  672,  623,  202,    0,  631,
      617,  596,  636,  515,  621,  634,  608,  217,  570,    0,
        0,  484,    0,  571,  596,  323,  572,  308,  648,  548,

      598,  646,  654,  339,  665,  640,  667,  616,  378,  585,
      354,  680,  682,  597,  577,  388,  690,  692,  693,  440,
      561,  695,  696,  697,  698,  719,  709,  562,  723,  532,
      540,  703,  729,  721,  748,  752,  764,  451,  765,  762,
      767,  392,  537,  768,  778,  533,  541,  245,  781, 1076,
      782,  521,  783,  788,  587,  506,  499,  786,  796,  632,
      489,  798,  806, 1076,  468,  809,  812,  833,  466,  836,
      840,  472,  841,  844,  847,  851,  852,  854,  453,  855,
      487,  859,  862,  430,  866,  462,  424,  867,  865,  869,
      879,  500,  880,  883,  899, 1076,  873, 1076,  903,  379,

      909,  920,  378,  576,  922,  923,  389,  360,  315,  928,
      308,  933,  934,  935,  938,  946,  949,  294,  951,  953,
      952,  230,  963,  957,  198,  967,  974, 1076,  245,  234,
     1028,  132, 1030,  125, 1032,   95,   82, 1034, 1036, 1038,
     1040,   69, 1042, 1044, 1046, 1048, 1050, 1052, 1054, 1056,
     1058, 1060, 1062, 1064, 1066, 1068, 1070
    } ;

static yyconst short int yy_def[358] =
    {   0,
      328,    1,  328,  329,  329,  328,  330,  331,  329,  332,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  328,   24,   24,   24,   24,   24,   24,
       24,   24,   24,  329,  329,  329,  329,  330,  329,  330,
      329,  331,  328,  333,  331,  331,  329,  329,   41,  334,
      329,  335,  336,  329,  329,  329,  329,  329,  329,  329,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,  337,  330,   58,  333,  333,  338,  331,  329,
      329,   58,  334,  334,  329,  335,  339,  335,  340,  336,
      336,  329,  329,  329,   58,   24,   24,   24,   24,   24,

       24,   24,   24,   24,   24,   24,   24,  337,  334,  337,
      334,  330,  330,  341,  338,  338,  331,  329,   58,  334,
      329,  329,  339,  335,  340,  340,  342,  329,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
      337,  337,  334,  330,  330,  341,  341,  338,  331,  329,
      340,  342,  342,  329,  329,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,  337,  337,  341,  331,
      340,  342,   24,   24,   24,   24,   24,   24,   24,   24,
       24,  337,  337,  331,   24,   24,   24,  329,  343,   24,
       24,  331,   24,  344,   24,  329,  343,  345,  343,  343,

      343,  331,  344,  346,  344,  344,  344,   24,  329,  345,
      345,  347,  343,  348,  346,  346,  349,  344,  350,  329,
      345,  347,  347,  347,  347,  343,  348,  351,  348,  331,
      346,  349,  349,  349,  349,  344,  350,  352,  350,  350,
      350,  329,  345,  347,  347,  343,  351,  328,  353,  328,
      331,  346,  349,  349,  344,  352,  352,  354,  350,  329,
      345,  347,  343,  328,  328,  353,  353,  338,  346,  349,
      344,  352,  354,  354,  354,  354,  350,  355,  345,  347,
      329,  353,  338,  346,  349,  329,  352,  354,  354,  350,
      355,  356,  355,  355,  355,  328,  347,  328,  349,  352,

      354,  350,  356,  356,  357,  355,  334,  334,  352,  354,
      356,  357,  357,  357,  357,  355,  354,  356,  357,  357,
      355,  356,  357,  355,  356,  357,  357,    0,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328
    } ;

static yyconst short int yy_nxt[1140] =
    {   0,
        4,    5,    6,    5,    4,    7,    8,    9,   10,   11,
       12,   13,    4,   14,    4,   15,   16,   17,   18,   18,
       19,   20,   21,   22,   23,    4,   24,   24,   24,   24,
       24,   24,   24,   25,   24,   24,   26,   24,   24,    4,
       24,   24,   24,   27,   24,   28,   24,   24,   29,   24,
       24,   24,   24,   30,   24,   31,   32,   24,   33,   24,
       24,   34,   35,   36,   36,   37,   43,   39,   44,  152,
       50,   36,   37,   40,   48,   45,   52,   37,   51,   51,
       51,   53,  108,   37,   64,   37,   60,   65,   50,   54,
       37,   55,   55,   56,   54,   90,   59,   59,   59,   43,

       68,   41,   49,   69,   57,   43,   43,   80,   45,   57,
       37,   46,   58,   80,   77,   45,   37,   87,  102,   57,
       78,   50,   37,  103,   57,   83,   88,   43,   92,   92,
       92,   89,   47,   58,   36,   36,   77,   36,   36,   36,
       36,   36,   36,   36,   36,   37,   36,   36,   36,   36,
       36,   61,   61,   61,   36,   36,   36,   36,   36,   36,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   36,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   36,   36,   36,   36,   84,

       43,   39,   39,   43,  120,  188,   43,   40,   40,   77,
       37,   87,   45,   73,  114,  116,   51,   51,   51,   37,
       88,   80,  189,   54,   37,   55,   55,   56,   37,   85,
      118,  118,   87,   87,   38,   41,   41,   38,   57,   43,
       38,  124,  126,   37,   85,   36,   50,  264,   45,   74,
       74,  328,   79,   57,   91,   37,   93,   38,   93,  127,
       37,   94,   94,   94,   54,   83,   56,   56,   56,  109,
       75,   38,  196,   38,   38,  110,   43,   83,   38,   57,
      117,  109,  325,   38,   43,  147,   38,  110,   38,   87,
       38,   75,   47,  116,   57,   47,   80,   36,  126,   37,

      265,   39,   37,  111,   81,   81,   54,   40,   59,   59,
       59,   43,   47,  112,  112,  111,   37,  121,   43,  121,
      147,   57,  122,  122,  122,   82,   47,  116,   47,   47,
       87,   43,  148,   47,   37,   41,   57,  322,   47,   88,
      116,   47,   37,   47,   89,   47,   82,   37,   92,   92,
       92,   37,  318,   95,   95,   95,  210,   94,   94,   94,
       43,  128,   95,   95,   95,   95,   95,   37,  328,  147,
      211,   84,  209,   94,   94,   94,  128,   95,   95,   95,
       95,   95,   95,  113,  113,  113,  153,  215,   43,   37,
       43,  172,  113,  113,  113,  113,  113,   45,   37,   45,

       84,  216,  210,   37,  122,  122,  122,  113,  113,  113,
      113,  113,  113,  119,  119,  119,  211,   83,  311,   87,
       43,  109,  119,  119,  119,  119,  119,  110,  151,  147,
      220,  309,  141,  120,  169,  149,  215,  119,  119,  119,
      119,  119,  119,   80,   36,  170,   37,  260,   39,   87,
      216,   37,   47,   47,   40,  111,  108,   37,  126,  108,
      144,  144,   84,  122,  122,  122,   87,  300,  142,  142,
      264,   37,  154,   37,  154,  126,  108,  155,  155,  155,
      171,   83,   41,  298,   83,  109,   43,  202,  109,  143,
      108,  110,  108,  108,  110,   45,  242,  108,   37,  256,

      167,  167,  108,   43,   36,  108,  296,  108,   39,  108,
      143,   36,   45,  257,   40,   39,  287,   43,  284,  111,
       36,   40,  111,  265,   39,   37,   45,  145,  145,  145,
       40,  155,  155,  155,  250,  198,  145,  145,  145,  145,
      145,  279,   41,   45,  199,  184,  272,  256,  303,   41,
      198,  145,  145,  145,  145,  145,  145,   80,   41,  199,
      192,  257,  304,   37,  269,  248,  150,  150,  150,  155,
      155,  155,  198,  204,  198,  150,  150,  150,  150,  150,
      261,  199,  205,  199,  252,  263,  248,  251,  213,  204,
      150,  150,  150,  150,  150,  150,   84,   83,  205,  228,

      198,  109,  168,  168,  168,  243,   83,  110,  229,  199,
      109,  168,  168,  168,  168,  168,  110,  231,  200,  206,
      200,  230,  182,  182,  303,  221,  168,  168,  168,  168,
      168,  168,  201,  207,  201,  111,  219,   83,  304,  271,
      208,  109,  204,   37,  111,   83,  200,  110,   43,  109,
      198,  205,  278,  195,  194,  110,  204,   45,  193,  199,
      201,  183,  183,  183,  212,  205,  191,  204,  214,  204,
      183,  183,  183,  183,  183,  111,  205,  190,  205,  187,
      218,  217,  198,  111,  198,  183,  183,  183,  183,  183,
      183,  223,  204,  199,  204,  238,  200,  198,  198,  198,

      198,  233,  206,  205,  239,  204,  223,  223,  223,  223,
      201,  228,  244,  206,  233,  206,  207,  186,  185,  153,
      229,  198,  181,  204,  180,  228,  226,  207,  224,  207,
      199,  204,  233,  230,  229,  179,  236,  245,  234,  249,
      233,  240,  225,  224,  224,  253,  224,  230,  178,  177,
      204,  234,  235,  176,  204,  241,  175,  225,  225,  233,
      225,  254,  246,  205,  238,  235,  238,  238,  174,  238,
      198,  173,  153,  239,  166,  239,  239,  234,  239,  223,
      198,  258,  165,  228,  250,  204,  164,  163,  238,  223,
      204,  235,  267,   45,  233,  255,  234,  274,  238,  233,

      198,  162,  259,  161,  160,  268,  159,  239,  198,  223,
      235,  228,  240,  240,  228,  240,  224,  199,  158,  157,
      267,  156,  262,  267,  153,  328,  241,  241,  282,  241,
      225,  234,  270,  268,  275,  250,  268,  251,  204,   84,
      277,  280,  204,  238,  116,  235,  238,  233,  276,  238,
       84,  205,  274,  238,  238,  274,  292,  198,  274,  281,
      288,  228,  274,  239,  250,  293,  223,  238,  204,  238,
      267,  238,  140,  116,  139,  198,  274,  233,  274,  285,
      239,  292,  292,  268,  223,  292,  138,  289,  283,  275,
      293,  293,  275,  286,  293,  290,  305,  137,  136,  275,

      135,  292,  294,  276,  134,  204,  276,  297,  133,  301,
      293,  238,  132,  276,  233,  275,  295,  283,  299,  131,
      274,  302,  238,  306,  292,  292,  307,  294,  294,  276,
      238,  239,  130,  313,  293,  292,  292,  292,  129,  274,
      292,  295,  295,   91,  313,  313,  313,  294,  292,  313,
      319,  238,  310,  292,  292,  292,  308,  293,  123,  292,
      274,  295,  313,  293,  313,  292,   84,  316,  293,  292,
      314,   37,  107,   36,  313,  320,  292,  106,  313,  105,
      317,  314,  314,  104,  315,  313,  314,  101,  100,  321,
       99,   98,   97,   96,   37,  315,  315,  323,   91,  314,

      315,   84,   83,   37,  324,   37,  326,   37,   37,   72,
       36,   71,   70,  315,   67,   66,   63,   62,   37,  327,
       37,   37,   37,   37,   37,   37,   37,   83,   42,   42,
       76,   76,   86,   86,  115,  115,   87,   87,  125,  125,
      146,  146,  197,  197,  203,  203,  198,  198,  204,  204,
      222,  222,  227,  227,  232,  232,  237,  237,  247,  247,
      238,  238,  266,  266,  273,  273,  291,  291,  292,  292,
      312,  312,   37,   37,  328,    3,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328
    } ;

static yyconst short int yy_chk[1140] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    7,   10,   13,    8,    7,    8,  342,
       13,   10,   15,    7,   10,    8,   16,   19,   15,   15,
       15,   16,  337,   37,   27,   17,   19,   27,   37,   17,
       18,   17,   17,   17,   18,  336,   18,   18,   18,   42,

       30,    7,   10,   30,   17,   44,   45,   47,   42,   18,
       47,    8,   17,   48,   44,   45,   48,   52,   68,   17,
       45,   48,   54,   68,   18,  334,   52,   76,   54,   54,
       54,   52,  332,   17,   24,   24,   76,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   38,   40,   84,

       77,   38,   40,   46,   84,  178,   78,   38,   40,   77,
       51,   86,   46,   40,   77,   78,   51,   51,   51,   55,
       86,   81,  178,   55,   81,   55,   55,   55,  188,   51,
       81,   81,   88,   89,  330,   38,   40,   41,   55,   79,
       41,   88,   89,   41,   51,  329,   88,  248,   79,   41,
       41,  325,   46,   55,   91,   57,   57,   41,   57,   91,
       56,   57,   57,   57,   56,   73,   56,   56,   56,   73,
       41,   41,  188,   41,   41,   73,  114,  108,   41,   56,
       79,  108,  322,   41,  115,  114,   41,  108,   41,  125,
       41,   41,   49,  115,   56,   49,  150,   74,  125,  150,

      248,   74,   59,   73,   49,   49,   59,   74,   59,   59,
       59,  146,   49,   74,   74,  108,   85,   85,  116,   85,
      146,   59,   85,   85,   85,   49,   49,  116,   49,   49,
      124,  148,  116,   49,  196,   74,   59,  318,   49,  124,
      148,   49,   92,   49,  124,   49,   49,   58,   92,   92,
       92,   93,  311,   58,   58,   58,  198,   93,   93,   93,
      169,   92,   58,   58,   58,   58,   58,   94,  309,  169,
      198,  308,  196,   94,   94,   94,   92,   58,   58,   58,
       58,   58,   58,   75,   75,   75,  153,  204,  117,  209,
      149,  153,   75,   75,   75,   75,   75,  117,  121,  149,

      307,  204,  211,  242,  121,  121,  121,   75,   75,   75,
       75,   75,   75,   82,   82,   82,  211,  110,  303,  126,
      147,  110,   82,   82,   82,   82,   82,  110,  126,  147,
      209,  300,  110,  126,  147,  117,  216,   82,   82,   82,
       82,   82,   82,  118,  112,  149,  118,  242,  112,  171,
      216,  220,  118,  118,  112,  110,  111,  122,  171,  111,
      112,  112,  111,  122,  122,  122,  151,  287,  111,  111,
      265,  128,  128,  286,  128,  151,  111,  128,  128,  128,
      151,  141,  112,  284,  142,  141,  192,  192,  142,  111,
      111,  141,  111,  111,  142,  192,  220,  111,  281,  238,

      142,  142,  111,  170,  144,  111,  279,  111,  144,  111,
      111,  113,  170,  238,  144,  113,  272,  184,  269,  141,
      145,  113,  142,  265,  145,  154,  184,  113,  113,  113,
      145,  154,  154,  154,  230,  246,  113,  113,  113,  113,
      113,  261,  144,  230,  246,  170,  256,  257,  292,  113,
      200,  113,  113,  113,  113,  113,  113,  119,  145,  200,
      184,  257,  292,  155,  252,  247,  119,  119,  119,  155,
      155,  155,  189,  194,  197,  119,  119,  119,  119,  119,
      243,  189,  194,  197,  231,  246,  228,  230,  200,  255,
      119,  119,  119,  119,  119,  119,  143,  182,  255,  214,

      201,  182,  143,  143,  143,  221,  167,  182,  214,  201,
      167,  143,  143,  143,  143,  143,  167,  215,  189,  194,
      197,  214,  167,  167,  304,  210,  143,  143,  143,  143,
      143,  143,  189,  194,  197,  182,  208,  183,  304,  255,
      195,  183,  206,  260,  167,  168,  201,  183,  202,  168,
      199,  206,  260,  187,  186,  168,  203,  202,  185,  199,
      201,  168,  168,  168,  199,  203,  181,  205,  202,  207,
      168,  168,  168,  168,  168,  183,  205,  180,  207,  177,
      206,  205,  212,  168,  213,  168,  168,  168,  168,  168,
      168,  212,  217,  213,  218,  219,  199,  222,  223,  224,

      225,  217,  203,  218,  219,  232,  222,  223,  224,  225,
      199,  227,  223,  205,  232,  207,  203,  176,  174,  172,
      227,  226,  166,  234,  165,  229,  213,  205,  212,  207,
      226,  233,  234,  227,  229,  164,  218,  224,  217,  229,
      233,  219,  212,  222,  223,  233,  225,  229,  163,  162,
      235,  232,  217,  161,  236,  219,  160,  222,  223,  235,
      225,  234,  226,  236,  240,  232,  237,  239,  157,  241,
      244,  156,  152,  240,  140,  237,  239,  233,  241,  244,
      245,  239,  139,  249,  251,  253,  138,  137,  258,  245,
      254,  233,  249,  251,  253,  236,  235,  258,  259,  254,

      262,  136,  240,  135,  134,  249,  132,  259,  263,  262,
      235,  266,  237,  239,  267,  241,  244,  263,  131,  130,
      266,  129,  245,  267,  127,  123,  237,  239,  267,  241,
      244,  253,  254,  266,  258,  268,  267,  251,  270,  120,
      259,  262,  271,  273,  268,  253,  274,  270,  258,  275,
      109,  271,  273,  276,  277,  274,  278,  280,  275,  263,
      274,  282,  276,  277,  283,  278,  280,  289,  285,  288,
      282,  290,  107,  283,  106,  297,  289,  285,  288,  270,
      290,  291,  293,  282,  297,  294,  105,  275,  268,  273,
      291,  293,  274,  271,  294,  277,  293,  104,  103,  276,

      102,  295,  278,  273,  101,  299,  274,  280,  100,  289,
      295,  301,   99,  276,  299,  288,  278,  283,  285,   98,
      301,  290,  302,  294,  305,  306,  297,  291,  293,  288,
      310,  302,   97,  305,  306,  312,  313,  314,   96,  310,
      315,  291,  293,   90,  312,  313,  314,  295,  316,  315,
      313,  317,  301,  319,  321,  320,  299,  316,   87,  324,
      317,  295,  319,  321,  320,  323,   83,  306,  324,  326,
      305,   80,   72,  302,  323,  314,  327,   71,  326,   70,
      310,  312,  313,   69,  305,  327,  315,   67,   66,  316,
       65,   64,   63,   62,   60,  312,  313,  320,   53,  319,

      315,   50,  317,   39,  321,   36,  323,   35,   34,   33,
      324,   32,   31,  319,   29,   28,   26,   25,   23,  326,
       22,   21,   20,   14,   12,   11,    9,  327,  331,  331,
      333,  333,  335,  335,  338,  338,  339,  339,  340,  340,
      341,  341,  343,  343,  344,  344,  345,  345,  346,  346,
      347,  347,  348,  348,  349,  349,  350,  350,  351,  351,
      352,  352,  353,  353,  354,  354,  355,  355,  356,  356,
      357,  357,    5,    4,    3,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.ll"
#define INITIAL 0
#line 2 "scanner.ll"

#define YY_NO_UNPUT
#include <stdlib.h>
#include <ctype.h>

class QString;

#ifndef KDE_USE_FINAL
#include "yacc.cc.h"
#endif

extern int idl_line_no;
int comment_mode;

#include <qstring.h>

static long ascii_to_longlong( long base, const char *s )
{
  long ll = 0;
  while( *s != '\0' ) {
    char c = *s++;
    if( c >= 'a' )
      c -= 'a' - 'A';
    c -= '0';
    if( c > 9 )
      c -= 'A' - '0' - 10;
    ll = ll * base + c;
  }
  return ll;
}

static double ascii_to_longdouble (const char *s)
{
  double d;
#ifdef HAVE_SCANF_LF
  sscanf (s, "%Lf", &d);
#else
  /*
   * this is only an approximation and will probably break fixed<>
   * parameter calculation on systems where
   * sizeof(double) < sizeof(long double). but fortunately all
   * systems where scanf("%Lf") is known to be broken (Linux/Alpha
   * and HPUX) have sizeof(double) == sizeof(long double).
   */
  d = strtod (s, NULL);
#endif
  return d;
}

static char translate_char( const char *s )
{
  char c = *s++;

  if( c != '\\' )
    return c;
  c = *s++;
  switch( c ) {
  case 'n':
    return '\n';
  case 't':
    return '\t';
  case 'v':
    return '\v';
  case 'b':
    return '\b';
  case 'r':
    return '\r';
  case 'f':
    return '\f';
  case 'a':
    return '\a';
  case '\\':
    return '\\';
  case '?':
    return '\?';
  case '\'':
    return '\'';
  case '"':
    return '"';
  case 'x':
  case 'X':
    return (char) ascii_to_longlong( 16, s );
  default:
    // Gotta be an octal
    return (char) ascii_to_longlong( 8, s );
  }
}


/*--------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------*/
#line 898 "scanner.cc"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 126 "scanner.ll"


#line 1052 "scanner.cc"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 329 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_current_state != 328 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 128 "scanner.ll"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 129 "scanner.ll"
{ idl_line_no++; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 131 "scanner.ll"
{ comment_mode = 1; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 132 "scanner.ll"
{ comment_mode = 0; /* this also eats one-line comments */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 133 "scanner.ll"
{ if (!comment_mode) { REJECT; } }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 135 "scanner.ll"
;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 136 "scanner.ll"
{
                          exit( 1 );
                        }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 139 "scanner.ll"
{
			  QString s( yytext );
			  yylval._str = new QString( s.mid( 10, s.stripWhiteSpace().length() - 11 ) );
                          idl_line_no++;
                          return T_INCLUDE;
                        }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 145 "scanner.ll"
{
                          idl_line_no++;
                        }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 148 "scanner.ll"
return T_LEFT_CURLY_BRACKET;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 149 "scanner.ll"
return T_RIGHT_CURLY_BRACKET;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 150 "scanner.ll"
return T_LEFT_PARANTHESIS;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 151 "scanner.ll"
return T_RIGHT_PARANTHESIS;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 152 "scanner.ll"
return T_COLON;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 153 "scanner.ll"
return T_COMMA;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 154 "scanner.ll"
return T_SEMICOLON;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 155 "scanner.ll"
return T_AMPERSAND;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 156 "scanner.ll"
return T_LESS;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 157 "scanner.ll"
return T_GREATER;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 158 "scanner.ll"
return T_SCOPE;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 159 "scanner.ll"
return T_EQUAL;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 161 "scanner.ll"
return T_CONST;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 162 "scanner.ll"
return T_ENUM;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 163 "scanner.ll"
return T_CLASS;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 164 "scanner.ll"
return T_STRUCT;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 165 "scanner.ll"
return T_VIRTUAL;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 166 "scanner.ll"
return T_PUBLIC;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 167 "scanner.ll"
return T_DCOP_AREA;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 168 "scanner.ll"
return T_TYPEDEF;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 169 "scanner.ll"
return T_DCOP;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 170 "scanner.ll"
;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 171 "scanner.ll"
return T_NULL;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 173 "scanner.ll"
return T_DCOP_AREA;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 174 "scanner.ll"
return T_RIGHT_CURLY_BRACKET;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 175 "scanner.ll"
return T_DCOP_AREA;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 176 "scanner.ll"
return T_RIGHT_CURLY_BRACKET;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 177 "scanner.ll"
return T_RIGHT_CURLY_BRACKET;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 178 "scanner.ll"
return T_RIGHT_CURLY_BRACKET;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 180 "scanner.ll"
{
			  yylval._str = new QString( yytext );
			  return T_IDENTIFIER;
			}
	YY_BREAK
case 40:
#line 185 "scanner.ll"
case 41:
#line 186 "scanner.ll"
case 42:
#line 187 "scanner.ll"
case 43:
#line 188 "scanner.ll"
case 44:
YY_RULE_SETUP
#line 188 "scanner.ll"
{
			  yylval._float = ascii_to_longdouble( yytext );
			  return T_DOUBLE_LITERAL;
			}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 192 "scanner.ll"
{
			  yylval._int = ascii_to_longlong( 10, yytext );
			  return T_INTEGER_LITERAL;
			}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 196 "scanner.ll"
{
			  yylval._int = ascii_to_longlong( 8, yytext );
			  return T_INTEGER_LITERAL;
			}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 200 "scanner.ll"
{
			  yylval._int = ascii_to_longlong( 16, yytext + 2 );
			  return T_INTEGER_LITERAL;
			}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 204 "scanner.ll"
{
                          QCString s( yytext );
	                  s = s.mid( 1, s.length() - 2 );
			  yylval._char = translate_char( s );
			  return T_CHARACTER_LITERAL;
			}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 210 "scanner.ll"
{
                          QString s( yytext );
                          yylval._str = new QString( s.mid( 1, s.length() - 2 ) );
			  return T_STRING_LITERAL;
			}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 215 "scanner.ll"
{
                          return T_UNKNOWN;
                        }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 219 "scanner.ll"
ECHO;
	YY_BREAK
#line 1414 "scanner.cc"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 329 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 329 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 328);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 219 "scanner.ll"


void dcopidlInitFlex( const char *_code )
{
   comment_mode = 0;
   yy_switch_to_buffer( yy_scan_string( _code ) );
}
