#! /usr/bin/env python

Import('env')
myenv=env.Copy()

## there is support for lex and yacc in scons
obj=myenv.qt4obj('program', myenv)
obj.source    = 'main.cpp yacc.yy scanner.ll'
obj.target    = 'dcopidlold'
obj.libs      = env['LIB_QT']
obj.execute()


#blec=myenv.Builder(action='cd $SOURCE.dir && flex -B -8 -o$TARGET $SOURCE',suffix='.cc',src_suffix='.ll')
#byac=myenv.Builder(action='cd $SOURCE.dir && bison -t -d -v -o $TARGET $SOURCE',suffix='.cc',src_suffix='.yy')

"""
INCLUDES = $(all_includes)
AM_LDFLAGS   = $(all_libraries)
AM_CPPFLAGS = -DYYDEBUG

####### Files

bin_PROGRAMS = dcopidlold

dcopidlold_SOURCES = main.cpp yacc.cc scanner.cc
noinst_HEADERS = yacc.cc.h

dcopidlold_LDADD = $(LIB_QT)
dcopidlold_LDFLAGS = $(KDE_RPATH)

####### Build rules

parser:
	cd $(srcdir) && flex -B -8 -oscanner.cc scanner.ll  ;\
	bison -t -d -v -o yacc.cc yacc.yy && mv yacc.hh yacc.cc.h

check-local: 
	$(srcdir)/run_test.sh $(srcdir)

EXTRA_DIST = dcopidl_test.h scanner.ll yacc.yy

MAINTAINERCLEANFILES = yacc.cc.output
"""
