#! /usr/bin/env python

Import('env')

obj = env.qt4obj('shlib', env)
obj.vnum     = '1.0.0'
obj.target   = 'libkwalletbackend'
obj.source   = """
blockcipher.cc
blowfish.cc
cbc.cc
sha1.cc
kwalletentry.cc
kwalletbackend.cc
"""
obj.uselib   = 'QT QTCORE QTGUI QT3SUPPORT KDE4'
obj.libs     = '../../kdecore/libkdecore.la'
obj.includes = '../client'
obj.execute()


