#! /usr/bin/env python

Import('env')

# TODO: are kdefx kdeui really required ? 
# DF: can't uselib=KIO bring in all the dependencies automatically, anyway?

if env['WINDOWS']:
	obj = env.kdeobj('program',env)
	obj.ccflags = '-Dkdemain=main'
else:
	obj = env.kdeinitobj(env)
obj.target   = 'kbuildsycoca'
obj.source   = """
kbuildsycoca.cpp kbuildservicetypefactory.cpp kbuildservicefactory.cpp 
kbuildservicegroupfactory.cpp kbuildprotocolinfofactory.cpp 
kctimefactory.cpp vfolder_menu.cpp
"""
obj.uselib   = 'QTCORE QTGUI QT3SUPPORT QT QTXML KDE4 KIO'
obj.libpaths = '../kdecore ../kdefx ../kdeui ../dcop'
obj.libs     = 'kdecore kdefx kdeui DCOP'
if env['WINDOWS']:
	obj.libpaths += ' ../win'
	obj.libs     += ' kdewin32'
obj.execute()

obj = env.kdeinitobj(env)
obj.target   = 'kded'
obj.source   = 'kded.cpp'
obj.uselib   = 'QTCORE QTGUI QT3SUPPORT QT KDE4 KIO'
if env['WINDOWS']:
	obj.libpaths = '. ../win'
	obj.libs     = 'kded kdewin32'
obj.execute()

obj=env.kdeobj('program', env)
obj.target='kdontchangehostname'
obj.source='khostname.cpp'
obj.uselib   = 'QTCORE QTGUI QT QT3SUPPORT KDE4'
obj.libpaths = '../kdecore ../kdefx ../kdeui ../dcop'
obj.libs     = 'kdecore kdefx kdeui DCOP'
if env['WINDOWS']:
	obj.libpaths += ' ../win'
	obj.libs     += ' kdewin32'
obj.execute()

obj=env.kdeobj('program', env)
obj.target='kdemenu'
obj.source='kde-menu.cpp'
obj.uselib   = 'QTCORE QT QTGUI QT3SUPPORT KDE4 KIO'
obj.libpaths = '../kdecore ../kdefx ../kdeui ../dcop'
obj.libs     = 'kdecore kdefx kdeui DCOP'
if env['WINDOWS']:
	obj.libpaths += ' ../win'
	obj.libs     += ' kdewin32'
obj.execute()

env.bksys_insttype( 'KDEDATA', 'kconf_update', 'kded.upd' )
env.bksys_insttype( 'KDESERVTYPES', '', 'kdedmodule.desktop' )
env.bksys_insttype( 'KDEMENU', '', 'applications.menu' )

env.bksys_insttype( 'KDEBIN', '', 'kdontchangethehostname kde-menu' )

