#! /usr/bin/env python

Import('env')

obj = env.kdeobj('shlib', env)
obj.iskdelib = 1
obj.vnum     = '2.1.0'
obj.target   = 'libkwalletclient'
obj.source   = """
kwallet.skel
kwallet.cc
"""

obj.uselib   = 'QT QTCORE QTGUI QT3SUPPORT KDE4'
obj.libs     = '../../kdecore/libkdecore.la'
obj.execute()


