/* ANSI-C code produced by gperf version 2.7.1 (19981006 egcs) */
/* Command-line: gperf -a -L ANSI-C -E -C -c -o -t -k * -NfindAttr -Hhash_attr -Wwordlist_attr -D -s 2 htmlattrs.gperf  */
/* This file is automatically generated from
#htmlattrs.in by makeattrs, do not edit */
/* Copyright 1999 Lars Knoll */
#include "htmlattrs.h"
struct attrs {
    const char *name;
    int id;
};
/* maximum key range = 739, duplicates = 0 */

#ifdef __GNUC__
__inline
#endif
static unsigned int
hash_attr (register const char *str, register unsigned int len)
{
  static const unsigned short asso_values[] =
    {
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753,   0, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753,   5,  30,   0,
       10,   0, 130, 145,  20, 135,   0,  90,   0,  65,
        0,   0,  95,   0,  40,  30,  30,   0, 165,  70,
        0,  80,  20, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753, 753, 753, 753, 753,
      753, 753, 753, 753, 753, 753
    };
  register int hval = len;

  switch (hval)
    {
      default:
      case 14:
        hval += asso_values[(unsigned char)str[13]];
      case 13:
        hval += asso_values[(unsigned char)str[12]];
      case 12:
        hval += asso_values[(unsigned char)str[11]];
      case 11:
        hval += asso_values[(unsigned char)str[10]];
      case 10:
        hval += asso_values[(unsigned char)str[9]];
      case 9:
        hval += asso_values[(unsigned char)str[8]];
      case 8:
        hval += asso_values[(unsigned char)str[7]];
      case 7:
        hval += asso_values[(unsigned char)str[6]];
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      case 5:
        hval += asso_values[(unsigned char)str[4]];
      case 4:
        hval += asso_values[(unsigned char)str[3]];
      case 3:
        hval += asso_values[(unsigned char)str[2]];
      case 2:
        hval += asso_values[(unsigned char)str[1]];
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

#ifdef __GNUC__
__inline
#endif
const struct attrs *
findAttr (register const char *str, register unsigned int len)
{
  enum
    {
      TOTAL_KEYWORDS = 129,
      MIN_WORD_LENGTH = 2,
      MAX_WORD_LENGTH = 14,
      MIN_HASH_VALUE = 14,
      MAX_HASH_VALUE = 752
    };

  static const struct attrs wordlist_attr[] =
    {
      {"code", ATTR_CODE},
      {"onload", ATTR_ONLOAD},
      {"onunload", ATTR_ONUNLOAD},
      {"cols", ATTR_COLS},
      {"console", ATTR_CONSOLE},
      {"alt", ATTR_ALT},
      {"label", ATTR_LABEL},
      {"rel", ATTR_REL},
      {"color", ATTR_COLOR},
      {"clear", ATTR_CLEAR},
      {"data", ATTR_DATA},
      {"declare", ATTR_DECLARE},
      {"text", ATTR_TEXT},
      {"object", ATTR_OBJECT},
      {"content", ATTR_CONTENT},
      {"onselect", ATTR_ONSELECT},
      {"char", ATTR_CHAR},
      {"class", ATTR_CLASS},
      {"noshade", ATTR_NOSHADE},
      {"src", ATTR_SRC},
      {"name", ATTR_NAME},
      {"rules", ATTR_RULES},
      {"onblur", ATTR_ONBLUR},
      {"selected", ATTR_SELECTED},
      {"codebase", ATTR_CODEBASE},
      {"coords", ATTR_COORDS},
      {"onreset", ATTR_ONRESET},
      {"controls", ATTR_CONTROLS},
      {"abbr", ATTR_ABBR},
      {"headers", ATTR_HEADERS},
      {"html", ATTR_HTML},
      {"scheme", ATTR_SCHEME},
      {"border", ATTR_BORDER},
      {"checked", ATTR_CHECKED},
      {"scope", ATTR_SCOPE},
      {"method", ATTR_METHOD},
      {"charset", ATTR_CHARSET},
      {"span", ATTR_SPAN},
      {"onmouseout", ATTR_ONMOUSEOUT},
      {"accept", ATTR_ACCEPT},
      {"colspan", ATTR_COLSPAN},
      {"face", ATTR_FACE},
      {"start", ATTR_START},
      {"readonly", ATTR_READONLY},
      {"rows", ATTR_ROWS},
      {"style", ATTR_STYLE},
      {"id", ATTR_ID},
      {"lang", ATTR_LANG},
      {"shape", ATTR_SHAPE},
      {"hspace", ATTR_HSPACE},
      {"onfocus", ATTR_ONFOCUS},
      {"cite", ATTR_CITE},
      {"bordercolor", ATTR_BORDERCOLOR},
      {"for", ATTR_FOR},
      {"axis", ATTR_AXIS},
      {"value", ATTR_VALUE},
      {"action", ATTR_ACTION},
      {"onchange", ATTR_ONCHANGE},
      {"hidden", ATTR_HIDDEN},
      {"defer", ATTR_DEFER},
      {"onmousedown", ATTR_ONMOUSEDOWN},
      {"dir", ATTR_DIR},
      {"size", ATTR_SIZE},
      {"standby", ATTR_STANDBY},
      {"longdesc", ATTR_LONGDESC},
      {"href", ATTR_HREF},
      {"nohref", ATTR_NOHREF},
      {"onmouseup", ATTR_ONMOUSEUP},
      {"title", ATTR_TITLE},
      {"usemap", ATTR_USEMAP},
      {"compact", ATTR_COMPACT},
      {"rev", ATTR_REV},
      {"type", ATTR_TYPE},
      {"enctype", ATTR_ENCTYPE},
      {"wrap", ATTR_WRAP},
      {"nowrap", ATTR_NOWRAP},
      {"classid", ATTR_CLASSID},
      {"tabindex", ATTR_TABINDEX},
      {"media", ATTR_MEDIA},
      {"bgcolor", ATTR_BGCOLOR},
      {"codetype", ATTR_CODETYPE},
      {"disabled", ATTR_DISABLED},
      {"link", ATTR_LINK},
      {"onclick", ATTR_ONCLICK},
      {"noresize", ATTR_NORESIZE},
      {"alink", ATTR_ALINK},
      {"plain", ATTR_PLAIN},
      {"accesskey", ATTR_ACCESSKEY},
      {"frame", ATTR_FRAME},
      {"rowspan", ATTR_ROWSPAN},
      {"target", ATTR_TARGET},
      {"onkeydown", ATTR_ONKEYDOWN},
      {"accept-charset", ATTR_ACCEPT_CHARSET},
      {"width", ATTR_WIDTH},
      {"onkeyup", ATTR_ONKEYUP},
      {"maxlength", ATTR_MAXLENGTH},
      {"ondblclick", ATTR_ONDBLCLICK},
      {"oversrc", ATTR_OVERSRC},
      {"datetime", ATTR_DATETIME},
      {"align", ATTR_ALIGN},
      {"summary", ATTR_SUMMARY},
      {"onsubmit", ATTR_ONSUBMIT},
      {"vspace", ATTR_VSPACE},
      {"language", ATTR_LANGUAGE},
      {"onmouseover", ATTR_ONMOUSEOVER},
      {"background", ATTR_BACKGROUND},
      {"prompt", ATTR_PROMPT},
      {"charoff", ATTR_CHAROFF},
      {"multiple", ATTR_MULTIPLE},
      {"ismap", ATTR_ISMAP},
      {"onmousemove", ATTR_ONMOUSEMOVE},
      {"hreflang", ATTR_HREFLANG},
      {"height", ATTR_HEIGHT},
      {"scrolling", ATTR_SCROLLING},
      {"frameborder", ATTR_FRAMEBORDER},
      {"archive", ATTR_ARCHIVE},
      {"onkeypress", ATTR_ONKEYPRESS},
      {"version", ATTR_VERSION},
      {"valuetype", ATTR_VALUETYPE},
      {"vlink", ATTR_VLINK},
      {"profile", ATTR_PROFILE},
      {"cellpadding", ATTR_CELLPADDING},
      {"cellspacing", ATTR_CELLSPACING},
      {"pluginurl", ATTR_PLUGINURL},
      {"valign", ATTR_VALIGN},
      {"http-equiv", ATTR_HTTP_EQUIV},
      {"pluginpage", ATTR_PLUGINPAGE},
      {"marginwidth", ATTR_MARGINWIDTH},
      {"marginheight", ATTR_MARGINHEIGHT}
    };

  static const short lookup[] =
    {
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,   0,  -1,  -1,  -1,  -1,  -1,
       -1,   1,  -1,   2,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,   3,  -1,  -1,   4,   5,  -1,
        6,  -1,  -1,   7,  -1,   8,  -1,  -1,  -1,  -1,
        9,  -1,  -1,  -1,  10,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  11,  -1,  12,  -1,  13,  14,  15,  16,
       17,  -1,  18,  19,  20,  21,  22,  -1,  23,  -1,
       -1,  -1,  -1,  24,  -1,  -1,  25,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  26,  27,  28,
       -1,  -1,  29,  -1,  -1,  -1,  -1,  -1,  -1,  30,
       -1,  31,  -1,  -1,  -1,  -1,  32,  33,  -1,  -1,
       34,  35,  36,  -1,  37,  38,  39,  40,  -1,  41,
       42,  -1,  -1,  43,  44,  45,  -1,  46,  -1,  -1,
       -1,  -1,  -1,  -1,  47,  48,  49,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  50,  -1,  51,
       -1,  52,  -1,  53,  54,  55,  56,  -1,  57,  -1,
       -1,  58,  -1,  -1,  -1,  59,  60,  -1,  61,  62,
       -1,  -1,  63,  64,  65,  -1,  66,  -1,  -1,  67,
       68,  69,  70,  -1,  -1,  -1,  -1,  -1,  71,  72,
       -1,  -1,  73,  -1,  74,  -1,  75,  76,  77,  -1,
       78,  -1,  79,  80,  -1,  -1,  -1,  -1,  81,  82,
       -1,  -1,  83,  84,  -1,  85,  -1,  -1,  -1,  -1,
       86,  -1,  -1,  -1,  87,  88,  -1,  89,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  90,  -1,  -1,  91,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  92,
       93,  -1,  94,  -1,  95,  96,  -1,  -1,  -1,  -1,
       -1,  -1,  97,  98,  -1,  -1,  -1,  -1,  -1,  -1,
       99,  -1, 100,  -1,  -1,  -1,  -1,  -1, 101,  -1,
       -1, 102,  -1,  -1,  -1,  -1,  -1,  -1, 103,  -1,
       -1, 104,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      105, 106, 107, 108,  -1, 109, 110,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 111,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 112,  -1,  -1, 113,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 114, 115,  -1,  -1, 116,  -1, 117,  -1,  -1,
       -1,  -1,  -1,  -1, 118,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 119,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 120,  -1,  -1,
       -1, 121,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 122,  -1,  -1, 123,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 124,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1, 125,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
      126,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 127,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 128
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = hash_attr (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        {
          register int index = lookup[key];

          if (index >= 0)
            {
              register const char *s = wordlist_attr[index].name;

              if (*str == *s && !strncmp (str + 1, s + 1, len - 1))
                return &wordlist_attr[index];
            }
          else if (index < -TOTAL_KEYWORDS)
            {
              register int offset = - 1 - TOTAL_KEYWORDS - index;
              register const struct attrs *wordptr = &wordlist_attr[TOTAL_KEYWORDS + lookup[offset]];
              register const struct attrs *wordendptr = wordptr + -lookup[offset + 1];

              while (wordptr < wordendptr)
                {
                  register const char *s = wordptr->name;

                  if (*str == *s && !strncmp (str + 1, s + 1, len - 1))
                    return wordptr;
                  wordptr++;
                }
            }
        }
    }
  return 0;
}


static const DOMString attrList[] = {
    "ABBR",
    "ACCEPT-CHARSET",
    "ACCEPT",
    "ACCESSKEY",
    "ACTION",
    "ALIGN",
    "ALINK",
    "ALT",
    "ARCHIVE",
    "AXIS",
    "BACKGROUND",
    "BGCOLOR",
    "BORDER",
    "BORDERCOLOR",
    "CELLPADDING",
    "CELLSPACING",
    "CHAR",
    "CHAROFF",
    "CHARSET",
    "CHECKED",
    "CITE",
    "CLASS",
    "CLASSID",
    "CLEAR",
    "CODE",
    "CODEBASE",
    "CODETYPE",
    "COLOR",
    "COLS",
    "COLSPAN",
    "COMPACT",
    "CONSOLE",
    "CONTENT",
    "CONTROLS",
    "COORDS",
    "DATA",
    "DATETIME",
    "DECLARE",
    "DEFER",
    "DIR",
    "DISABLED",
    "ENCTYPE",
    "FACE",
    "FOR",
    "FRAME",
    "FRAMEBORDER",
    "HEADERS",
    "HEIGHT",
    "HIDDEN",
    "HREF",
    "HREFLANG",
    "HSPACE",
    "HTML",
    "HTTP-EQUIV",
    "ID",
    "ISMAP",
    "LABEL",
    "LANG",
    "LANGUAGE",
    "LINK",
    "LONGDESC",
    "MARGINHEIGHT",
    "MARGINWIDTH",
    "MAXLENGTH",
    "MEDIA",
    "METHOD",
    "MULTIPLE",
    "NAME",
    "NOHREF",
    "NORESIZE",
    "NOSHADE",
    "NOWRAP",
    "OBJECT",
    "ONBLUR",
    "ONCHANGE",
    "ONCLICK",
    "ONDBLCLICK",
    "ONFOCUS",
    "ONKEYDOWN",
    "ONKEYPRESS",
    "ONKEYUP",
    "ONLOAD",
    "ONMOUSEDOWN",
    "ONMOUSEMOVE",
    "ONMOUSEOUT",
    "ONMOUSEOVER",
    "ONMOUSEUP",
    "ONRESET",
    "ONSELECT",
    "ONSUBMIT",
    "ONUNLOAD",
    "OVERSRC",
    "PLAIN",
    "PLUGINPAGE",
    "PLUGINURL",
    "PROFILE",
    "PROMPT",
    "READONLY",
    "REL",
    "REV",
    "ROWS",
    "ROWSPAN",
    "RULES",
    "SCHEME",
    "SCOPE",
    "SCROLLING",
    "SELECTED",
    "SHAPE",
    "SIZE",
    "SPAN",
    "SRC",
    "STANDBY",
    "START",
    "STYLE",
    "SUMMARY",
    "TABINDEX",
    "TARGET",
    "TEXT",
    "TITLE",
    "TYPE",
    "USEMAP",
    "VALIGN",
    "VALUE",
    "VALUETYPE",
    "VERSION",
    "VLINK",
    "VSPACE",
    "WIDTH",
    "WRAP",
    0
};
const DOMString &getAttrName(unsigned short id)
{
    return attrList[id-1];
};
