/* ANSI-C code produced by gperf version 2.7.2 */
/* Command-line: gperf -c -a -L ANSI-C -D -E -C -o -t -k '*' -NfindAttr -Hhash_attr -Wwordlist_attr -s 2 htmlattrs.gperf  */
/* This file is automatically generated from
#htmlattrs.in by makeattrs, do not edit */
/* Copyright 1999 Lars Knoll */
#include "htmlattrs.h"
struct attrs {
    const char *name;
    int id;
};
/* maximum key range = 545, duplicates = 1 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash_attr (register const char *str, register unsigned int len)
{
  static const unsigned short asso_values[] =
    {
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548,   0, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548,  45,  95,  10,
       50,   0, 155,  40, 120,  45,   0,  70,   0,  55,
        0,   0,   0,   0,  25,   5,   0, 155, 125,  80,
        0, 105,  15, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548, 548, 548, 548, 548,
      548, 548, 548, 548, 548, 548
    };
  register int hval = len;

  switch (hval)
    {
      default:
      case 15:
        hval += asso_values[(unsigned char)str[14]];
      case 14:
        hval += asso_values[(unsigned char)str[13]];
      case 13:
        hval += asso_values[(unsigned char)str[12]];
      case 12:
        hval += asso_values[(unsigned char)str[11]];
      case 11:
        hval += asso_values[(unsigned char)str[10]];
      case 10:
        hval += asso_values[(unsigned char)str[9]];
      case 9:
        hval += asso_values[(unsigned char)str[8]];
      case 8:
        hval += asso_values[(unsigned char)str[7]];
      case 7:
        hval += asso_values[(unsigned char)str[6]];
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      case 5:
        hval += asso_values[(unsigned char)str[4]];
      case 4:
        hval += asso_values[(unsigned char)str[3]];
      case 3:
        hval += asso_values[(unsigned char)str[2]];
      case 2:
        hval += asso_values[(unsigned char)str[1]];
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

#ifdef __GNUC__
__inline
#endif
const struct attrs *
findAttr (register const char *str, register unsigned int len)
{
  enum
    {
      TOTAL_KEYWORDS = 145,
      MIN_WORD_LENGTH = 2,
      MAX_WORD_LENGTH = 15,
      MIN_HASH_VALUE = 3,
      MAX_HASH_VALUE = 547
    };

  static const struct attrs wordlist_attr[] =
    {
      {"top", ATTR_TOP},
      {"text", ATTR_TEXT},
      {"content", ATTR_CONTENT},
      {"cols", ATTR_COLS},
      {"scope", ATTR_SCOPE},
      {"onselect", ATTR_ONSELECT},
      {"rel", ATTR_REL},
      {"onreset", ATTR_ONRESET},
      {"color", ATTR_COLOR},
      {"src", ATTR_SRC},
      {"alt", ATTR_ALT},
      {"title", ATTR_TITLE},
      {"span", ATTR_SPAN},
      {"cite", ATTR_CITE},
      {"code", ATTR_CODE},
      {"colspan", ATTR_COLSPAN},
      {"size", ATTR_SIZE},
      {"class", ATTR_CLASS},
      {"accept", ATTR_ACCEPT},
      {"selected", ATTR_SELECTED},
      {"start", ATTR_START},
      {"onerror", ATTR_ONERROR},
      {"clear", ATTR_CLEAR},
      {"prompt", ATTR_PROMPT},
      {"lang", ATTR_LANG},
      {"pagex", ATTR_PAGEX},
      {"plain", ATTR_PLAIN},
      {"coords", ATTR_COORDS},
      {"id", ATTR_ID},
      {"noresize", ATTR_NORESIZE},
      {"onresize", ATTR_ONRESIZE},
      {"axis", ATTR_AXIS},
      {"onload", ATTR_ONLOAD},
      {"name", ATTR_NAME},
      {"action", ATTR_ACTION},
      {"type", ATTR_TYPE},
      {"object", ATTR_OBJECT},
      {"longdesc", ATTR_LONGDESC},
      {"rows", ATTR_ROWS},
      {"style", ATTR_STYLE},
      {"target", ATTR_TARGET},
      {"z-index", ATTR_Z_INDEX},
      {"link", ATTR_LINK},
      {"enctype", ATTR_ENCTYPE},
      {"dir", ATTR_DIR},
      {"compact", ATTR_COMPACT},
      {"scrolling", ATTR_SCROLLING},
      {"align", ATTR_ALIGN},
      {"declare", ATTR_DECLARE},
      {"onclick", ATTR_ONCLICK},
      {"data", ATTR_DATA},
      {"label", ATTR_LABEL},
      {"rev", ATTR_REV},
      {"wrap", ATTR_WRAP},
      {"ismap", ATTR_ISMAP},
      {"nowrap", ATTR_NOWRAP},
      {"left", ATTR_LEFT},
      {"rowspan", ATTR_ROWSPAN},
      {"alink", ATTR_ALINK},
      {"cellspacing", ATTR_CELLSPACING},
      {"classid", ATTR_CLASSID},
      {"onabort", ATTR_ONABORT},
      {"codetype", ATTR_CODETYPE},
      {"shape", ATTR_SHAPE},
      {"bgcolor", ATTR_BGCOLOR},
      {"html", ATTR_HTML},
      {"nosave", ATTR_NOSAVE},
      {"for", ATTR_FOR},
      {"hspace", ATTR_HSPACE},
      {"rules", ATTR_RULES},
      {"vspace", ATTR_VSPACE},
      {"pagey", ATTR_PAGEY},
      {"scheme", ATTR_SCHEME},
      {"oversrc", ATTR_OVERSRC},
      {"media", ATTR_MEDIA},
      {"border", ATTR_BORDER},
      {"datetime", ATTR_DATETIME},
      {"char", ATTR_CHAR},
      {"version", ATTR_VERSION},
      {"charset", ATTR_CHARSET},
      {"codebase", ATTR_CODEBASE},
      {"face", ATTR_FACE},
      {"topmargin", ATTR_TOPMARGIN},
      {"onkeypress", ATTR_ONKEYPRESS},
      {"onchange", ATTR_ONCHANGE},
      {"challenge", ATTR_CHALLENGE},
      {"noshade", ATTR_NOSHADE},
      {"method", ATTR_METHOD},
      {"profile", ATTR_PROFILE},
      {"readonly", ATTR_READONLY},
      {"defer", ATTR_DEFER},
      {"bordercolor", ATTR_BORDERCOLOR},
      {"tabindex", ATTR_TABINDEX},
      {"vlink", ATTR_VLINK},
      {"bgproperties", ATTR_BGPROPERTIES},
      {"cellpadding", ATTR_CELLPADDING},
      {"headers", ATTR_HEADERS},
      {"onunload", ATTR_ONUNLOAD},
      {"accesskey", ATTR_ACCESSKEY},
      {"contenteditable", ATTR_CONTENTEDITABLE},
      {"valign", ATTR_VALIGN},
      {"multiple", ATTR_MULTIPLE},
      {"abbr", ATTR_ABBR},
      {"usemap", ATTR_USEMAP},
      {"checked", ATTR_CHECKED},
      {"maxlength", ATTR_MAXLENGTH},
      {"hidden", ATTR_HIDDEN},
      {"autocomplete", ATTR_AUTOCOMPLETE},
      {"onblur", ATTR_ONBLUR},
      {"accept-charset", ATTR_ACCEPT_CHARSET},
      {"frame", ATTR_FRAME},
      {"ondblclick", ATTR_ONDBLCLICK},
      {"disabled", ATTR_DISABLED},
      {"width", ATTR_WIDTH},
      {"href", ATTR_HREF},
      {"nohref", ATTR_NOHREF},
      {"standby", ATTR_STANDBY},
      {"unknown", ATTR_UNKNOWN},
      {"onkeydown", ATTR_ONKEYDOWN},
      {"value", ATTR_VALUE},
      {"height", ATTR_HEIGHT},
      {"onfocus", ATTR_ONFOCUS},
      {"language", ATTR_LANGUAGE},
      {"pluginpage", ATTR_PLUGINPAGE},
      {"onkeyup", ATTR_ONKEYUP},
      {"pluginspage", ATTR_PLUGINSPAGE},
      {"onmousedown", ATTR_ONMOUSEDOWN},
      {"onsubmit", ATTR_ONSUBMIT},
      {"leftmargin", ATTR_LEFTMARGIN},
      {"onmouseover", ATTR_ONMOUSEOVER},
      {"archive", ATTR_ARCHIVE},
      {"onmouseup", ATTR_ONMOUSEUP},
      {"onmouseout", ATTR_ONMOUSEOUT},
      {"hreflang", ATTR_HREFLANG},
      {"onmousemove", ATTR_ONMOUSEMOVE},
      {"pluginurl", ATTR_PLUGINURL},
      {"valuetype", ATTR_VALUETYPE},
      {"summary", ATTR_SUMMARY},
      {"http-equiv", ATTR_HTTP_EQUIV},
      {"frameborder", ATTR_FRAMEBORDER},
      {"background", ATTR_BACKGROUND},
      {"marginwidth", ATTR_MARGINWIDTH},
      {"charoff", ATTR_CHAROFF},
      {"visibility", ATTR_VISIBILITY},
      {"marginheight", ATTR_MARGINHEIGHT}
    };

  static const short lookup[] =
    {
        -1,   -1,   -1,    0,    1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,    2,   -1,    3,    4,   -1,   -1,    5,
        -1,   -1,   -1,   -1,    6,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,    7,   -1,   -1,
         8,   -1,   -1,    9,   -1,   -1,   -1,   -1,
        10,   -1,   11,   -1,   -1,   -1,   12,   -1,
        -1,   -1,   -1,   13,   -1,   -1,   -1,   -1,
        14,   -1,   -1,   15,   -1,   16,   17,   18,
        -1,   19,   -1,   -1,   -1,   -1,   -1,   -1,
        20,   -1,   21,   -1,   -1,   22,   23,   -1,
        -1,   24,   25,   -1,   -1,   -1,   -1,   26,
        27,   28, -248,   31,   -1,   32, -116,   -2,
        33,   -1,   34,   -1,   -1,   35,   -1,   36,
        -1,   37,   38,   39,   40,   41,   -1,   42,
        -1,   -1,   43,   44,   -1,   -1,   -1,   45,
        -1,   -1,   -1,   -1,   -1,   -1,   46,   47,
        -1,   48,   -1,   -1,   -1,   -1,   49,   -1,
        50,   51,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   52,   53,   54,   55,   -1,   -1,   56,
        -1,   -1,   57,   -1,   -1,   58,   59,   60,
        -1,   -1,   -1,   -1,   61,   62,   -1,   63,
        -1,   64,   -1,   65,   -1,   66,   -1,   67,
        -1,   -1,   68,   -1,   -1,   -1,   69,   70,
        -1,   -1,   -1,   71,   72,   73,   -1,   -1,
        74,   75,   -1,   76,   77,   -1,   -1,   78,
        -1,   -1,   -1,   -1,   79,   80,   81,   -1,
        -1,   -1,   -1,   82,   83,   -1,   -1,   84,
        85,   -1,   -1,   86,   -1,   -1,   -1,   87,
        88,   89,   -1,   90,   -1,   -1,   -1,   -1,
        -1,   91,   -1,   92,   -1,   93,   -1,   94,
        -1,   -1,   -1,   95,   96,   -1,   -1,   -1,
        -1,   -1,   97,   98,   99,  100,   -1,  101,
       102,   -1,  103,  104,   -1,  105,   -1,  106,
        -1,   -1,   -1,   -1,   -1,  107,   -1,   -1,
        -1,  108,   -1,   -1,  109,  110,   -1,   -1,
        -1,   -1,  111,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,  112,   -1,  113,   -1,   -1,   -1,
       114,   -1,  115,  116,   -1,   -1,   -1,   -1,
       117,   -1,  118,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,  119,  120,  121,  122,   -1,  123,
        -1,  124,   -1,   -1,   -1,  125,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,  126,   -1,   -1,   -1,
        -1,   -1,   -1,  127,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,  128,
       129,  130,   -1,  131,  132,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,  133,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,  134,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,  135,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,  136,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,  137,   -1,   -1,  138,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,  139,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,  140,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,  141,  142,   -1,   -1,
       143,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
        -1,   -1,   -1,  144
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = hash_attr (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        {
          register int index = lookup[key];

          if (index >= 0)
            {
              register const char *s = wordlist_attr[index].name;

              if (*str == *s && !strncmp (str + 1, s + 1, len - 1) && s[len] == '\0')
                return &wordlist_attr[index];
            }
          else if (index < -TOTAL_KEYWORDS)
            {
              register int offset = - 1 - TOTAL_KEYWORDS - index;
              register const struct attrs *wordptr = &wordlist_attr[TOTAL_KEYWORDS + lookup[offset]];
              register const struct attrs *wordendptr = wordptr + -lookup[offset + 1];

              while (wordptr < wordendptr)
                {
                  register const char *s = wordptr->name;

                  if (*str == *s && !strncmp (str + 1, s + 1, len - 1) && s[len] == '\0')
                    return wordptr;
                  wordptr++;
                }
            }
        }
    }
  return 0;
}


static const char * const attrList[] = {
    "ABBR",
    "ACCEPT-CHARSET",
    "ACCEPT",
    "ACCESSKEY",
    "ACTION",
    "ALIGN",
    "ALINK",
    "ALT",
    "ARCHIVE",
    "AUTOCOMPLETE",
    "AXIS",
    "BACKGROUND",
    "BGCOLOR",
    "BGPROPERTIES",
    "BORDER",
    "BORDERCOLOR",
    "CELLPADDING",
    "CELLSPACING",
    "CHAR",
    "CHALLENGE",
    "CHAROFF",
    "CHARSET",
    "CHECKED",
    "CITE",
    "CLASS",
    "CLASSID",
    "CLEAR",
    "CODE",
    "CODEBASE",
    "CODETYPE",
    "COLOR",
    "COLS",
    "COLSPAN",
    "COMPACT",
    "CONTENT",
    "CONTENTEDITABLE",
    "COORDS",
    "DATA",
    "DATETIME",
    "DECLARE",
    "DEFER",
    "DIR",
    "DISABLED",
    "ENCTYPE",
    "FACE",
    "FOR",
    "FRAME",
    "FRAMEBORDER",
    "HEADERS",
    "HEIGHT",
    "HIDDEN",
    "HREF",
    "HREFLANG",
    "HSPACE",
    "HTML",
    "HTTP-EQUIV",
    "ID",
    "ISMAP",
    "LABEL",
    "LANG",
    "LANGUAGE",
    "LEFT",
    "LEFTMARGIN",
    "LINK",
    "LONGDESC",
    "MARGINHEIGHT",
    "MARGINWIDTH",
    "MAXLENGTH",
    "MEDIA",
    "METHOD",
    "MULTIPLE",
    "NAME",
    "NOHREF",
    "NORESIZE",
    "NOSAVE",
    "NOSHADE",
    "NOWRAP",
    "OBJECT",
    "ONABORT",
    "ONBLUR",
    "ONCHANGE",
    "ONCLICK",
    "ONDBLCLICK",
    "ONERROR",
    "ONFOCUS",
    "ONKEYDOWN",
    "ONKEYPRESS",
    "ONKEYUP",
    "ONLOAD",
    "ONMOUSEDOWN",
    "ONMOUSEMOVE",
    "ONMOUSEOUT",
    "ONMOUSEOVER",
    "ONMOUSEUP",
    "ONRESET",
    "ONRESIZE",
    "ONSELECT",
    "ONSUBMIT",
    "ONUNLOAD",
    "OVERSRC",
    "PAGEX",
    "PAGEY",
    "PLAIN",
    "PLUGINPAGE",
    "PLUGINSPAGE",
    "PLUGINURL",
    "PROFILE",
    "PROMPT",
    "READONLY",
    "REL",
    "REV",
    "ROWS",
    "ROWSPAN",
    "RULES",
    "SCHEME",
    "SCOPE",
    "SCROLLING",
    "SELECTED",
    "SHAPE",
    "SIZE",
    "SPAN",
    "SRC",
    "STANDBY",
    "START",
    "STYLE",
    "SUMMARY",
    "TABINDEX",
    "TARGET",
    "TEXT",
    "TITLE",
    "TOP",
    "TOPMARGIN",
    "TYPE",
    "UNKNOWN",
    "USEMAP",
    "VALIGN",
    "VALUE",
    "VALUETYPE",
    "VERSION",
    "VISIBILITY",
    "VLINK",
    "VSPACE",
    "WIDTH",
    "WRAP",
    "Z-INDEX",
    0
};
DOM::DOMString KDE_NO_EXPORT getAttrName(unsigned short id)
{
    return attrList[id-1];
}
