/* This file is automatically generated from htmltags.in and htmlattrs.in by gennames.py, do not edit */
/* Copyright 2008 Vyacheslav Tokarev */

#ifndef HTMLNames_h
#define HTMLNames_h

#include "misc/idstring.h"

#define XHTML_NAMESPACE "http://www.w3.org/1999/xhtml"
#define SVG_NAMESPACE "http://www.w3.org/2000/svg"

#define ID_A 1
#define ID_ABBR 2
#define ATTR_ABBR 65538
#define ID_ACRONYM 3
#define ID_ADDRESS 4
#define ID_APPLET 5
#define ID_AREA 6
#define ID_AUDIO 7
#define ID_B 8
#define ID_BASE 9
#define ID_BASEFONT 10
#define ID_BDO 11
#define ID_BIG 12
#define ID_BLOCKQUOTE 13
#define ID_BODY 14
#define ID_BR 15
#define ID_BUTTON 16
#define ID_CANVAS 17
#define ID_CAPTION 18
#define ID_CENTER 19
#define ID_CITE 20
#define ATTR_CITE 65556
#define ID_CODE 21
#define ATTR_CODE 65557
#define ID_COL 22
#define ID_COLGROUP 23
#define ID_DD 24
#define ID_DEL 25
#define ID_DFN 26
#define ID_DIR 27
#define ATTR_DIR 65563
#define ID_DIV 28
#define ID_DL 29
#define ID_DT 30
#define ID_EM 31
#define ID_EMBED 32
#define ID_FIELDSET 33
#define ID_FONT 34
#define ID_FORM 35
#define ID_FRAME 36
#define ATTR_FRAME 65572
#define ID_FRAMESET 37
#define ID_H1 38
#define ID_H2 39
#define ID_H3 40
#define ID_H4 41
#define ID_H5 42
#define ID_H6 43
#define ID_HEAD 44
#define ID_HR 45
#define ID_HTML 46
#define ATTR_HTML 65582
#define ID_I 47
#define ID_IFRAME 48
#define ID_ILAYER 49
#define ID_IMG 50
#define ID_INPUT 51
#define ID_INS 52
#define ID_ISINDEX 53
#define ID_KBD 54
#define ID_KEYGEN 55
#define ID_LABEL 56
#define ATTR_LABEL 65592
#define ID_LAYER 57
#define ID_LEGEND 58
#define ID_LI 59
#define ID_LINK 60
#define ATTR_LINK 65596
#define ID_LISTING 61
#define ID_MAP 62
#define ID_MARQUEE 63
#define ID_MENU 64
#define ID_META 65
#define ID_NOBR 66
#define ID_NOEMBED 67
#define ID_NOFRAMES 68
#define ID_NOSCRIPT 69
#define ID_NOLAYER 70
#define ID_OBJECT 71
#define ATTR_OBJECT 65607
#define ID_OL 72
#define ID_OPTGROUP 73
#define ID_OPTION 74
#define ID_P 75
#define ID_PARAM 76
#define ID_PLAINTEXT 77
#define ID_PRE 78
#define ID_Q 79
#define ID_S 80
#define ID_SAMP 81
#define ID_SCRIPT 82
#define ID_SELECT 83
#define ID_SMALL 84
#define ID_SOURCE 85
#define ID_SPAN 86
#define ATTR_SPAN 65622
#define ID_STRIKE 87
#define ID_STRONG 88
#define ID_STYLE 89
#define ATTR_STYLE 65625
#define ID_SUB 90
#define ID_SUP 91
#define ID_TABLE 92
#define ID_TBODY 93
#define ID_TD 94
#define ID_TEXTAREA 95
#define ID_TFOOT 96
#define ID_TH 97
#define ID_THEAD 98
#define ID_TITLE 99
#define ATTR_TITLE 65635
#define ID_TR 100
#define ID_TT 101
#define ID_U 102
#define ID_UL 103
#define ID_VAR 104
#define ID_VIDEO 105
#define ID_WBR 106
#define ID_XMP 107
#define ID_TEXT 108
#define ID_COMMENT 109
#define ATTR_ACCEPT_CHARSET 65646
#define ATTR_ACCEPT 65647
#define ATTR_ACCESSKEY 65648
#define ATTR_ALIGN 65649
#define ATTR_ALINK 65650
#define ATTR_AUTOCOMPLETE 65651
#define ATTR_AUTOPLAY 65652
#define ATTR_AXIS 65653
#define ATTR_BEHAVIOR 65654
#define ATTR_BGCOLOR 65655
#define ATTR_BGPROPERTIES 65656
#define ATTR_BORDER 65657
#define ATTR_BORDERCOLOR 65658
#define ATTR_CELLPADDING 65659
#define ATTR_CELLSPACING 65660
#define ATTR_CHAR 65661
#define ATTR_CHALLENGE 65662
#define ATTR_CHAROFF 65663
#define ATTR_CHARSET 65664
#define ATTR_CHECKED 65665
#define ATTR_CLEAR 65666
#define ATTR_CODETYPE 65667
#define ATTR_COLOR 65668
#define ATTR_COLS 65669
#define ATTR_COLSPAN 65670
#define ATTR_COMPACT 65671
#define ATTR_CONTENTEDITABLE 65672
#define ATTR_CONTROLS 65673
#define ATTR_COORDS 65674
#define ATTR_DECLARE 65675
#define ATTR_DEFER 65676
#define ATTR_DIRECTION 65677
#define ATTR_DISABLED 65678
#define ATTR_ENCTYPE 65679
#define ATTR_END 65680
#define ATTR_FACE 65681
#define ATTR_FRAMEBORDER 65682
#define ATTR_HEIGHT 65683
#define ATTR_HIDDEN 65684
#define ATTR_HREFLANG 65685
#define ATTR_HSPACE 65686
#define ATTR_HTTP_EQUIV 65687
#define ATTR_ISMAP 65688
#define ATTR_LANG 65689
#define ATTR_LANGUAGE 65690
#define ATTR_LEFT 65691
#define ATTR_LEFTMARGIN 65692
#define ATTR_LOOP 65693
#define ATTR_LOOPEND 65694
#define ATTR_LOOPSTART 65695
#define ATTR_MARGINHEIGHT 65696
#define ATTR_MARGINWIDTH 65697
#define ATTR_MAXLENGTH 65698
#define ATTR_MEDIA 65699
#define ATTR_METHOD 65700
#define ATTR_MULTIPLE 65701
#define ATTR_NOHREF 65702
#define ATTR_NORESIZE 65703
#define ATTR_NOSAVE 65704
#define ATTR_NOSHADE 65705
#define ATTR_NOWRAP 65706
#define ATTR_ONABORT 65707
#define ATTR_ONERROR 65708
#define ATTR_ONRESIZE 65709
#define ATTR_OVERSRC 65710
#define ATTR_PAGEX 65711
#define ATTR_PAGEY 65712
#define ATTR_PLAIN 65713
#define ATTR_PLAYCOUNT 65714
#define ATTR_PLUGINPAGE 65715
#define ATTR_PLUGINSPAGE 65716
#define ATTR_PLUGINURL 65717
#define ATTR_POSTER 65718
#define ATTR_READONLY 65719
#define ATTR_REL 65720
#define ATTR_REV 65721
#define ATTR_ROWS 65722
#define ATTR_ROWSPAN 65723
#define ATTR_RULES 65724
#define ATTR_SCOPE 65725
#define ATTR_SCROLLAMOUNT 65726
#define ATTR_SCROLLDELAY 65727
#define ATTR_SCROLLING 65728
#define ATTR_SELECTED 65729
#define ATTR_SHAPE 65730
#define ATTR_SIZE 65731
#define ATTR_START 65732
#define ATTR_TABINDEX 65733
#define ATTR_TARGET 65734
#define ATTR_TEXT 65735
#define ATTR_TOP 65736
#define ATTR_TOPMARGIN 65737
#define ATTR_TRUESPEED 65738
#define ATTR_TYPE 65739
#define ATTR_UNKNOWN 65740
#define ATTR_VALIGN 65741
#define ATTR_VALUETYPE 65742
#define ATTR_VERSION 65743
#define ATTR_VISIBILITY 65744
#define ATTR_VLINK 65745
#define ATTR_VSPACE 65746
#define ATTR_WIDTH 65747
#define ATTR_WRAP 65748
#define ATTR_Z_INDEX 65749
#define ATTR_ACTION 65750
#define ATTR_ALT 65751
#define ATTR_ARCHIVE 65752
#define ATTR_BACKGROUND 65753
#define ATTR_CLASS 65754
#define ATTR_CLASSID 65755
#define ATTR_CODEBASE 65756
#define ATTR_CONTENT 65757
#define ATTR_DATA 65758
#define ATTR_DATETIME 65759
#define ATTR_FOR 65760
#define ATTR_HEADERS 65761
#define ATTR_HREF 65762
#define ATTR_ID 65763
#define ATTR_LONGDESC 65764
#define ATTR_NAME 65765
#define ATTR_ONBLUR 65766
#define ATTR_ONCHANGE 65767
#define ATTR_ONCLICK 65768
#define ATTR_ONDBLCLICK 65769
#define ATTR_ONFOCUS 65770
#define ATTR_ONKEYDOWN 65771
#define ATTR_ONKEYPRESS 65772
#define ATTR_ONKEYUP 65773
#define ATTR_ONLOAD 65774
#define ATTR_ONMOUSEDOWN 65775
#define ATTR_ONMOUSEMOVE 65776
#define ATTR_ONMOUSEOUT 65777
#define ATTR_ONMOUSEOVER 65778
#define ATTR_ONMOUSEUP 65779
#define ATTR_ONRESET 65780
#define ATTR_ONSELECT 65781
#define ATTR_ONSCROLL 65782
#define ATTR_ONSUBMIT 65783
#define ATTR_ONUNLOAD 65784
#define ATTR_PROFILE 65785
#define ATTR_PROMPT 65786
#define ATTR_SCHEME 65787
#define ATTR_SRC 65788
#define ATTR_STANDBY 65789
#define ATTR_SUMMARY 65790
#define ATTR_USEMAP 65791
#define ATTR_VALUE 65792
#define ID_LAST_TAG 109
#define ID_CLOSE_TAG 16384
#define ATTR_LAST_ATTR 256
#define ATTR_LAST_CI_ATTR 213

#define caseSensitiveAttr(id) (((localNamePart(id)) > ATTR_LAST_CI_ATTR || (id) == ATTR_ABBR || (id) == ATTR_CITE || (id) == ATTR_CODE || (id) == ATTR_LABEL || (id) == ATTR_OBJECT || (id) == ATTR_TITLE))

namespace DOM {

#define NodeImpl_IdNSMask    0xffff0000
#define NodeImpl_IdLocalMask 0x0000ffff

const quint16 xhtmlNamespace = 0;
const quint16 emptyNamespace = 1;
const quint16 svgNamespace = 2;
const quint16 anyNamespace = 0xffff;
const quint16 anyLocalName = 0xffff;
const quint16 emptyPrefix = 0;

inline quint16 localNamePart(quint32 id) { return id & NodeImpl_IdLocalMask; }
inline quint16 namespacePart(quint32 id) { return (((unsigned int)id) & NodeImpl_IdNSMask) >> 16; }
inline quint32 makeId(quint16 n, quint16 l) { return (n << 16) | l; }

const quint32 anyQName = makeId(anyNamespace, anyLocalName);

}

namespace khtml {

class NamespaceFactory {
public:
    static IDTable<NamespaceFactory>* idTable() {
    if (s_idTable)
            return s_idTable;
        else
            return initIdTable();
    }
protected:
    static IDTable<NamespaceFactory>* s_idTable;
    static IDTable<NamespaceFactory>* initIdTable();
};

class LocalNameFactory {
public:
    static IDTable<LocalNameFactory>* idTable() {
        if (s_idTable)
            return s_idTable;
        else
            return initIdTable();
    }
protected:
    static IDTable<LocalNameFactory>* s_idTable;
    static IDTable<LocalNameFactory>* initIdTable();
};

class PrefixFactory {
public:
    static IDTable<PrefixFactory>* idTable() {
        if (s_idTable)
            return s_idTable;
        else
            return initIdTable();
    }
protected:
    static IDTable<PrefixFactory>* s_idTable;
    static IDTable<PrefixFactory>* initIdTable();
};

}

namespace DOM {

    typedef khtml::IDString<khtml::NamespaceFactory> NamespaceName;
    typedef khtml::IDString<khtml::LocalNameFactory> LocalName;
    typedef khtml::IDString<khtml::PrefixFactory> PrefixName;
    extern PrefixName emptyPrefixName;
    extern LocalName emptyLocalName;
    extern NamespaceName emptyNamespaceName;

    QString getPrintableName(int id);

}
#endif
