/*
 * This file has been generated by the onto2vocabularyclass tool
 * copyright (C) 2007-2008 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

#include "nie.h"

class NiePrivate
{
public:
    NiePrivate()
        : nie_namespace( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#", QUrl::StrictMode ) ),
          nie_DataObject( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataObject", QUrl::StrictMode ) ),
          nie_InformationElement( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement", QUrl::StrictMode ) ),
          nie_url( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#url", QUrl::StrictMode ) ) {
    }

    QUrl nie_namespace;
    QUrl nie_DataObject;
    QUrl nie_InformationElement;
    QUrl nie_url;
};

Q_GLOBAL_STATIC( NiePrivate, s_nie )

QUrl Nepomuk::Vocabulary::NIE::nieNamespace()
{
    return s_nie()->nie_namespace;
}

QUrl Nepomuk::Vocabulary::NIE::DataObject()
{
    return s_nie()->nie_DataObject;
}

QUrl Nepomuk::Vocabulary::NIE::InformationElement()
{
    return s_nie()->nie_InformationElement;
}

QUrl Nepomuk::Vocabulary::NIE::url()
{
    return s_nie()->nie_url;
}
