#!/bin/sh
set -e

# HACK!
#
# When using superbuild with DESTDIR set, frameworks are installed in
# $DESTDIR/$CMAKE_INSTALL_PREFIX. This cause dependencies problems: For example
# when KAuth is built, it tries to find KCoreAddons and looks for it in
# $CMAKE_INSTALL_PREFIX but it is only in $DESTDIR/$CMAKE_INSTALL_PREFIX for now
# so the find_package() call fails.
#
# The hack consists of setting CMAKE_PREFIX_PATH to
# $DESTDIR/$CMAKE_INSTALL_PREFIX. This makes it possible for frameworks to find
# other frameworks they depend on.
#
# The first two arguments of this script are the full path to the cmake binary
# and the value of CMAKE_INSTALL_PREFIX. It computes CMAKE_PREFIX_PATH from the
# later and calls cmake, passing all other arguments.

CMAKE_COMMAND=$1
CMAKE_INSTALL_PREFIX=$2
shift 2

echo "sbcmake: Running $CMAKE_COMMAND -DCMAKE_PREFIX_PATH=$DESTDIR/$CMAKE_INSTALL_PREFIX \"$@\""
exec $CMAKE_COMMAND -DCMAKE_PREFIX_PATH=$DESTDIR/$CMAKE_INSTALL_PREFIX "$@"
