#! /usr/bin/env python

Import('env')

# test if install is really wanted
if env['_INSTALL_']:
	# ahem .. a real glob function needed somewhere (ita)
	import glob
	import SCons.Util

	# get the path to the sources
	path=SCons.Node.FS.default_fs.Dir('.').srcnode().abspath

	dirs="uri model audio multipart image application message text video inode"
	# process each subfolder
	for dir in dirs.split():
		files=glob.glob( env.join(path, dir, '*.desktop') )
		env.bksys_insttype('KDEMIME', dir, files, 0644)
	
#	import os, string, fnmatch
#	for root, dirs, files in os.walk('.'):
#		insttar = os.path.join(env['KDEMIME'], root)
#		files = fnmatch.filter( files, "*.desktop")
#		toinst = []
#		for file in files: 
#			toinst.append(os.path.join(root, file))
#
#		if toinst:
#			env.bksys_install(insttar, toinst)

