QRect
QRect::QRect()
Referenced by adjusted, translated.
QRect::QRect(const QPoint &topleft, const QPoint &bottomright)
References QPoint::x, QPoint::y.
QRect::QRect(const QPoint &topleft, const QSize &size)
References QSize::height, QSize::width, QPoint::x, QPoint::y.
QRect::QRect(int left, int top, int width, int height)
bool QRect::isNull() const
bool QRect::isEmpty() const
bool QRect::isValid() const
int QRect::left() const
int QRect::top() const
int QRect::right() const
int QRect::bottom() const
QRect QRect::normalized() const
int QRect::x() const
int QRect::y() const
void QRect::setLeft(int pos)
void QRect::setTop(int pos)
void QRect::setRight(int pos)
void QRect::setBottom(int pos)
void QRect::setX(int x)
void QRect::setY(int y)
void QRect::setTopLeft(const QPoint &p)
References QPoint::x, QPoint::y.
void QRect::setBottomRight(const QPoint &p)
References QPoint::x, QPoint::y.
void QRect::setTopRight(const QPoint &p)
References QPoint::x, QPoint::y.
void QRect::setBottomLeft(const QPoint &p)
References QPoint::x, QPoint::y.
QPoint QRect::topLeft() const
QPoint QRect::bottomRight() const
QPoint QRect::topRight() const
QPoint QRect::bottomLeft() const
QPoint QRect::center() const
void QRect::moveLeft(int pos)
Referenced by moveBottomLeft, moveTopLeft.
void QRect::moveTop(int pos)
Referenced by moveTopLeft, moveTopRight.
void QRect::moveRight(int pos)
Referenced by moveBottomRight, moveTopRight.
void QRect::moveBottom(int pos)
Referenced by moveBottomLeft, moveBottomRight.
void QRect::moveTopLeft(const QPoint &p)
References moveLeft, moveTop, QPoint::x, QPoint::y.
void QRect::moveBottomRight(const QPoint &p)
References moveBottom, moveRight, QPoint::x, QPoint::y.
void QRect::moveTopRight(const QPoint &p)
References moveRight, moveTop, QPoint::x, QPoint::y.
void QRect::moveBottomLeft(const QPoint &p)
References moveBottom, moveLeft, QPoint::x, QPoint::y.
void QRect::moveCenter(const QPoint &p)
void QRect::translate(int dx, int dy)
void QRect::translate(const QPoint &p)
References QPoint::x, QPoint::y.
QRect QRect::translated(int dx, int dy) const
References QRect.
QRect QRect::translated(const QPoint &p) const
References QRect, QPoint::x, QPoint::y.
void QRect::moveTo(int x, int t)
void QRect::moveTo(const QPoint &p)
References QPoint::x, QPoint::y.
void QRect::setRect(int x, int y, int w, int h)
void QRect::getRect(int *x, int *y, int *w, int *h) const
void QRect::setCoords(int x1, int y1, int x2, int y2)
void QRect::getCoords(int *x1, int *y1, int *x2, int *y2) const
void QRect::adjust(int x1, int y1, int x2, int y2)
QRect QRect::adjusted(int x1, int y1, int x2, int y2) const
References QRect.
QSize QRect::size() const
References height, width.
int QRect::width() const
Referenced by size.
int QRect::height() const
Referenced by size.
void QRect::setWidth(int w)
void QRect::setHeight(int h)
void QRect::setSize(const QSize &s)
References QSize::height, QSize::width.
QRect QRect::operator|(const QRect &r) const
QRect QRect::operator &(const QRect &r) const
QRect & QRect::operator|=(const QRect &r)
QRect & QRect::operator &=(const QRect &r)
bool QRect::contains(const QPoint &p, bool proper=false) const
Referenced by contains.
bool QRect::contains(int x, int y) const
References contains.
bool QRect::contains(int x, int y, bool proper) const
References contains.
bool QRect::contains(const QRect &r, bool proper=false) const
QRect QRect::unite(const QRect &r) const
QRect QRect::intersect(const QRect &r) const
bool QRect::intersects(const QRect &r) const
int QRect::x1
Referenced by operator!=, operator==.
int QRect::y1
Referenced by operator!=, operator==.
int QRect::x2
Referenced by operator!=, operator==.
int QRect::y2
Referenced by operator!=, operator==.
Q_CORE_EXPORT bool operator==(const QRect &, const QRect &)
Q_CORE_EXPORT bool operator!=(const QRect &, const QRect &)