QSize
QSize::QSize()
Referenced by boundedTo, expandedTo, scale.
QSize::QSize(int w, int h)
bool QSize::isNull() const
bool QSize::isEmpty() const
bool QSize::isValid() const
int QSize::width() const
Referenced by QRect::QRect, QRect::setSize.
int QSize::height() const
Referenced by QRect::QRect, QRect::setSize.
void QSize::setWidth(int w)
void QSize::setHeight(int h)
void QSize::transpose()
void QSize::scale(int w, int h, Qt::AspectRatioMode mode)
References QSize.
void QSize::scale(const QSize &s, Qt::AspectRatioMode mode)
QSize QSize::expandedTo(const QSize &) const
References ht, QSize, wd.
QSize QSize::boundedTo(const QSize &) const
References ht, QSize, wd.
int & QSize::rwidth()
int & QSize::rheight()
QSize & QSize::operator+=(const QSize &)
References ht, wd.
QSize & QSize::operator-=(const QSize &)
References ht, wd.
QSize & QSize::operator *=(qreal c)
QSize & QSize::operator/=(qreal c)
int QSize::wd
Referenced by boundedTo, expandedTo, operator *, operator!=, operator+, operator+=, operator-, operator-=, operator/, operator==.
int QSize::ht
Referenced by boundedTo, expandedTo, operator *, operator!=, operator+, operator+=, operator-, operator-=, operator/, operator==.
bool operator==(const QSize &, const QSize &)
bool operator!=(const QSize &, const QSize &)
const QSize operator+(const QSize &, const QSize &)
const QSize operator-(const QSize &, const QSize &)
const QSize operator *(const QSize &, qreal)
const QSize operator *(qreal, const QSize &)
const QSize operator/(const QSize &, qreal)