QFont
StyleHint
StyleStrategy
Weight
Style
Stretch
QFont::QFont()
QFont::QFont(const QString &family, int pointSize=-1, int weight=-1, bool italic=false)
QFont::QFont(const QFont &, QPaintDevice *pd)
QFont::QFont(const QFont &)
QFont::~QFont()
QString QFont::family() const
void QFont::setFamily(const QString &)
int QFont::pointSize() const
void QFont::setPointSize(int)
qreal QFont::pointSizeF() const
void QFont::setPointSizeF(qreal)
int QFont::pixelSize() const
void QFont::setPixelSize(int)
int QFont::weight() const
Referenced by bold.
void QFont::setWeight(int)
Referenced by setBold.
bool QFont::bold() const
References Normal, weight.
void QFont::setBold(bool)
References Bold, Normal, setWeight.
void QFont::setStyle(Style style)
Referenced by setItalic.
Style QFont::style() const
Referenced by italic.
bool QFont::italic() const
References style, StyleNormal.
void QFont::setItalic(bool b)
References setStyle, StyleItalic, StyleNormal.
bool QFont::underline() const
void QFont::setUnderline(bool)
bool QFont::overline() const
void QFont::setOverline(bool)
bool QFont::strikeOut() const
void QFont::setStrikeOut(bool)
bool QFont::fixedPitch() const
void QFont::setFixedPitch(bool)
bool QFont::kerning() const
void QFont::setKerning(bool)
StyleHint QFont::styleHint() const
StyleStrategy QFont::styleStrategy() const
void QFont::setStyleHint(StyleHint, StyleStrategy=PreferDefault)
void QFont::setStyleStrategy(StyleStrategy s)
int QFont::stretch() const
void QFont::setStretch(int)
bool QFont::rawMode() const
void QFont::setRawMode(bool)
bool QFont::exactMatch() const
QFont& QFont::operator=(const QFont &)
bool QFont::operator==(const QFont &) const
bool QFont::operator!=(const QFont &) const
bool QFont::operator<(const QFont &) const
QFont::operator QVariant() const
bool QFont::isCopyOf(const QFont &) const
Qt::HANDLE QFont::handle() const
void QFont::setRawName(const QString &)
QString QFont::rawName() const
QString QFont::key() const
QString QFont::toString() const
bool QFont::fromString(const QString &)
QString QFont::defaultFamily() const
QString QFont::lastResortFamily() const
QString QFont::lastResortFont() const
QFont QFont::resolve(const QFont &) const
uint QFont::resolve() const
void QFont::resolve(uint mask)
static QString QFont::substitute(const QString &)
static QStringList QFont::substitutes(const QString &)
static QStringList QFont::substitutions()
static void QFont::insertSubstitution(const QString &, const QString &)
static void QFont::insertSubstitutions(const QString &, const QStringList &)
static void QFont::removeSubstitution(const QString &)
static void QFont::initialize()
static void QFont::cleanup()
static void QFont::cacheStatistics()
QFont::QFont(QFontPrivate *)
void QFont::detach()
QFontPrivate* QFont::d
uint QFont::resolve_mask
friend class QFontMetrics
friend class QFontMetricsF
friend class QFontInfo
friend class QPainter
friend class QPSPrintEngineFont
friend class QApplication
friend class QWidget
friend class QWidgetPrivate
friend class Q3TextFormatCollection
friend class QTextLayout
friend class QTextEngine
friend class QTextLine
friend struct QScriptLine
friend class QGLContext
friend class QWin32PaintEngine
friend class QPainterPath
Q_GUI_EXPORT QDataStream& operator<<(QDataStream &, const QFont &)
Q_GUI_EXPORT QDataStream& operator>>(QDataStream &, QFont &)