QRectF
QRectF::QRectF()
Referenced by adjusted, translated.
QRectF::QRectF(const QPointF &topleft, const QSizeF &size)
References QSizeF::height, QSizeF::width, QPointF::x, QPointF::y.
QRectF::QRectF(qreal left, qreal top, qreal width, qreal height)
QRectF::QRectF(const QRect &rect)
bool QRectF::isNull() const
bool QRectF::isEmpty() const
bool QRectF::isValid() const
QRectF QRectF::normalized() const
qreal QRectF::left() const
qreal QRectF::top() const
qreal QRectF::right() const
qreal QRectF::bottom() const
qreal QRectF::x() const
qreal QRectF::y() const
void QRectF::setLeft(qreal pos)
Referenced by setBottomLeft, setTopLeft.
void QRectF::setTop(qreal pos)
Referenced by setTopLeft, setTopRight.
void QRectF::setRight(qreal pos)
Referenced by setBottomRight, setTopRight.
void QRectF::setBottom(qreal pos)
Referenced by setBottomLeft, setBottomRight.
void QRectF::setX(qreal pos)
void QRectF::setY(qreal pos)
QPointF QRectF::topLeft() const
QPointF QRectF::bottomRight() const
QPointF QRectF::topRight() const
QPointF QRectF::bottomLeft() const
QPointF QRectF::center() const
void QRectF::setTopLeft(const QPointF &p)
References setLeft, setTop, QPointF::x, QPointF::y.
void QRectF::setBottomRight(const QPointF &p)
References setBottom, setRight, QPointF::x, QPointF::y.
void QRectF::setTopRight(const QPointF &p)
References setRight, setTop, QPointF::x, QPointF::y.
void QRectF::setBottomLeft(const QPointF &p)
References setBottom, setLeft, QPointF::x, QPointF::y.
void QRectF::moveLeft(qreal pos)
Referenced by moveBottomLeft, moveTopLeft.
void QRectF::moveTop(qreal pos)
Referenced by moveTopLeft, moveTopRight.
void QRectF::moveRight(qreal pos)
Referenced by moveBottomRight, moveTopRight.
void QRectF::moveBottom(qreal pos)
Referenced by moveBottomLeft, moveBottomRight.
void QRectF::moveTopLeft(const QPointF &p)
References moveLeft, moveTop, QPointF::x, QPointF::y.
void QRectF::moveBottomRight(const QPointF &p)
References moveBottom, moveRight, QPointF::x, QPointF::y.
void QRectF::moveTopRight(const QPointF &p)
References moveRight, moveTop, QPointF::x, QPointF::y.
void QRectF::moveBottomLeft(const QPointF &p)
References moveBottom, moveLeft, QPointF::x, QPointF::y.
void QRectF::moveCenter(const QPointF &p)
References QPointF::x, QPointF::y.
void QRectF::translate(qreal dx, qreal dy)
void QRectF::translate(const QPointF &p)
References QPointF::x, QPointF::y.
QRectF QRectF::translated(qreal dx, qreal dy) const
References QRectF.
QRectF QRectF::translated(const QPointF &p) const
References QRectF, QPointF::x, QPointF::y.
void QRectF::moveTo(qreal x, qreal t)
void QRectF::moveTo(const QPointF &p)
References QPointF::x, QPointF::y.
void QRectF::setRect(qreal x, qreal y, qreal w, qreal h)
void QRectF::getRect(qreal *x, qreal *y, qreal *w, qreal *h) const
void QRectF::setCoords(qreal x1, qreal y1, qreal x2, qreal y2)
void QRectF::getCoords(qreal *x1, qreal *y1, qreal *x2, qreal *y2) const
void QRectF::adjust(qreal x1, qreal y1, qreal x2, qreal y2)
QRectF QRectF::adjusted(qreal x1, qreal y1, qreal x2, qreal y2) const
References QRectF.
QSizeF QRectF::size() const
qreal QRectF::width() const
qreal QRectF::height() const
void QRectF::setWidth(qreal w)
void QRectF::setHeight(qreal h)
void QRectF::setSize(const QSizeF &s)
References QSizeF::height, QSizeF::width.
QRectF QRectF::operator|(const QRectF &r) const
QRectF QRectF::operator &(const QRectF &r) const
QRectF & QRectF::operator|=(const QRectF &r)
QRectF & QRectF::operator &=(const QRectF &r)
bool QRectF::contains(const QPointF &p) const
Referenced by contains.
bool QRectF::contains(qreal x, qreal y) const
References contains.
bool QRectF::contains(const QRectF &r) const
QRectF QRectF::unite(const QRectF &r) const
QRectF QRectF::intersect(const QRectF &r) const
bool QRectF::intersects(const QRectF &r) const
QRect QRectF::toRect() const
qreal QRectF::xp
Referenced by operator!=, operator==.
qreal QRectF::yp
Referenced by operator!=, operator==.
qreal QRectF::w
Referenced by operator!=, operator==.
qreal QRectF::h
Referenced by operator!=, operator==.
Q_CORE_EXPORT bool operator==(const QRectF &, const QRectF &)
Q_CORE_EXPORT bool operator!=(const QRectF &, const QRectF &)