QSizeF
QSizeF::QSizeF()
Referenced by boundedTo, expandedTo, scale.
QSizeF::QSizeF(const QSize &sz)
QSizeF::QSizeF(qreal w, qreal h)
bool QSizeF::isNull() const
bool QSizeF::isEmpty() const
bool QSizeF::isValid() const
qreal QSizeF::width() const
Referenced by QRectF::QRectF, QRectF::setSize.
qreal QSizeF::height() const
Referenced by QRectF::QRectF, QRectF::setSize.
void QSizeF::setWidth(qreal w)
void QSizeF::setHeight(qreal h)
void QSizeF::transpose()
void QSizeF::scale(qreal w, qreal h, Qt::AspectRatioMode mode)
References QSizeF.
void QSizeF::scale(const QSizeF &s, Qt::AspectRatioMode mode)
QSizeF QSizeF::expandedTo(const QSizeF &) const
References ht, QSizeF, wd.
QSizeF QSizeF::boundedTo(const QSizeF &) const
References ht, QSizeF, wd.
qreal & QSizeF::rwidth()
qreal & QSizeF::rheight()
QSizeF & QSizeF::operator+=(const QSizeF &)
References ht, wd.
QSizeF & QSizeF::operator-=(const QSizeF &)
References ht, wd.
QSizeF & QSizeF::operator *=(qreal c)
QSizeF & QSizeF::operator/=(qreal c)
QSize QSizeF::toSize() const
qreal QSizeF::wd
Referenced by boundedTo, expandedTo, operator *, operator!=, operator+, operator+=, operator-, operator-=, operator/, operator==.
qreal QSizeF::ht
Referenced by boundedTo, expandedTo, operator *, operator!=, operator+, operator+=, operator-, operator-=, operator/, operator==.
bool operator==(const QSizeF &, const QSizeF &)
bool operator!=(const QSizeF &, const QSizeF &)
const QSizeF operator+(const QSizeF &, const QSizeF &)
const QSizeF operator-(const QSizeF &, const QSizeF &)
const QSizeF operator *(const QSizeF &, qreal)
const QSizeF operator *(qreal, const QSizeF &)
const QSizeF operator/(const QSizeF &, qreal)