QPointF
QPointF::QPointF()
QPointF::QPointF(const QPoint &p)
QPointF::QPointF(qreal xpos, qreal ypos)
bool QPointF::isNull() const
qreal QPointF::x() const
Referenced by QRectF::moveBottomLeft, QRectF::moveBottomRight, QRectF::moveCenter, QRectF::moveTo, QRectF::moveTopLeft, QRectF::moveTopRight, QRectF::QRectF, QRectF::setBottomLeft, QRectF::setBottomRight, QRectF::setTopLeft, QRectF::setTopRight, QRectF::translate, QRectF::translated.
qreal QPointF::y() const
Referenced by QRectF::moveBottomLeft, QRectF::moveBottomRight, QRectF::moveCenter, QRectF::moveTo, QRectF::moveTopLeft, QRectF::moveTopRight, QRectF::QRectF, QRectF::setBottomLeft, QRectF::setBottomRight, QRectF::setTopLeft, QRectF::setTopRight, QRectF::translate, QRectF::translated.
void QPointF::setX(qreal x)
void QPointF::setY(qreal y)
qreal & QPointF::rx()
qreal & QPointF::ry()
QPointF & QPointF::operator+=(const QPointF &p)
References xp, yp.
QPointF & QPointF::operator-=(const QPointF &p)
References xp, yp.
QPointF & QPointF::operator *=(qreal c)
QPointF & QPointF::operator/=(qreal c)
QPoint QPointF::toPoint() const
qreal QPointF::xp
Referenced by operator *, operator!=, operator+, operator+=, operator-, operator-=, operator/, operator==.
qreal QPointF::yp
Referenced by operator *, operator!=, operator+, operator+=, operator-, operator-=, operator/, operator==.
friend class QMatrix
bool operator==(const QPointF &, const QPointF &)
bool operator!=(const QPointF &, const QPointF &)
const QPointF operator+(const QPointF &, const QPointF &)
const QPointF operator-(const QPointF &, const QPointF &)
const QPointF operator *(qreal, const QPointF &)
const QPointF operator *(const QPointF &, qreal)
const QPointF operator-(const QPointF &)
const QPointF operator/(const QPointF &, qreal)