#! /usr/bin/env python

Import('env')

obj = env.kdeobj('program', env)
obj.target = 'kconfig_compiler'
obj.source = 'kconfig_compiler.cpp '
obj.libpaths = '.. ../../dcop'
# TODO - remove the "QT" once scons adds the right include pathes for non-gui projects
obj.uselib = 'QTCORE QTXML QT'
obj.instdir = env['KDEBIN']
obj.execute()


"""
SUBDIRS = tests
AM_CPPFLAGS = -I$(top_srcdir)/kdecore -I$(top_srcdir) $(all_includes)

bin_PROGRAMS = kconfig_compiler
kconfig_compiler_LDFLAGS = $(all_libraries) $(KDE_RPATH)
kconfig_compiler_LDADD = $(LIB_KDECORE)
kconfig_compiler_SOURCES = kconfig_compiler.cpp

check_PROGRAMS = example # autoexample
EXTRA_PROGRAMS = autoexample

example_LDFLAGS = $(all_libraries) $(KDE_RPATH)
example_LDADD = $(LIB_KDECORE)
example_SOURCES = example.cpp exampleprefs_base.cpp

autoexample_LDFLAGS = $(all_libraries) $(KDE_RPATH)
autoexample_LDADD = $(LIB_KDECORE) $(LIB_KDEUI)
autoexample_SOURCES = exampleprefs_base.cpp general_base.ui3 myoptions_base.ui3 \
  autoexample.cpp  

example.o exampleprefs_base.o: exampleprefs_base.h
# avoid running the below command in parallel
exampleprefs_base.cpp: exampleprefs_base.h
exampleprefs_base.cpp exampleprefs_base.h: $(srcdir)/example.kcfg kconfig_compiler $(srcdir)/exampleprefs_base.kcfgc
	./kconfig_compiler $(srcdir)/example.kcfg $(srcdir)/exampleprefs_base.kcfgc

METASOURCES = AUTO

CLEANFILES = exampleprefs_base.h exampleprefs_base.cpp

TESTFILES = test1.kcfg test2.kcfg test3.kcfg test4.kcfg test_dpointer.kcfg

check-local:
	for i in $(TESTFILES); \
	  do xmllint --noout --schema $(srcdir)/kcfg.xsd $(srcdir)/tests/$$i; \
	  perl $(top_srcdir)/kdecore/kconfig_compiler/checkkcfg.pl \
          $(top_srcdir)/kdecore/kconfig_compiler/tests/$$i; done
"""
 
