function list() {
    return [
                 { filePath: "../qmimedatabase/testfiles/test.bmp", mimeType: "image/bmp", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.cel", mimeType: "image/x-cel", xFail: "xxx" }
               , { filePath: "../qmimedatabase/testfiles/test.dcm", mimeType: "application/dicom", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.eps", mimeType: "image/x-eps", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/GammaChart.exr", mimeType: "image/x-exr", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.fit", mimeType: "image/fits", xFail: "x" }
               , { filePath: "../qmimedatabase/testfiles/test.fli", mimeType: "video/x-flic", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.gif", mimeType: "image/gif", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.ico", mimeType: "image/vnd.microsoft.icon", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.im1", mimeType: "image/x-sun-raster", xFail: "x" }
               , { filePath: "../qmimedatabase/testfiles/test.jp2", mimeType: "image/jp2", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.jpg", mimeType: "image/jpeg", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.jpc", mimeType: "image/jp2", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.mng", mimeType: "video/x-mng", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.pat", mimeType: "image/x-pat", xFail: "xxx" }
               , { filePath: "../qmimedatabase/testfiles/test.pbm", mimeType: "image/x-portable-bitmap", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.pcx", mimeType: "image/x-pcx", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.pgm", mimeType: "image/x-portable-graymap", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.pix", mimeType: "image/x-pix", xFail: "xxx" }
               , { filePath: "../qmimedatabase/testfiles/test.png", mimeType: "image/png", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.ppm", mimeType: "image/x-portable-pixmap", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test2.ppm", mimeType: "image/x-portable-pixmap", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.ps", mimeType: "application/postscript", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.psd", mimeType: "image/vnd.adobe.photoshop", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.sgi", mimeType: "image/x-sgi", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.tga", mimeType: "image/x-tga", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.tif", mimeType: "image/tiff", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.xbm", mimeType: "image/x-xbitmap", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.xcf", mimeType: "image/x-xcf", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.xpm", mimeType: "image/x-xpixmap", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.xwd", mimeType: "image/x-xwindowdump", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/2001_compression_overview.djvu", mimeType: "image/vnd.djvu", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.kdc", mimeType: "image/x-kodak-kdc", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/bathead.sk", mimeType: "image/x-skencil", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/jc-win.ani", mimeType: "application/x-navi-animation", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/aero_alt.cur", mimeType: "image/x-win-bitmap", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/mypaint.ora", mimeType: "image/openraster", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.xml.in", mimeType: "application/xml", xFail: "x" }
               , { filePath: "../qmimedatabase/testfiles/dia.shape", mimeType: "application/x-dia-shape", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/attachment.tif", mimeType: "image/jpeg", xFail: "xox" }
               , { filePath: "../qmimedatabase/testfiles/panasonic_lumix_dmc_fz38_05.rw2", mimeType: "image/x-panasonic-raw2", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/ooo-6.0.doc", mimeType: "application/msword", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/ooo-95.doc", mimeType: "application/msword", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/ooo.doc", mimeType: "application/msword", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/ooo.rtf", mimeType: "application/rtf", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/ooo.sdw", mimeType: "application/vnd.stardivision.writer", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/ooo.stw", mimeType: "application/vnd.sun.xml.writer.template", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/ooo.sxw", mimeType: "application/vnd.sun.xml.writer", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/ooo.vor", mimeType: "application/vnd.stardivision.writer", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/ooo-xp.doc", mimeType: "application/msword", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/office.doc", mimeType: "application/msword", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/ooo-test.odg", mimeType: "application/vnd.oasis.opendocument.graphics", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/ooo-test.odp", mimeType: "application/vnd.oasis.opendocument.presentation", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/ooo-test.ods", mimeType: "application/vnd.oasis.opendocument.spreadsheet", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/ooo-test.odt", mimeType: "application/vnd.oasis.opendocument.text", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/ooo-test.fodg", mimeType: "application/vnd.oasis.opendocument.graphics-flat-xml", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/ooo-test.fodp", mimeType: "application/vnd.oasis.opendocument.presentation-flat-xml", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/ooo-test.fods", mimeType: "application/vnd.oasis.opendocument.spreadsheet-flat-xml", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/ooo-test.fodt", mimeType: "application/vnd.oasis.opendocument.text-flat-xml", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/foo.doc", mimeType: "application/msword", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test-template.dot", mimeType: "application/msword-template", xFail: "oxx" }
               , { filePath: "../qmimedatabase/testfiles/ocf10-20060911.epub", mimeType: "application/epub+zip", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.wps", mimeType: "application/vnd.ms-works", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/sample.docx", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", xFail: "oxo" }
               , { filePath: "../qmimedatabase/testfiles/sample.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", xFail: "oxo" }
               , { filePath: "../qmimedatabase/testfiles/sample.pptx", mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation", xFail: "oxo" }
               , { filePath: "../qmimedatabase/testfiles/sample.ppsx", mimeType: "application/vnd.openxmlformats-officedocument.presentationml.slideshow", xFail: "oxo" }
               , { filePath: "../qmimedatabase/testfiles/pocket-word.psw", mimeType: "application/x-pocket-word", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/aportis.pdb", mimeType: "application/x-aportisdoc", xFail: "oox" }
               , { filePath: "../qmimedatabase/testfiles/internet.ez", mimeType: "application/andrew-inset", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/Anaphraseus-1.21-beta.oxt", mimeType: "application/vnd.openofficeorg.extension", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/petite-ouverture-a-danser.ly", mimeType: "text/x-lilypond", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/sqlite2.kexi", mimeType: "application/x-kexiproject-sqlite2", xFail: "oxx" }
               , { filePath: "../qmimedatabase/testfiles/sqlite3.kexi", mimeType: "application/x-kexiproject-sqlite3", xFail: "xxo" }
               , { filePath: "../qmimedatabase/testfiles/combined.karbon", mimeType: "application/x-karbon", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/Empty.chrt", mimeType: "application/x-kchart", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/layersupdatesignals.flw", mimeType: "application/x-kivio", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/Presentation.kpt", mimeType: "application/x-kpresenter", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/testcases.ksp", mimeType: "application/x-kspread", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test-kounavail2.kwd", mimeType: "application/x-kword", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/white_640x480.kra", mimeType: "application/x-krita", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/stream.nsc", mimeType: "application/x-netshow-channel", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/stream.sdp", mimeType: "application/sdp", xFail: "x" }
               , { filePath: "../qmimedatabase/testfiles/playlist.asx", mimeType: "audio/x-ms-asx", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/feed.rss", mimeType: "application/rss+xml", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/feed2", mimeType: "application/rss+xml", xFail: "x" }
               , { filePath: "../qmimedatabase/testfiles/560051.xml", mimeType: "application/rss+xml", xFail: "xxx" }
               , { filePath: "../qmimedatabase/testfiles/feed.atom", mimeType: "application/atom+xml", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/feeds.opml", mimeType: "text/x-opml+xml", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/subtitle.srt", mimeType: "application/x-subrip", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/subtitle.smi", mimeType: "application/x-sami", xFail: "x" }
               , { filePath: "../qmimedatabase/testfiles/subtitle-microdvd.sub", mimeType: "text/x-microdvd", xFail: "oox" }
               , { filePath: "../qmimedatabase/testfiles/subtitle-mpsub.sub", mimeType: "text/x-mpsub", xFail: "xox" }
               , { filePath: "../qmimedatabase/testfiles/subtitle.ssa", mimeType: "text/x-ssa", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/subtitle-subviewer.sub", mimeType: "text/x-subviewer", xFail: "x" }
               , { filePath: "../qmimedatabase/testfiles/ringtone.ime", mimeType: "text/x-iMelody", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/ringtone.mmf", mimeType: "application/x-smaf", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/playlist.mrl", mimeType: "text/x-mrml", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/hbo-playlist.qtl", mimeType: "application/x-quicktime-media-link", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/playlist.wpl", mimeType: "application/vnd.ms-wpl", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.flac", mimeType: "audio/flac", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/live-streaming.m3u", mimeType: "application/vnd.apple.mpegurl", xFail: "x" }
               , { filePath: "../qmimedatabase/testfiles/all_w.m3u8", mimeType: "application/vnd.apple.mpegurl", xFail: "x" }
               , { filePath: "../qmimedatabase/testfiles/text-iso8859-15.txt", mimeType: "text/plain", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/text-utf8.txt", mimeType: "text/plain", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.tex", mimeType: "text/x-tex", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/registry.reg", mimeType: "text/x-ms-regedit", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/registry-nt.reg", mimeType: "text/x-ms-regedit", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.ext,v", mimeType: "text/plain", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.fl", mimeType: "application/x-fluid", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/helloworld.java", mimeType: "text/x-java", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/survey.js", mimeType: "application/javascript", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.cs", mimeType: "text/x-csharp", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.dot", mimeType: "text/vnd.graphviz", xFail: "x" }
               , { filePath: "../qmimedatabase/testfiles/test.vala", mimeType: "text/x-vala", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.ooc", mimeType: "text/x-ooc", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.mof", mimeType: "text/x-mof", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test-cdda.toc", mimeType: "application/x-cdrdao-toc", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test-cdrom.toc", mimeType: "application/x-cdrdao-toc", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.iptables", mimeType: "text/x-iptables", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test-vpn.pcf", mimeType: "application/x-cisco-vpn-settings", xFail: "x" }
               , { filePath: "../qmimedatabase/testfiles/test.php", mimeType: "application/x-php", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/evolution.eml", mimeType: "application/mbox", xFail: "xox" }
               , { filePath: "../qmimedatabase/testfiles/tb-from-sentbox.eml", mimeType: "message/rfc822", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/tb-saved.eml", mimeType: "message/rfc822", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.url", mimeType: "application/x-mswinurl", xFail: "xox" }
               , { filePath: "../qmimedatabase/testfiles/test.d", mimeType: "text/x-dsrc", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.v", mimeType: "text/x-verilog", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.sv", mimeType: "text/x-svsrc", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.svh", mimeType: "text/x-svhdr", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.manifest", mimeType: "text/cache-manifest", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.yaml", mimeType: "application/x-yaml", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/mysum.m", mimeType: "text/x-matlab", xFail: "x" }
               , { filePath: "../qmimedatabase/testfiles/isdir.m", mimeType: "text/x-matlab", xFail: "x" }
               , { filePath: "../qmimedatabase/testfiles/bibtex.bib", mimeType: "text/x-bibtex", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/simple-obj-c.m", mimeType: "text/x-objcsrc", xFail: "oox" }
               , { filePath: "../qmimedatabase/testfiles/ssh-public-key.txt", mimeType: "text/plain", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.vcf", mimeType: "text/directory", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.go", mimeType: "text/x-go", xFail: "oxo" }
               , { filePath: "../qmimedatabase/testfiles/test.ttx", mimeType: "application/x-font-ttx", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/project.glade", mimeType: "application/x-glade", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/ISOcyr1.ent", mimeType: "application/xml-external-parsed-entity", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.metalink", mimeType: "application/metalink+xml", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.mml", mimeType: "application/mathml+xml", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/linguist.ts", mimeType: "text/vnd.trolltech.linguist", xFail: "oox" }
               , { filePath: "../qmimedatabase/testfiles/test.xsl", mimeType: "application/xslt+xml", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.cbl", mimeType: "text/x-cobol", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.alz", mimeType: "application/x-alz", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.class", mimeType: "application/x-java", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/hello.pack", mimeType: "application/x-java-pack200", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.msi", mimeType: "application/x-msi", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/archive.7z", mimeType: "application/x-7z-compressed", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/comics.cb7", mimeType: "application/x-cb7", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/archive.tar", mimeType: "application/x-tar", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/comics.cbt", mimeType: "application/x-cbt", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/copying.cab", mimeType: "application/vnd.ms-cab-compressed", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/archive.gz", mimeType: "application/x-gzip", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/archive.tar.gz", mimeType: "application/x-compressed-tar", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/good-1-delta-lzma2.tiff.xz", mimeType: "application/x-xz", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/spinboxes-0.1.1-Linux.tar.xz", mimeType: "application/x-xz-compressed-tar", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.lz", mimeType: "application/x-lzip", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.lzo", mimeType: "application/x-lzop", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/archive.lrz", mimeType: "application/x-lrzip", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/fuji.themepack", mimeType: "application/x-windows-themepack", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/helloworld.xpi", mimeType: "application/x-xpinstall", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.wim", mimeType: "application/x-ms-wim", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.wav", mimeType: "audio/x-wav", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.avi", mimeType: "video/x-msvideo", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/hereyes_remake.mo3", mimeType: "audio/x-mo3", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/ccfilm.axv", mimeType: "video/annodex", xFail: "oxo" }
               , { filePath: "../qmimedatabase/testfiles/ccfilm.axv", mimeType: "application/annodex", xFail: "xxx" }
               , { filePath: "../qmimedatabase/testfiles/test.ogg", mimeType: "audio/ogg", xFail: "oxx" }
               , { filePath: "../qmimedatabase/testfiles/test.ogg", mimeType: "audio/x-vorbis+ogg", xFail: "x" }
               , { filePath: "../qmimedatabase/testfiles/msg0001.gsm", mimeType: "audio/x-gsm", xFail: "oxo" }
               , { filePath: "../qmimedatabase/testfiles/small_wav.mxf", mimeType: "application/mxf", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/Elephants_Dream-360p-Stereo.webm", mimeType: "video/webm", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/settopbox.ts", mimeType: "video/mp2t", xFail: "xx" }
               , { filePath: "../qmimedatabase/testfiles/bbc.ram", mimeType: "application/ram", xFail: "oxo" }
               , { filePath: "../qmimedatabase/testfiles/bbc.ram", mimeType: "application/vnd.rn-realmedia", xFail: "xox" }
               , { filePath: "../qmimedatabase/testfiles/text.pdf", mimeType: "application/pdf", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/README.pdf", mimeType: "application/pdf", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/testcase.is-really-a-pdf", mimeType: "application/pdf", xFail: "xo" }
               , { filePath: "../qmimedatabase/testfiles/test.pdf.xz", mimeType: "application/x-xzpdf", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/Makefile", mimeType: "text/x-makefile", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/Makefile.gnu", mimeType: "text/x-makefile", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/googleearth.kml", mimeType: "application/vnd.google-earth.kml+xml", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.gnd", mimeType: "application/gnunet-directory", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/text.ps", mimeType: "application/postscript", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/text.ps.gz", mimeType: "application/x-gzpostscript", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/text.PS.gz", mimeType: "application/x-gzpostscript", xFail: "oxo" }
               , { filePath: "../qmimedatabase/testfiles/test.cmake", mimeType: "text/x-cmake", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/bluerect.mdi", mimeType: "image/vnd.ms-modi", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/Stallman_Richard_-_The_GNU_Manifesto.fb2", mimeType: "application/x-fictionbook+xml", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.p7b", mimeType: "application/x-pkcs7-certificates", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.pkipath", mimeType: "application/pkix-pkipath", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/test.jks", mimeType: "application/x-java-keystore", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.jceks", mimeType: "application/x-java-jce-keystore", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.sav", mimeType: "application/x-spss-sav", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.por", mimeType: "application/x-spss-por", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/core", mimeType: "application/x-core", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/bluish.icc", mimeType: "application/vnd.iccprofile", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.it87", mimeType: "application/x-it87", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.hdf4", mimeType: "application/x-hdf", xFail: "" }
               , { filePath: "../qmimedatabase/testfiles/test.h5", mimeType: "application/x-hdf", xFail: "ox" }
               , { filePath: "../qmimedatabase/testfiles/without_an_extension", mimeType: "image/vnd.djvu", xFail: "x" }
           ]
}
