include(CheckIncludeFile)
include(CheckIncludeFiles)
include(CheckSymbolExists)
include(CheckCXXSymbolExists)
include(CheckStructMember)
include(CheckFunctionExists)
include(CheckLibraryExists)
include(CheckPrototypeExists)

check_include_files(sys/time.h    HAVE_SYS_TIME_H)
check_include_files(time.h        HAVE_TIME_H)
check_include_files(alloca.h      HAVE_ALLOCA_H)
check_include_files(string.h      HAVE_STRING_H)
check_include_files(strings.h     HAVE_STRINGS_H)
check_include_files(stdlib.h      HAVE_STDLIB_H)
check_include_files(sys/select.h  HAVE_SYS_SELECT_H)
check_include_files(errno.h       HAVE_ERRNO_H)
check_include_files(sys/time.h    HAVE_SYS_TIME_H)
check_include_files(sys/time.h    TIME_WITH_SYS_TIME)
check_include_files(time.h        HAVE_TIME_H)

check_struct_member(dirent d_type dirent.h HAVE_DIRENT_D_TYPE)

check_prototype_exists(strlcpy string.h             HAVE_STRLCPY_PROTO)
check_prototype_exists(setenv stdlib.h              HAVE_SETENV_PROTO)
check_prototype_exists(initgroups "unistd.h;sys/types.h;unistd.h;grp.h" HAVE_INITGROUPS_PROTO)
check_symbol_exists(getgrouplist    "unistd.h;grp.h"           HAVE_GETGROUPLIST)
