#! /usr/bin/env python

Import('env')

env.subdirs('kconfig_compiler tests')
	
core_files="""
libintl.cpp kapplication.cpp kauthorized.cpp
kdebug.cpp kconfigbase.cpp kconfig.cpp  ksimpleconfig.cpp
kconfigbackend.cpp kmanagerselection.cpp kdesktopfile.cpp
kstandarddirs.cpp kprocess.cpp kprocctrl.cpp
klocale.cpp krfcdate.cpp kiconeffect.cpp kicontheme.cpp
kiconloader.cpp krootprop.cpp kcharsets.cpp
kckey.cpp kshortcut.cpp kdatetime.cpp
kkeynative_x11.cpp 
kkeyserver_x11.cpp
kaccelaction.cpp kshortcutmenu.cpp kaccelbase.cpp kaccel.cpp
kglobalaccel.cpp kstdaccel.cpp kshortcutlist.cpp
kcrash.cpp kurl.cpp kglobal.cpp kglobalsettings.cpp
kallocator.cpp kvmallocator.cpp kmimesourcefactory.cpp
kinstance.cpp kpalette.cpp kipc.cpp klibloader.cpp ktempfile.cpp
kuniqueapplication.cpp kacceleratormanager.cpp
ksavefile.cpp krandomsequence.cpp kstringhandler.cpp kcompletion.cpp
kcmdlineargs.cpp kaboutdata.cpp kcompletionbase.cpp knotifyclient.cpp
kaudioplayer.cpp kdcoppropertyproxy.cpp
kprocio.cpp krandom.cpp
kpixmapprovider.cpp ktoolinvocation.cpp
kcodecs.cpp fakes.c 
ksycoca.cpp ksycocadict.cpp ksycocafactory.cpp
kxmessages.cpp kstartupinfo.cpp kcatalog.cpp
kstaticdeleter.cpp kappdcopiface.cpp
kclipboard.cpp kcheckaccelerators.cpp
kdeversion.cpp kdebugdcopiface.cpp
kcalendarsystem.cpp kcalendarsystemgregorian.cpp
kcalendarsystemhijri.cpp kcalendarsystemhebrew.cpp
kcalendarsystemfactory.cpp kmacroexpander.cpp kidna.cpp
ktempdir.cpp kshell.cpp kmountpoint.cpp kcalendarsystemjalali.cpp
kprotocolinfo_kdecore.cpp kprotocolinfofactory.cpp kxerrorhandler.cpp
kuser.cpp kconfigskeleton.cpp klockfile.cpp 
ktimezones.cpp ktzfiletimezone.cpp kmath.cpp
kfilterbase.cpp kfilterdev.cpp kgzipfilter.cpp
ksycoca.skel kappdcopiface.skel kdebugdcopiface.skel
network/kresolver.cpp
network/kresolvermanager.cpp
network/kresolverworkerbase.cpp
network/ksocketaddress.cpp
network/kresolverstandardworkers.cpp
network/kreverseresolver.cpp
network/ksocketbase.cpp
network/ksocketdevice.cpp
network/kclientsocketbase.cpp
network/kstreamsocket.cpp
network/kbufferedsocket.cpp
network/ksocketbuffer.cpp
network/kserversocket.cpp
"""

if not env['WINDOWS']:
	core_files +="""
kglobalaccel_x11.cpp 
ktoolinvocation_x11.cpp 
ksocks.cpp netsupp.cpp netwm.cpp kpty.cpp
kwin.cpp kwinmodule.cpp 
network/kdatagramsocket.cpp
network/khttpproxysocketdevice.cpp
network/ksockssocketdevice.cpp
network/knetworkinterface.cpp
"""
else:
	core_files +="""
netsupp_win32.cpp
kapplication_win.cpp 
kglobalaccel_win.cpp
ktoolinvocation_win.cpp 
"""

install_headers="""
kconfig.h kconfigskeleton.h
kconfigdata.h ksimpleconfig.h
kconfigbase.h kdesktopfile.h kurl.h kaboutdata.h
kcmdlineargs.h kconfigbackend.h kapplication.h kauthorized.h ktoolinvocation.h
kuniqueapplication.h kcharsets.h kdeversion.h kpty.h kprocess.h
kprocctrl.h klocale.h kicontheme.h kiconloader.h kdebug.h
kwinmodule.h kwin.h krootprop.h kshortcut.h kkeynative.h kaccel.h
kglobalaccel.h kstdaccel.h kshortcutlist.h kcatalog.h kcompletion.h
kstringhandler.h kstandarddirs.h kglobal.h kglobalsettings.h ksharedptr.h
kallocator.h kvmallocator.h kcrash.h krfcdate.h kdatetime.h
kinstance.h kpalette.h kipc.h klibloader.h ktempfile.h ksavefile.h
krandomsequence.h knotifyclient.h kiconeffect.h
kaudioplayer.h kdcoppropertyproxy.h netwm.h kacceleratormanager.h
netwm_def.h kpixmapprovider.h kstaticdeleter.h kprocio.h kasyncio.h krandom.h
kbufferedio.h kmimesourcefactory.h kcodecs.h ksocks.h
ksycoca.h ksycocaentry.h ksycocatype.h kxmessages.h kstartupinfo.h
kgenericfactory.h kgenericfactory.tcc
ktypelist.h ksortablevaluelist.h kclipboard.h
kcalendarsystem.h kcalendarsystemfactory.h kmacroexpander.h
kmanagerselection.h kmountpoint.h kuser.h klockfile.h
kidna.h ktempdir.h kshell.h fixx11h.h kxerrorhandler.h
kde_file.h ktimezones.h ktzfiletimezone.h kmdcodec.h kmath.h
"""

# not finished (ita)
for i in "kacceleratormanager_private.h kaccelprivate.h".split():
	env.Moc(i)

obj = env.kdeobj('shlib', env)
obj.vnum     = '6.0.2'
obj.target   = 'kdecore'
obj.source   = core_files
#FIXME: DL is required for ../libltdl/libltdlc.a, although it is specified
#when compiling libltdlc.a, we still need it here. We need a better static
#library support (liucougar)
obj.uselib   = 'QT QTCORE QTGUI QT3SUPPORT KDE4 LIBIDN DL'
obj.libpaths = '../libltdl ../dcop'
obj.libs     = 'ltdlc DCOP '
obj.iskdelib = 1
obj.includes = 'network'
obj.ccflags += ' -DMAKE_KDECORE_LIB ' # todo: will be generated automatically
if env['WINDOWS']:
	obj.libpaths += ' ../win '
	obj.includes += ' ../win/3rdparty/zlib '
	obj.libs     += ' kdewin32 ws2_32 user32 '
	obj.ccflags += ' -DKIO_EXPORT= '

if env['MAC']:
	obj.libs += ' resolv z '
	obj.frameworks += ' Carbon '

if env.has_key("CACHED_LIBBZ2") and env['CACHED_LIBBZ2']:
	obj.uselib += ' LIBBZ2 '
	obj.source += ' kbzip2filter.cpp'

if env.has_key("CACHED_AGG") and env['CACHED_AGG']:
	obj.uselib += ' QTXML AGG Z'
	obj.source   += ' svgicons/ksvgiconengine.cpp svgicons/ksvgiconpainter.cpp'
obj.execute()


env.bksys_insttype( 'KDEINCLUDE', '', install_headers )

