#! /usr/bin/env python
Import('env')


check_PROGRAMS = """
#ksycocatest getalltest kruntest ktartest kziptest
kioslavetest kdirwatchtest speed kurifiltertest
kdefaultprogresstest kmimemagictest
kiopassdlgtest kscantest kdirlistertest
previewtest kionetrctest kdcopcheck metatest
kmimefromext kpropsdlgtest kmfitest dataprotocoltest
kprotocolinfotest ksycocaupdatetest netaccesstest jobtest
kurlcompletiontest kmimetypetest kbookmarktest kacltest
"""

for appname in check_PROGRAMS.split():
	if appname[:1] == '#':
		if env['WINDOWS']:
			continue
		else:
			appname = appname[1:]
			
	obj = env.kdeobj('program', env)
	obj.vnum     = '6.0.2'
	obj.target   = appname
	obj.source   = appname + '.cpp'
	obj.uselib   = 'QT QTCORE QTGUI QTXML QT3SUPPORT KDE4 QTEST'
	obj.libpaths = '.. ../../kdeui ../../kdecore ../../kdesu ../../dcop ../../qttestlib #/kio ../../kdefx ../../kwallet/client'
	obj.libs     = 'kio kdeui kdecore DCOP kdefx kwalletclient'
	obj.includes = '. .. ../kssl ../bookmarks ../kfile ../kio ../misc ../../kdecore ../../kdefx ../../qttestlib '
	if env['WINDOWS']:
		obj.libs     += ' ws2_32'
	else:
		obj.libs     += ' kdesu'
		
	obj.execute()


