#define CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}"
#define LIBEXEC_INSTALL_DIR "${LIBEXEC_INSTALL_DIR}"
#define LIB_INSTALL_DIR "${LIB_INSTALL_DIR}"
#define KCONF_UPDATE_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}"
