#!/usr/bin/perl -w

use Shell qw(mv cp mkdir rm) ;
use File::Find;
use Cwd;

$origPwd = `pwd`;
chomp $origPwd;

if (@ARGV && $ARGV[0] eq 'update') {
  @packages = `ls -1d debian/*/DEBIAN`;
  foreach $dir (@packages) {
    chomp $dir;
    next if (! -d $dir);
    foreach $file (qw{postinst postrm preinst prerm}) {  
      next if (! -f "$dir/$file");
      $found = 0;
      open(IN, "$dir/$file");
      open(OUT, ">/tmp/kde.dpkg");
      while (<IN>) { 
	if (/^#KDEHELPER#/) {
	    $found = 1;
	    if (-d $dir . "/../usr/lib/mime/packages") {
	      if ($file eq 'postinst') {
		print OUT "# added by kderules\n";
		print OUT 'case "$1" in' . "\n";
		print OUT "  configure)\n";
		print OUT "    if [ -x /usr/sbin/update-mime ]; then\n";
		print OUT "       update-mime\n";
		print OUT "    fi\n";
		print OUT "  ;;\n";
		print OUT "esac\n";
	      } elsif ($file eq 'postrm') {
		print OUT "# added by kderules\n";
		print OUT 'case "$1" in' . "\n";
		print OUT "   remove|purge)\n";
		print OUT "    if [ -x /usr/sbin/update-mime ]; then\n";
		print OUT "       update-mime\n";
		print OUT "    fi\n";
		print OUT "  ;;\n";
		print OUT "esac\n";
	      }
	    }
	    
	    next;
	  }
	print OUT $_;
      }
      
      close IN;
      close OUT;

      if ($found == 0) {
	rm("/tmp/kde.dpkg");
      } else {
	mv("/tmp/kde.dpkg", "$dir/$file");
	chown("root.root","dir/$file");
	chmod(0755,"$dir/$file");   
      }
    }
  }
  exit;
}

if (@ARGV && $ARGV[0] eq 'echodirs') {
  #	kde_htmldir=/usr/doc/kde/HTML \
  #	kde_appsdir=/usr/share/applnk \
  #	kde_icondir=/usr/share/icons \
  #	kde_sounddir=/usr/share/sounds \
  #	kde_datadir=/usr/share/apps \
  #	kde_locale=/usr/share/locale \
  #	kde_cgidir=/usr/lib/cgi-bin \
  #	kde_confdir=/etc/kde \
  #	kde_mimedir=/usr/share/mimelnk \
  #	kde_toolbardir=/usr/share/toolbar \
  #	kde_wallpaperdir=/usr/share/wallpaper \
  #	kde_bindir=/usr/bin \
  #	kde_partsdir=/usr/lib/parts 
  print STDOUT "export kde_htmldir=/opt/kde2pre/share/doc/HTML\n";
  print STDOUT "export kde_appsdir=/opt/kde2pre/share/applnk\n";
  print STDOUT "export kde_icondir=/opt/kde2pre/share/icons\n";
  print STDOUT "export kde_sounddir=/opt/kde2pre/share/sounds\n";
  print STDOUT "export kde_datadir=/opt/kde2pre/share/apps\n";
  print STDOUT "export kde_locale=/opt/kde2pre/share/locale\n";
  print STDOUT "export kde_cgidir=/opt/kde2pre/cgi-bin\n";
  print STDOUT "export kde_confdir=/opt/kde2pre/share/config\n";
  print STDOUT "export kde_mimedir=/opt/kde2pre/share/mimelnk\n";
  print STDOUT "export kde_toolbardir=/opt/kde2pre/share/toolbar\n";
  print STDOUT "export kde_wallpaperdir=/opt/kde2pre/share/wallpapers\n";
  print STDOUT "export kde_bindir=/opt/kde2pre/bin\n";
  print STDOUT "export kde_partsdir=/opt/kde2pre/parts\n";
  print STDOUT "export includedir=/opt/kde2pre/include\n";
  print STDOUT "export libdir=/opt/kde2pre/lib\n";
  print STDOUT "export QTINC=/usr/lib/qt2beta/include\n";
  print STDOUT "export QTLIB=/usr/lib/qt2beta/lib\n";
  print STDOUT "export MOC=/usr/lib/qt2beta/bin/moc\n";
  print STDOUT "export MICODIR=/usr\n";
  print STDOUT "export PYTHONDIR=/usr\n";

  exit
}

if (@ARGV && $ARGV[0]) {  
  $package = $ARGV[0];
} else {
  open(CHANGELOG,"debian/changelog") 
	or die "can't read debian/changelog : $!\n";
  $_ = <CHANGELOG>;
  close(CHANGELOG);
  /^(.*) \((.*)\) /;
  $package = $1;
}

# Find documentation and install it
sub docwanted {
        local $dir = $File::Find::dir;
        $dir =~ s/^$origPwd//;
	if ($dir =~ /debian/) { return 0 ; }
	/debian/ or /INSTALL/ and return 0 ;
	/COPYING/ and return ;
	if ( (! /CVS/ )
	and ( /^[A-Z]*$/ or /README/ or /ChangeLog/ or /lsm$/ or /SWALLOW/
	or /TODO/ or /kdedoc/ or /Header/ or /Documentation/ or /Tutorial/ ) )
	{	
		if ($dir) {
		  $_ = "$dir/$_";
		  $_ =~ s/^\///;
		}
		push @docs, "$_" ;
	}
}

$pwd = cwd();

find(\&docwanted, $pwd);
if ($pwd =~ ?^(.*/)build_([^/]*)$?) {
  $pwd = $1 . $2;
  if (-d $pwd) {
     find(\&docwanted, $pwd);
  }
}

if (! -d "debian/tmp/usr/doc/$package") {
	mkdir("-p", "debian/tmp/usr/doc/$package") ;
}

if (! -d "debian/tmp/usr/share/pixmaps") {
       mkdir("-p", "debian/tmp/usr/share/pixmaps");
}

if (@docs) {
       chdir($origPwd);
       cp( "-aP", @docs, "debian/tmp/usr/doc/$package") ;
       if (-f "debian/tmp/usr/doc/$package/ChangeLog") {
	  mv("debian/tmp/usr/doc/$package/ChangeLog", 
		"debian/tmp/usr/doc/$package/changelog");
	}
}

# Create debian/menu files

sub finddesktop {
	/\.desktop$/ && push @lnkfiles, "$File::Find::dir/$_" ;
}

if (-d "debian/tmp/opt/kde2pre/share/applnk") {
	find(\&finddesktop,"debian/tmp/opt/kde2pre/share/applnk");
}

if (-e "debian/menu.in") {
	open MENUIN, "debian/menu.in" ;
	while (<MENUIN>) {
		chop ;
		($prog,$type,$sect) = split / /;
		$type{$prog}=$type;
		$sect{$prog}=$sect;
	}
	close MENUIN;
}

open MENU, ">debian/menu" or die "can't open debian/menu : $!\n";
open MIME, ">debian/mailcap" or die "can't open debian/mailcap : $!\n";

foreach $file (@lnkfiles) {
	open DESKTOP, $file;
	undef %desktop;
	while (<DESKTOP>) {
		/^#/ && next ;
		/^\[Desktop Entry\]/ && next ;
		/^\[KDE Desktop Entry\]/ && next ;
		/^\s*$/ && next ;
		chop ;
		($what,$value) = split /=/ ;
		$desktop{ucfirst lc $what}=$value;
	}
	close DESKTOP;
	if (defined $desktop{"Type"}) {
		if ($desktop{"Type"} ne "Application" ) {
			print STDERR "Type is not Application : $file !\n" ;
			next ;
		}
	} else {
		print STDERR "has no Type= defaults to Application : $file !\n" ;
	}
	if (! defined $desktop{"Exec"}) {
		print STDERR "has no Exec= : $file !\n" ;
		next ;
	}

	if (defined $desktop{"Mimetype"} && ! $desktop{"Mimetype"} eq '') {

  	   $execline = $desktop{"Exec"};
	   $execline =~ s/%f/%s/;
	   $execline =~ s/%c/$desktop{"Name"}/;
	   $execline =~ s/%i//;
	   $execline =~ s/%m//;
	   $execline =~ s/%u/%s/;
	   $mimeline = $desktop{"Mimetype"};
	   @mimetypes = split(';', $mimeline);
	   foreach $mimetype (@mimetypes) {
	   print MIME "$mimetype; $execline;" . 'test=test "$DISPLAY" != ""; priority=7' . "\n";
	   }

	}

	($prog,)=split / /, $desktop{"Exec"} ;
	if (! defined($type{$prog})) {
		open MENUIN, ">>debian/menu.in" ;
		print MENUIN "$prog x11 SECTION\n";
		close MENUIN;
		next ;
	}
	if ($sect{$prog} eq "NONE") { next ; }
	$icon="";
	if (not defined $desktop{"Name"}) {
		print STDERR "No Name : $package $desktop\n";
		next ;
	}
	if (defined $desktop{"Icon"}) {
   	        $icon=$desktop{"Icon"} ;
		if (! -f "debian/tmp/opt/kde2pre/share/icons/$icon" ) {
                   $icon="";
	        } else {
	          system("/usr/bin/X11/convert -map /usr/X11R6/include/X11/pixmaps/cmap.xpm debian/tmp/opt/kde2pre/share/icons/$icon debian/tmp/usr/share/pixmaps/$icon");
	  	  $icon="/usr/share/pixmaps/" . $icon ;
               }
	}
	($desktop=$file) =~ s/^.*tmp// ;
	print MENU "?package($package):\\\n" ;
	print MENU "	needs=$type{$prog}\\\n" ;
	print MENU "	section=$sect{$prog}\\\n" ;
	print MENU "	title=\"$desktop{Name}\"\\\n" ;
	print MENU "	command=$prog\\\n" ;
	print MENU "	icon=\"$icon\"\n\n" ;

}

if (-e "debian/menu.add") {
	open MENUADD, "debian/menu.add" ;
	while (<MENUADD>) {
		print MENU $_ ;
	}
	close MENUADD;
}

close MENU;

if (-z "debian/menu") {
	rm("debian/menu");
}

close MIME;

if (-z "debian/mailcap") {
  rm("debian/mailcap");
} else {
  mkdir("-p", "debian/tmp/usr/lib/mime/packages");
  cp("debian/mailcap", "debian/tmp/usr/lib/mime/packages/$package");
}

