#! /bin/sh
# postinst script for kdelibs
#
# see: dh_installdeb(1)

set -e
case "$1" in
    configure)
      ldconfig
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#
#KDEHELPER#

exit 0
