#! /bin/sh
# postinst script for kdelibs
#
# see: dh_installdeb(1)

set -e
case "$1" in
    configure)
      /sbin/ldconfig
      echo -n "Verifying HTML directory is configured properly:  "
      if [ -e /usr/share/doc/kde/HTML/default -a ! -L /usr/share/doc/kde/HTML/default ]; then
        mv /usr/share/doc/kde/HTML/default/* /usr/share/doc/kde/HTML/en >/dev/null 2>&1
        rm -rf /usr/share/doc/kde/HTML/default > /dev/null 2>&1
        ln -s /usr/share/doc/kde/HTML/en /usr/share/doc/kde/HTML/default > /dev/null 2>&1
        echo "It wasn't, I fixed it"
      else
        echo "Looks ok"
      fi
      echo -n "Verifying config link is configured properly:  "
      if [ -e /usr/share/config -a ! -L /usr/share/config ]; then
        mv /usr/share/config/* /etc/kde2/ >/dev/null 2>&1
        rm -rf /usr/share/config > /dev/null 2>&1
        ln -s /etc/kde2 /usr/share/config > /dev/null 2>&1
        echo "It wasn't, I fixed it"
      else
        echo "Looks ok" 
      fi
      echo -n "Verifying services link is configured properly:  "
      if [ -e /etc/kde2/services -a ! -L /etc/kde2/services ]; then
        rm -rf /etc/kde2/services > /dev/null 2>&1
        ln -s /usr/share/services /etc/kde2/services > /dev/null 2>&1
        echo "It wasn't, I fixed it"
      else
        echo "Looks ok"
      fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#
#KDEHELPER#

exit 0
