/* ANSI-C code produced by gperf version 2.7.2 */
/* Command-line: gperf -a -L ANSI-C -E -C -c -o -t -k '*' -NfindProp -Hhash_prop -Wwordlist_prop -D -s 2 cssproperties.gperf  */
/* This file is automatically generated from cssproperties.in by makeprop, do not edit */
/* Copyright 1999 W. Bastian */
#include "cssproperties.h"
struct props {
    const char *name;
    int id;
};
/* maximum key range = 893, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash_prop (register const char *str, register unsigned int len)
{
  static const unsigned short asso_values[] =
    {
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898,   0, 898, 898, 898, 898,
      898,   5, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898,  25,  15,   0,
        0,   0,  30,   0,  10,   0, 898, 100,   0,  80,
      180,   0,  65,   5,   0, 165,   0,   5,  70, 150,
        5,  95,  10, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898, 898, 898, 898, 898,
      898, 898, 898, 898, 898, 898
    };
  register int hval = len;

  switch (hval)
    {
      default:
      case 32:
        hval += asso_values[(unsigned char)str[31]];
      case 31:
        hval += asso_values[(unsigned char)str[30]];
      case 30:
        hval += asso_values[(unsigned char)str[29]];
      case 29:
        hval += asso_values[(unsigned char)str[28]];
      case 28:
        hval += asso_values[(unsigned char)str[27]];
      case 27:
        hval += asso_values[(unsigned char)str[26]];
      case 26:
        hval += asso_values[(unsigned char)str[25]];
      case 25:
        hval += asso_values[(unsigned char)str[24]];
      case 24:
        hval += asso_values[(unsigned char)str[23]];
      case 23:
        hval += asso_values[(unsigned char)str[22]];
      case 22:
        hval += asso_values[(unsigned char)str[21]];
      case 21:
        hval += asso_values[(unsigned char)str[20]];
      case 20:
        hval += asso_values[(unsigned char)str[19]];
      case 19:
        hval += asso_values[(unsigned char)str[18]];
      case 18:
        hval += asso_values[(unsigned char)str[17]];
      case 17:
        hval += asso_values[(unsigned char)str[16]];
      case 16:
        hval += asso_values[(unsigned char)str[15]];
      case 15:
        hval += asso_values[(unsigned char)str[14]];
      case 14:
        hval += asso_values[(unsigned char)str[13]];
      case 13:
        hval += asso_values[(unsigned char)str[12]];
      case 12:
        hval += asso_values[(unsigned char)str[11]];
      case 11:
        hval += asso_values[(unsigned char)str[10]];
      case 10:
        hval += asso_values[(unsigned char)str[9]];
      case 9:
        hval += asso_values[(unsigned char)str[8]];
      case 8:
        hval += asso_values[(unsigned char)str[7]];
      case 7:
        hval += asso_values[(unsigned char)str[6]];
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      case 5:
        hval += asso_values[(unsigned char)str[4]];
      case 4:
        hval += asso_values[(unsigned char)str[3]];
      case 3:
        hval += asso_values[(unsigned char)str[2]];
      case 2:
        hval += asso_values[(unsigned char)str[1]];
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

#ifdef __GNUC__
__inline
#endif
const struct props *
findProp (register const char *str, register unsigned int len)
{
  enum
    {
      TOTAL_KEYWORDS = 112,
      MIN_WORD_LENGTH = 3,
      MAX_WORD_LENGTH = 32,
      MIN_HASH_VALUE = 5,
      MAX_HASH_VALUE = 897
    };

  static const struct props wordlist_prop[] =
    {
      {"color", CSS_PROP_COLOR},
      {"right", CSS_PROP_RIGHT},
      {"border", CSS_PROP_BORDER},
      {"height", CSS_PROP_HEIGHT},
      {"border-color", CSS_PROP_BORDER_COLOR},
      {"clear", CSS_PROP_CLEAR},
      {"left", CSS_PROP_LEFT},
      {"border-right", CSS_PROP_BORDER_RIGHT},
      {"border-right-color", CSS_PROP_BORDER_RIGHT_COLOR},
      {"border-left", CSS_PROP_BORDER_LEFT},
      {"float", CSS_PROP_FLOAT},
      {"border-left-color", CSS_PROP_BORDER_LEFT_COLOR},
      {"top", CSS_PROP_TOP},
      {"clip", CSS_PROP_CLIP},
      {"border-top", CSS_PROP_BORDER_TOP},
      {"border-top-color", CSS_PROP_BORDER_TOP_COLOR},
      {"bottom", CSS_PROP_BOTTOM},
      {"border-bottom", CSS_PROP_BORDER_BOTTOM},
      {"border-bottom-color", CSS_PROP_BORDER_BOTTOM_COLOR},
      {"max-height", CSS_PROP_MAX_HEIGHT},
      {"width", CSS_PROP_WIDTH},
      {"cursor", CSS_PROP_CURSOR},
      {"table-layout", CSS_PROP_TABLE_LAYOUT},
      {"size", CSS_PROP_SIZE},
      {"quotes", CSS_PROP_QUOTES},
      {"border-width", CSS_PROP_BORDER_WIDTH},
      {"direction", CSS_PROP_DIRECTION},
      {"outline", CSS_PROP_OUTLINE},
      {"outline-color", CSS_PROP_OUTLINE_COLOR},
      {"z-index", CSS_PROP_Z_INDEX},
      {"border-right-width", CSS_PROP_BORDER_RIGHT_WIDTH},
      {"line-height", CSS_PROP_LINE_HEIGHT},
      {"unicode-bidi", CSS_PROP_UNICODE_BIDI},
      {"font", CSS_PROP_FONT},
      {"text-align", CSS_PROP_TEXT_ALIGN},
      {"border-left-width", CSS_PROP_BORDER_LEFT_WIDTH},
      {"text-decoration", CSS_PROP_TEXT_DECORATION},
      {"scrollbar-3dlight-color", CSS_PROP_SCROLLBAR_3DLIGHT_COLOR},
      {"border-top-width", CSS_PROP_BORDER_TOP_WIDTH},
      {"overflow", CSS_PROP_OVERFLOW},
      {"scrollbar-highlight-color", CSS_PROP_SCROLLBAR_HIGHLIGHT_COLOR},
      {"padding", CSS_PROP_PADDING},
      {"max-width", CSS_PROP_MAX_WIDTH},
      {"scrollbar-face-color", CSS_PROP_SCROLLBAR_FACE_COLOR},
      {"border-collapse", CSS_PROP_BORDER_COLLAPSE},
      {"border-style", CSS_PROP_BORDER_STYLE},
      {"border-bottom-width", CSS_PROP_BORDER_BOTTOM_WIDTH},
      {"min-height", CSS_PROP_MIN_HEIGHT},
      {"margin", CSS_PROP_MARGIN},
      {"page-break-before", CSS_PROP_PAGE_BREAK_BEFORE},
      {"padding-right", CSS_PROP_PADDING_RIGHT},
      {"page-break-after", CSS_PROP_PAGE_BREAK_AFTER},
      {"border-right-style", CSS_PROP_BORDER_RIGHT_STYLE},
      {"margin-right", CSS_PROP_MARGIN_RIGHT},
      {"padding-left", CSS_PROP_PADDING_LEFT},
      {"vertical-align", CSS_PROP_VERTICAL_ALIGN},
      {"border-left-style", CSS_PROP_BORDER_LEFT_STYLE},
      {"margin-left", CSS_PROP_MARGIN_LEFT},
      {"background", CSS_PROP_BACKGROUND},
      {"background-color", CSS_PROP_BACKGROUND_COLOR},
      {"padding-top", CSS_PROP_PADDING_TOP},
      {"scrollbar-track-color", CSS_PROP_SCROLLBAR_TRACK_COLOR},
      {"visibility", CSS_PROP_VISIBILITY},
      {"border-top-style", CSS_PROP_BORDER_TOP_STYLE},
      {"display", CSS_PROP_DISPLAY},
      {"outline-width", CSS_PROP_OUTLINE_WIDTH},
      {"margin-top", CSS_PROP_MARGIN_TOP},
      {"counter-reset", CSS_PROP_COUNTER_RESET},
      {"content", CSS_PROP_CONTENT},
      {"text-indent", CSS_PROP_TEXT_INDENT},
      {"padding-bottom", CSS_PROP_PADDING_BOTTOM},
      {"font-weight", CSS_PROP_FONT_WEIGHT},
      {"border-bottom-style", CSS_PROP_BORDER_BOTTOM_STYLE},
      {"margin-bottom", CSS_PROP_MARGIN_BOTTOM},
      {"font-size", CSS_PROP_FONT_SIZE},
      {"scrollbar-arrow-color", CSS_PROP_SCROLLBAR_ARROW_COLOR},
      {"empty-cells", CSS_PROP_EMPTY_CELLS},
      {"position", CSS_PROP_POSITION},
      {"white-space", CSS_PROP_WHITE_SPACE},
      {"-khtml-text-decoration-color", CSS_PROP__KHTML_TEXT_DECORATION_COLOR},
      {"min-width", CSS_PROP_MIN_WIDTH},
      {"scrollbar-base-color", CSS_PROP_SCROLLBAR_BASE_COLOR},
      {"background-repeat", CSS_PROP_BACKGROUND_REPEAT},
      {"list-style", CSS_PROP_LIST_STYLE},
      {"marker-offset", CSS_PROP_MARKER_OFFSET},
      {"background-image", CSS_PROP_BACKGROUND_IMAGE},
      {"caption-side", CSS_PROP_CAPTION_SIDE},
      {"letter-spacing", CSS_PROP_LETTER_SPACING},
      {"font-family", CSS_PROP_FONT_FAMILY},
      {"orphans", CSS_PROP_ORPHANS},
      {"outline-style", CSS_PROP_OUTLINE_STYLE},
      {"border-spacing", CSS_PROP_BORDER_SPACING},
      {"-khtml-flow-mode", CSS_PROP__KHTML_FLOW_MODE},
      {"widows", CSS_PROP_WIDOWS},
      {"font-style", CSS_PROP_FONT_STYLE},
      {"text-transform", CSS_PROP_TEXT_TRANSFORM},
      {"font-variant", CSS_PROP_FONT_VARIANT},
      {"list-style-image", CSS_PROP_LIST_STYLE_IMAGE},
      {"scrollbar-shadow-color", CSS_PROP_SCROLLBAR_SHADOW_COLOR},
      {"page-break-inside", CSS_PROP_PAGE_BREAK_INSIDE},
      {"word-spacing", CSS_PROP_WORD_SPACING},
      {"list-style-type", CSS_PROP_LIST_STYLE_TYPE},
      {"-khtml-user-input", CSS_PROP__KHTML_USER_INPUT},
      {"counter-increment", CSS_PROP_COUNTER_INCREMENT},
      {"background-attachment", CSS_PROP_BACKGROUND_ATTACHMENT},
      {"scrollbar-darkshadow-color", CSS_PROP_SCROLLBAR_DARKSHADOW_COLOR},
      {"background-position", CSS_PROP_BACKGROUND_POSITION},
      {"background-position-x", CSS_PROP_BACKGROUND_POSITION_X},
      {"-khtml-border-vertical-spacing", CSS_PROP__KHTML_BORDER_VERTICAL_SPACING},
      {"background-position-y", CSS_PROP_BACKGROUND_POSITION_Y},
      {"list-style-position", CSS_PROP_LIST_STYLE_POSITION},
      {"-khtml-border-horizontal-spacing", CSS_PROP__KHTML_BORDER_HORIZONTAL_SPACING}
    };

  static const signed char lookup[] =
    {
       -1,  -1,  -1,  -1,  -1,   0,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,   1,  -1,  -1,  -1,  -1,
       -1,   2,  -1,  -1,  -1,  -1,   3,   4,  -1,  -1,
        5,  -1,  -1,  -1,   6,  -1,  -1,   7,  -1,  -1,
       -1,  -1,  -1,   8,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,   9,  -1,  -1,  -1,
       10,  -1,  11,  -1,  -1,  -1,  -1,  -1,  12,  13,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       14,  -1,  -1,  -1,  -1,  -1,  15,  -1,  -1,  -1,
       -1,  16,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  17,  -1,  -1,  -1,  -1,  -1,  18,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       19,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  20,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  21,  22,  -1,  23,
       -1,  24,  -1,  -1,  -1,  -1,  -1,  25,  -1,  26,
       -1,  -1,  27,  -1,  -1,  -1,  -1,  -1,  28,  -1,
       -1,  -1,  29,  30,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  31,  32,  -1,  33,  -1,  -1,  -1,  -1,  -1,
       34,  -1,  35,  -1,  -1,  36,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  37,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  38,  -1,  39,  -1,
       40,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  41,  -1,  42,
       43,  -1,  -1,  -1,  -1,  44,  -1,  45,  -1,  46,
       47,  48,  49,  50,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  51,  -1,  52,  -1,  -1,  -1,  53,  -1,  -1,
       -1,  -1,  54,  -1,  55,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  56,  -1,  -1,  -1,  57,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  58,  -1,  -1,  -1,  -1,
       -1,  59,  -1,  -1,  -1,  -1,  60,  -1,  -1,  -1,
       -1,  61,  -1,  -1,  -1,  62,  63,  64,  65,  -1,
       66,  -1,  -1,  67,  -1,  -1,  -1,  68,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  69,  -1,  -1,  70,
       -1,  71,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  72,
       -1,  -1,  -1,  73,  74,  -1,  -1,  -1,  -1,  -1,
       -1,  75,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  76,  -1,  77,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  78,  -1,  79,  80,
       81,  -1,  82,  -1,  -1,  83,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  84,  -1,  -1,  85,  86,  -1,  87,
       -1,  88,  89,  -1,  -1,  -1,  -1,  -1,  90,  -1,
       -1,  -1,  -1,  -1,  91,  -1,  92,  -1,  -1,  -1,
       -1,  93,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       94,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  95,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  96,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  97,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  98,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  99,  -1,  -1,  -1,  -1, 100,  -1,  -1,
      101,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 102,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1, 103,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 104,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1, 105,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1, 106,  -1,  -1,  -1,  -1,  -1,
       -1, 107,  -1,  -1,  -1, 108,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1, 109,  -1,  -1, 110,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
       -1,  -1,  -1,  -1,  -1,  -1,  -1, 111
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = hash_prop (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        {
          register int index = lookup[key];

          if (index >= 0)
            {
              register const char *s = wordlist_prop[index].name;

              if (*str == *s && !strncmp (str + 1, s + 1, len - 1) && s[len] == '\0')
                return &wordlist_prop[index];
            }
        }
    }
  return 0;
}
static const char * const propertyList[] = {
"",
"background-color", 
"background-image", 
"background-repeat", 
"background-attachment", 
"background-position", 
"background-position-x", 
"background-position-y", 
"border-collapse", 
"border-spacing", 
"-khtml-border-horizontal-spacing", 
"-khtml-border-vertical-spacing", 
"border-top-color", 
"border-right-color", 
"border-bottom-color", 
"border-left-color", 
"border-top-style", 
"border-right-style", 
"border-bottom-style", 
"border-left-style", 
"border-top-width", 
"border-right-width", 
"border-bottom-width", 
"border-left-width", 
"bottom", 
"caption-side", 
"clear", 
"clip", 
"color", 
"content", 
"counter-increment", 
"counter-reset", 
"cursor", 
"direction", 
"display", 
"empty-cells", 
"float", 
"font-family", 
"font-size", 
"font-style", 
"font-variant", 
"font-weight", 
"height", 
"left", 
"letter-spacing", 
"line-height", 
"list-style-image", 
"list-style-position", 
"list-style-type", 
"margin-top", 
"margin-right", 
"margin-bottom", 
"margin-left", 
"marker-offset", 
"max-height", 
"max-width", 
"min-height", 
"min-width", 
"orphans", 
"outline-color", 
"outline-style", 
"outline-width", 
"overflow", 
"padding-top", 
"padding-right", 
"padding-bottom", 
"padding-left", 
"page-break-after", 
"page-break-before", 
"page-break-inside", 
"position", 
"quotes", 
"right", 
"size", 
"table-layout", 
"text-align", 
"text-decoration", 
"text-indent", 
"text-transform", 
"top", 
"unicode-bidi", 
"vertical-align", 
"visibility", 
"white-space", 
"widows", 
"width", 
"word-spacing", 
"z-index", 
"background", 
"border", 
"border-color", 
"border-style", 
"border-top", 
"border-right", 
"border-bottom", 
"border-left", 
"border-width", 
"font", 
"list-style", 
"margin", 
"outline", 
"padding", 
"scrollbar-base-color", 
"scrollbar-face-color", 
"scrollbar-shadow-color", 
"scrollbar-highlight-color", 
"scrollbar-3dlight-color", 
"scrollbar-darkshadow-color", 
"scrollbar-track-color", 
"scrollbar-arrow-color", 
"-khtml-flow-mode", 
"-khtml-user-input", 
"-khtml-text-decoration-color", 
    0
};
DOMString getPropertyName(unsigned short id)
{
    if(id >= CSS_PROP_TOTAL || id == 0)
      return DOMString();
    else
      return DOMString(propertyList[id]);
}

