#cmakedefine01 KIO_NO_SOLID
#cmakedefine01 KIO_NO_NEPOMUK
#cmakedefine01 KIO_NO_STRIGI
#cmakedefine01 KIO_NO_SOPRANO
#cmakedefine01 HAVE_X11
#cmakedefine01 HAVE_STRUCT_SOCKADDR_SA_LEN
#cmakedefine01 HAVE_BACKTRACE
#cmakedefine01 HAVE_SYS_STAT_H
#cmakedefine01 HAVE_XRENDER
#cmakedefine01 HAVE_GETGROUPLIST 
