/*
 * This file was generated by dbusidl2cpp version 0.3
 * when processing input file org.kde.KDirNotify.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef KDIRNOTIFY_H_137891145808813
#define KDIRNOTIFY_H_137891145808813

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <dbus/qdbus.h>

#include <kdelibs_export.h>

/*
 * Proxy class for interface org.kde.KDirNotify
 */
class KIO_EXPORT OrgKdeKDirNotifyInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.kde.KDirNotify"; }

public:
    explicit OrgKdeKDirNotifyInterface(QDBusAbstractInterfacePrivate *p);

    ~OrgKdeKDirNotifyInterface();

public slots: // METHODS
signals: // SIGNALS
    void FileRenamed(const QString &src, const QString &dst);
    void FilesAdded(const QString &directory);
    void FilesChanged(const QStringList &fileList);
    void FilesRemoved(const QStringList &fileList);
    void enteredDirectory(const QString &url);
    void leftDirectory(const QString &url);

public:
    static void emitFileRenamed(const QString &src, const QString &dst);
    static void emitFilesAdded(const QString &directory);
    static void emitFilesChanged(const QStringList &fileList);
    static void emitFilesRemoved(const QStringList &fileList);    
    static void emitEnteredDirectory(const QString &url);
    static void emitLeftDirectory(const QString &url);
};

namespace org {
  namespace kde {
    typedef ::OrgKdeKDirNotifyInterface KDirNotify;
  }
}
#endif
