#! /usr/bin/env python

Import('env')

env.subdirs('kssl kio bookmarks kfile kpasswdserver')

obj = env.kdeobj('shlib', env)
obj.target   = 'libkio'
obj.vnum     = '6.0.2'
obj.source   = "SConscript.dummy"
obj.iskdelib = 1
obj.linkflags = '-Wl,--whole-archive build/kio/kio/libksycoca.a build/kio/bookmarks/libkbookmarks.a build/kio/kfile/libkfile.a -Wl,--no-whole-archive'
obj.uselib   = 'QT QTCORE QTGUI QT3SUPPORT KDE4 FAM'
obj.libs     = 'kssl/libkssl.a kio/libkiocore.a  ../kdeui/libkdeui.la ../kdesu/libkdesu.la ../kwallet/client/libkwalletclient.la'
#$(LIBZ) $(LIBFAM) $(LIBVOLMGT)

obj.execute()
# For now ;(
env.Depends('libkio.so.6.0.2', 'kio/libksycoca.a')
env.Depends('libkio.so.6.0.2', 'bookmarks/libkbookmarks.a')
env.Depends('libkio.so.6.0.2', 'kfile/libkfile.a')

servicetypes = [ 'application.desktop', 'kurifilterplugin.desktop', 'kcomprfilter.desktop', 'kscan.desktop', 
'kdatatool.desktop', 'kfileplugin.desktop', 'kcmodule.desktop', 'renamedlgplugin.desktop' ]

env.bksys_insttype('KDESERVTYPES','', servicetypes)
env.bksys_insttype('KDESERV','', 'data.protocol')
env.bksys_insttype('KDESERV','kded', 'kpasswdserver.desktop')
env.bksys_insttype('KDEAPPS','kconf_update', [ 'kioslave.upd', 'proxytype.pl', 'useragent.pl' ])
env.bksys_insttype('KDEMIME','','magic')
