#! /bin/sh

echo "this script does nothing. Convert your documentation to XML DTD 4.1.2"
echo "otherwise provide HTML. This should do nothing, because either the HTML"
echo "is already there or the application should use meinproc and XML"

