addMethod( "QStringList", "availableAudioStreams()" );
addMethod( "QString", "selectedSubtitleStream(const QObject*)" );
addMethod( "", "removeAudioPath(QObject*)" );
addMethod( "", "pause()" );
addMethod( "", "setTickInterval(qint32)" );
addMethod( "QStringList", "availableSubtitleStreams()" );
addMethod( "bool", "hasVideo()" );
addMethod( "", "removeVideoPath(QObject*)" );
addMethod( "", "stop()" );
addMethod( "QString", "selectedVideoStream(const QObject*)" );
addMethod( "qint32", "tickInterval()" );
addMethod( "", "selectAudioStream(QString,const QObject*)" );
addMethod( "QString", "selectedAudioStream(const QObject*)" );
addMethod( "bool", "addAudioPath(QObject*)" );
addMethod( "QStringList", "availableVideoStreams()" );
addMethod( "", "seek(qint64)" );
addMethod( "qint64", "currentTime()" );
addMethod( "Phonon::State", "state()" );
addMethod( "bool", "seekable()" );
addMethod( "", "selectSubtitleStream(QString,const QObject*)" );
addMethod( "", "selectVideoStream(QString,const QObject*)" );
addMethod( "", "play()" );
addMethod( "bool", "addVideoPath(QObject*)" );
