addMethod("", "setStreamSeekable(bool)");
addSignal("needData()");
addMethod("", "setStreamSize(qint64)");
addMethod("qint64", "streamSize()");
addSignal("length(qint64)");
addMethod("qint64", "remainingTime()", true);
addSignal("enoughData()");
addSignal("seekStream(qint64)");
addSignal("finished()");
addMethod("bool", "streamSeekable()");
addSignal("aboutToFinish(qint32)");
addMethod("qint32", "aboutToFinishTime()");
addMethod("", "setAboutToFinishTime(qint32)");
