addSignal("prefinishMarkReached(qint32)");
addSignal("tick(qint64)");
addSignal("hasVideoChanged(bool)");
addSignal("metaDataChanged(const QMultiMap<QString, QString>&)");
addSignal("aboutToFinish()");
addSignal("stateChanged(Phonon::State, Phonon::State)");
addSignal("seekableChanged(bool)");
addSignal("totalTimeChanged(qint64)");
addSignal("finished()");
addSignal("bufferStatus(int)");
