addMethod( "KUrl", "nextUrl()" );
addMethod( "", "doCrossfade(bool)" );
addMethod( "", "setNextUrl(KUrl)" );
addMethod( "", "timeBetweenMedia(qint32)" );
addMethod( "", "setDoCrossfade(bool)" );
addMethod( "", "nextUrl(KUrl)" );
addMethod( "bool", "doCrossfade()" );
addMethod( "", "setTimeBetweenMedia(qint32)" );
addMethod( "qint32", "timeBetweenMedia()" );
