/*
 * This file was generated by dbusidl2cpp version 0.3
 * when processing input file org.kde.KDEPrint.KMFactory.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#include "kmfactoryiface.h"

/*
 * Implementation of interface class OrgKdeKDEPrintKMFactoryInterface
 */

OrgKdeKDEPrintKMFactoryInterface::OrgKdeKDEPrintKMFactoryInterface(QDBusAbstractInterfacePrivate *p)
    : QDBusAbstractInterface(p)
{
}

OrgKdeKDEPrintKMFactoryInterface::~OrgKdeKDEPrintKMFactoryInterface()
{
}


#include "kmfactoryiface.moc"
