/*
 * This file was generated by dbusidl2cpp version 0.3
 * when processing input file org.kde.KDEPrint.KMFactory.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef KMFACTORYIFACE_H_282481146498264
#define KMFACTORYIFACE_H_282481146498264

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <dbus/qdbus.h>

/*
 * Proxy class for interface org.kde.KDEPrint.KMFactory
 */
class OrgKdeKDEPrintKMFactoryInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.kde.KDEPrint.KMFactory"; }

public:
    explicit OrgKdeKDEPrintKMFactoryInterface(QDBusAbstractInterfacePrivate *p);

    ~OrgKdeKDEPrintKMFactoryInterface();

public slots: // METHODS
signals: // SIGNALS
    void configChanged();
    void pluginChanged(int in0);
};

namespace org {
  namespace kde {
    namespace KDEPrint {
      typedef ::OrgKdeKDEPrintKMFactoryInterface KMFactory;
    }
  }
}
#endif
