/*
 * This file was generated by dbusidl2cpp version 0.3
 * when processing input file org.kde.KDEPrint.KMFactory.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#ifndef KMFACTORYADAPTOR_H_282481146498264
#define KMFACTORYADAPTOR_H_282481146498264

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.KDEPrint.KMFactory
 */
class KMFactoryAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.KDEPrint.KMFactory")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.KDEPrint.KMFactory\" >"
"    <signal name=\"pluginChanged\" >"
"      <arg direction=\"out\" type=\"i\" />"
"    </signal>"
"    <signal name=\"configChanged\" />"
"  </interface>"
        "")
public:
    KMFactoryAdaptor(QObject *parent);
    virtual ~KMFactoryAdaptor();

public: // PROPERTIES
public slots: // METHODS
signals: // SIGNALS
    void configChanged();
    void pluginChanged(int in0);
};

#endif
