#!/bin/bash
# compile entire kdelibs/win32 in debug mode
# (c) 2003-2005, Jaroslaw Staniek, js@iidea.pl

if [ "$1" == "noclean" ] ; then
	noclean=1
fi

update_kdelibs_pro_files || exit 1

pwd=`pwd`
make='nmake -nologo'

# special
cd win/9x && $make || exit 1
cd $pwd

# all
for d in \
win \
libltdl \
dcop \
dcop/dcopidl \
dcop/dcopidl2cpp \
kdefx \
kstyles/thinkeramik/widget-engine \
kdecore \
kdeui \
kio \
kresources \
kabc/vcard \
kabc \
kutils \
kparts \
kmdi \
kioslave/gzip \
kioslave/bzip2 \
interfaces/ktexteditor \
kate/interfaces \
kate/part \
 ; do 
	echo ================== $d =================
	cd $d && qmake || exit 1
	if [ -z $noclean ] ; then
		$make clean || exit 1
	fi
	$make || exit 1
	cd $pwd
done

cd kdewidgets
qmake makekdewidgets.pro && $make clean && $make || exit 1
qmake && $make clean && $make || exit 1
cd $pwd

cd kded
./makeall || exit 1
cd $pwd
