#!/bin/bash
# compile entire kdelibs/win32 in release mode
# (c) 2003-2005, Jaroslaw Staniek, js@iidea.pl

if [ "$1" == "noclean" ] ; then
	noclean=1
fi

update_kdelibs_pro_files || exit 1
.copy_missing_headers || exit 1
source .build_kdelibs_comon || exit 1

cd "$KDELIBS"

echo "-------------------------------------------------"
echo "Building Release Version of KDElibs/win32"
echo "Source directory: \$KDELIBS = $KDELIBS"
echo "Version: $KDE_VER_MAJ.$KDE_VER_MIN.$KDE_VER_PAT"
echo "Destination directory: \$KDEDIR = $KDEDIR"
if [ -n $noclean ] ; then
	echo "Options: noclean"
fi
echo "-------------------------------------------------"
echo

# special
cd win/9x || exit 1
if [ "$1" != "noclean" ] ; then
	$make -f Makefile.rel clean
fi
$make -f Makefile.rel || exit 1
cd $pwd

# all
for d in \
win \
libltdl \
dcop/KDE-ICE \
dcop \
dcop/dcopidl \
dcop/dcopidl2cpp \
dcop/dcopserver \
dcop/dcopserver_shutdown \
dcop/iceauth \
kdefx \
kdecore \
kdeui \
kstyles/thinkeramik/widget-engine \
kio \
kresources \
kabc/vcard \
kabc \
kutils \
kparts \
kmdi \
kioslave/gzip \
kioslave/bzip2 \
interfaces/ktexteditor \
kate/interfaces \
kate/part \
 ; do 
	echo ================== $d =================
	cd $d || exit 1
	if [ -z $noclean ] ; then
		$make -f Makefile.release clean
	fi
	mkrel || exit 1
	cd $pwd
done

cd kded
./makeall_rel.sh || exit 1
cd $pwd
