#!/bin/bash
# compile entire kdelibs/win32 in debug mode
# (c) 2003-2005, Jaroslaw Staniek, js@iidea.pl

if [ "$1" == "noclean" ] ; then
	noclean=1
fi

update_kdelibs_pro_files || exit 1
.copy_missing_headers || exit 1
source .build_kdelibs_comon || exit 1

cd "$KDELIBS"

echo "-------------------------------------------------"
echo "Building Debug Version of KDElibs/win32"
echo "Source directory: \$KDELIBS = $KDELIBS"
echo "Version: $KDE_VER_MAJ.$KDE_VER_MIN.$KDE_VER_PAT"
echo "Destination directory: \$KDEDIR = $KDEDIR"
if [ -n $noclean ] ; then
	echo "Options: noclean"
fi
echo "-------------------------------------------------"
echo

# special
cd win/9x && $make || exit 1
cd "$pwd"

if [ -d "kstyles/thinkeramik/widget-engine" ] ; then
	additional="kstyles/thinkeramik/widget-engine"
fi

# all
for d in \
win \
libltdl \
dcop/KDE-ICE \
dcop \
dcop/dcopidl \
dcop/dcopidl2cpp \
dcop/dcopserver \
dcop/dcopserver_shutdown \
dcop/iceauth \
kdefx \
$additional \
kdecore \
kdeui \
kio \
kresources \
kabc/vcard \
kabc \
kutils \
kparts \
kmdi \
kioslave/gzip \
kioslave/bzip2 \
interfaces/ktexteditor \
kate/interfaces \
kate/part \
 ; do 
	echo ================== $d =================
	cd $d || exit 1
	if [ -z $noclean ] ; then
		$make clean
	fi
	qmake && $make || exit 1
	cd $pwd
done

cd kdewidgets
qmake makekdewidgets.pro && $make clean && $make || exit 1
qmake && $make clean && $make || exit 1

# copy kdewidgets plugin for Qt Designer
cp $KDEDIR/lib/kde3/plugins/designer/kdewidgets.dll $QTDIR/plugins/designer/

cd $pwd

cd kded
./makeall.sh || exit 1
cd $pwd
