#!/bin/bash

# copies all used .pro files from kdelibs/ to kdelibs/win/pro_files/
# what makes it easier to commit that to KDE CVS
# (c) 2005, Jaroslaw Staniek

dest=win/pro_files
mkdir -p $dest

[ -z "$KDELIBS" ] && echo "KDELIBS?" && exit 1

cd $KDELIBS

for pro in `find . -name \*.pro | grep -v "\/\.\|^\.\/win/"` ; do
	dir=`dirname $pro`
	mkdir -p $dest/$dir
	cp -p $pro $dest/$pro
	echo $pro
done

