#!/bin/bash

# Copies all used .pro (and a few shell) files kdelibs/ to kdelibs/win/pro_files/
# what makes it easier to commit that to KDE CVS
# (c) 2005, Jaroslaw Staniek

dest=win/pro_files
mkdir -p $dest

.check_kde_env || exit 1

cd "$KDELIBS"

for pro in `find . -name \*.pro | grep -v "\/\.\|^\.\/win/"` kded/makeall.sh kded/makeall_rel.sh ; do
	dir=`dirname "$pro"`
	mkdir -p "$dest/$dir"
	if [ "$pro" -nt "$dest/$pro" ] ; then
		cp -p "$pro" "$dest/$pro"
		echo "$pro"
	fi
done

