#!/bin/sh

# runs kdcopidl for current dir
# or for $1 dir, (and $2, $3, $4, $5), whatever is provided

if [ -n "$1" ] ; then
 dir="$1"
else
 dir="."
fi

find $dir -maxdepth 1 -name \*.h | while read ; do 
	grep K_DCOP $REPLY > /dev/null || continue
	name=`echo $REPLY | sed -e "s/\\.h//"`
	if [ $name".kidl" -ot $REPLY -o ! -f $name".kidl" -o ! -f $name"_skel.cpp" -o ! -f $name"_stub.cpp" ] ; then
		echo DCOPIDL for $REPLY...
		dcopidl $REPLY > $name".kidl"
		dcopidl2cpp $name".kidl"
	fi
done

[ -n "$2" ] && kdcopidl $2
[ -n "$3" ] && kdcopidl $3
[ -n "$4" ] && kdcopidl $4
[ -n "$5" ] && kdcopidl $5
