#!/bin/bash

# Creates KDE-compatible .moc files out of .h files in current directory
# .moc files are saved to moc/ subdirectory.
# Any additional arguments are directories - kmoc will be called for each of them.

mkdir -p moc
find . -maxdepth 1 -name \*.h | while read ; do 
	grep Q_OBJECT $REPLY > /dev/null || continue
	moc=moc/`echo $REPLY | sed -e "s/\\.h/\\.moc/;s/\\.\\///"`
	if [ $moc -ot $REPLY ] ; then echo mocing $REPLY... ; moc $REPLY -o $moc ; fi
done

pwd=`pwd`
while [ $# -gt 0 ] ; do
	cd $pwd/$1 && kmoc
	cd $pwd
	shift
done
