#!/bin/bash

# Copies all used .pro files from kdelibs/win/pro_files/ to kdelibs/
# so they can be used to build kdelibs.
# Note: only newer files are copied over older.
# (c) 2005, Jaroslaw Staniek, js@iidea.pl

[ -z "$KDELIBS" ] && echo "$0: \$KDELIBS environment variable is not set. Set it to absolute path of kdelibs/win32 source code, e.g. C:\\kdelibs" && exit 1

src=win/pro_files
dest=../..

cd "$KDELIBS/$src"

for pro in `find . -name \*.pro` ; do
	dir=`dirname "$pro"`
	if [ ! -d "$KDELIBS/$dir" ] ; then
		true
#		echo "*SKIPPED* - no \$KDELIBS/$dir directory"
	else
		if [ ! "$pro" -nt "$dest/$pro" ] ; then
			true
#			echo "*SKIPPED* $pro is not newer than destination in $KDELIBS"
		else
			echo "UPDATING \$KDELIBS/$pro"
			cp $pro $dest/$pro
		fi
	fi
done

