#!/bin/bash

# Copies all used .pro (and a few shell) files from kdelibs/win/pro_files/ to kdelibs/
# so they can be used to build kdelibs.
# Note: only newer files are copied over older.
# (c) 2005, Jaroslaw Staniek, js@iidea.pl

.check_kde_env || exit 1

src=win/pro_files
dest=../..

cd "$KDELIBS/$src"

for pro in `find . -name \*.pro -o -name \*.sh` ; do
	dir=`dirname "$pro"`
	if [ ! -d "$KDELIBS/$dir" ] ; then
		echo "no \$KDELIBS/$dir directory: creating it"
		mkdir -p "$KDELIBS/$dir"
	fi

	if [ ! "$pro" -nt "$dest/$pro" ] ; then
		true
#			echo "*SKIPPED* $pro is not newer than destination in $KDELIBS"
	else
		echo "UPDATING \$KDELIBS/$pro"
		cp $pro $dest/$pro
	fi
done

