#!/bin/bash

# copies all used .pro files from kdelibs/win/pro_files/ to kdelibs/
# so they can be used to build kdelibs
# (c) 2005, Jaroslaw Staniek

[ -z "$KDELIBS" ] && echo "KDELIBS?" && exit 1

src=win/pro_files
dest=../..

cd "$KDELIBS/$src"

for pro in `find . -name \*.pro` ; do
	dir=`dirname "$pro"`
	if [ ! -d "$KDELIBS/$dir" ] ; then
		echo "*SKIPPED* - no \$KDEDIR/$dir directory"
	else
		if [ ! "$pro" -nt "$dest/$pro" ] ; then
			echo "*SKIPPED* $pro is not newer than destination"
		else
			echo "UPDATING \$KDEDIR/$pro"
			cp $pro $dest/$pro
		fi
	fi
done

