#include <kmedia2.idl>

module Arts {

/*
 * notification proxy for floats, used internally!
 */
interface KFloatWatchProxy {
	attribute float value;
};

/* 
 * used for deliviering MCOP data to the playobjects
 */
interface KIOInputStream : InputStream {
	boolean openURL(string url);
	
	attribute long bufferPackets;

	long packetSize();
};

/*
 * used for piping raw data to KAudioConverter from the POs
 */
interface KDataRequest : SynthModule {
	void goOn();

	default in audio stream left, right;
};

/*
 * TESTING ONLY
 */

interface KIOTestSlow : SynthModule {
	async in byte stream data;

	attribute InputStream inputStream;
};
};
