/* Automatically generated from kjs_dom.cpp using ../../kjs/create_hash_table. DO NOT EDIT ! */

namespace KJS {

const struct HashEntry DOMNodeTableEntries[] = {
   { "nodeType", DOMNode::NodeType, DontDelete|ReadOnly, 0, &DOMNodeTableEntries[72] },
   { "childNodes", DOMNode::ChildNodes, DontDelete|ReadOnly, 0, 0 },
   { "scrollTop", DOMNode::ScrollTop, DontDelete|ReadOnly, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "offsetParent", DOMNode::OffsetParent, DontDelete|ReadOnly, 0, 0 },
   { "ownerDocument", DOMNode::OwnerDocument, DontDelete|ReadOnly, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "clientWidth", DOMNode::ClientWidth, DontDelete|ReadOnly, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "onmousemove", DOMNode::OnMouseMove, DontDelete, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "attributes", DOMNode::Attributes, DontDelete|ReadOnly, 0, 0 },
   { "firstChild", DOMNode::FirstChild, DontDelete|ReadOnly, 0, &DOMNodeTableEntries[61] },
   { 0, 0, 0, 0, 0 },
   { "onmouseover", DOMNode::OnMouseOver, DontDelete, 0, 0 },
   { "nextSibling", DOMNode::NextSibling, DontDelete|ReadOnly, 0, &DOMNodeTableEntries[63] },
   { "parentNode", DOMNode::ParentNode, DontDelete|ReadOnly, 0, &DOMNodeTableEntries[60] },
   { "onselect", DOMNode::OnSelect, DontDelete, 0, 0 },
   { "offsetLeft", DOMNode::OffsetLeft, DontDelete|ReadOnly, 0, 0 },
   { "contains", DOMNode::Contains, DontDelete|ReadOnly|Function, 0, &DOMNodeTableEntries[71] },
   { "onunload", DOMNode::OnUnload, DontDelete, 0, 0 },
   { "ondblclick", DOMNode::OnDblClick, DontDelete, 0, 0 },
   { "removeEventListener", DOMNode::RemoveEventListener, DontDelete|ReadOnly|Function, 0, 0 },
   { "nodeName", DOMNode::NodeName, DontDelete|ReadOnly, 0, &DOMNodeTableEntries[68] },
   { 0, 0, 0, 0, 0 },
   { "addEventListener", DOMNode::AddEventListener, DontDelete|ReadOnly|Function, 0, 0 },
   { "onkeydown", DOMNode::OnKeyDown, DontDelete, 0, &DOMNodeTableEntries[75] },
   { "nodeValue", DOMNode::NodeValue, DontDelete, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "appendChild", DOMNode::AppendChild, DontDelete|ReadOnly|Function, 0, 0 },
   { "onabort", DOMNode::OnAbort, DontDelete, 0, &DOMNodeTableEntries[70] },
   { "onmouseout", DOMNode::OnMouseOut, DontDelete, 0, 0 },
   { "onresize", DOMNode::OnResize, DontDelete, 0, 0 },
   { "clientHeight", DOMNode::ClientHeight, DontDelete|ReadOnly, 0, 0 },
   { "onsubmit", DOMNode::OnSubmit, DontDelete, 0, 0 },
   { "dispatchEvent", DOMNode::DispatchEvent, DontDelete|ReadOnly|Function, 0, 0 },
   { "onmouseup", DOMNode::OnMouseUp, DontDelete, 0, 0 },
   { "parentElement", DOMNode::ParentElement, DontDelete|ReadOnly, 0, 0 },
   { "previousSibling", DOMNode::PreviousSibling, DontDelete|ReadOnly, 0, &DOMNodeTableEntries[62] },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "onreset", DOMNode::OnReset, DontDelete, 0, &DOMNodeTableEntries[74] },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "ondragdrop", DOMNode::OnDragDrop, DontDelete, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "offsetTop", DOMNode::OffsetTop, DontDelete|ReadOnly, 0, 0 },
   { "onchange", DOMNode::OnChange, DontDelete, 0, &DOMNodeTableEntries[66] },
   { "insertBefore", DOMNode::InsertBefore, DontDelete|ReadOnly|Function, 0, 0 },
   { 0, 0, 0, 0, 0 },
   { "removeChild", DOMNode::RemoveChild, DontDelete|ReadOnly|Function, 0, &DOMNodeTableEntries[64] },
   { "hasAttributes", DOMNode::HasAttributes, DontDelete|ReadOnly|Function, 0, &DOMNodeTableEntries[69] },
   { "lastChild", DOMNode::LastChild, DontDelete|ReadOnly, 0, 0 },
   { "replaceChild", DOMNode::ReplaceChild, DontDelete|ReadOnly|Function, 0, 0 },
   { "hasChildNodes", DOMNode::HasChildNodes, DontDelete|ReadOnly|Function, 0, &DOMNodeTableEntries[67] },
   { "cloneNode", DOMNode::CloneNode, DontDelete|ReadOnly|Function, 0, &DOMNodeTableEntries[65] },
   { "onblur", DOMNode::OnBlur, DontDelete, 0, 0 },
   { "onclick", DOMNode::OnClick, DontDelete, 0, &DOMNodeTableEntries[73] },
   { "onerror", DOMNode::OnError, DontDelete, 0, 0 },
   { "onfocus", DOMNode::OnFocus, DontDelete, 0, 0 },
   { "onkeypress", DOMNode::OnKeyPress, DontDelete, 0, 0 },
   { "onkeyup", DOMNode::OnKeyUp, DontDelete, 0, 0 },
   { "onload", DOMNode::OnLoad, DontDelete, 0, 0 },
   { "onmousedwn", DOMNode::OnMouseDown, DontDelete, 0, 0 },
   { "onmove", DOMNode::OnMove, DontDelete, 0, 0 },
   { "offsetWidth", DOMNode::OffsetWidth, DontDelete|ReadOnly, 0, 0 },
   { "offsetHeight", DOMNode::OffsetHeight, DontDelete|ReadOnly, 0, 0 },
   { "scrollLeft", DOMNode::ScrollLeft, DontDelete|ReadOnly, 0, 0 }
};

const struct HashTable DOMNodeTable = { 2, 76, DOMNodeTableEntries, 60 };

}; // namespace
