// DO NOT EDIT - EDIT bugs/Maintainers instead
const char * const packages[] = {
"HIG",
"HIG/General",
"akodelib",
"akregator",
"akregator/akregator konqueror plugin",
"akregator/kontact plugin",
"aktion",
"amarok",
"amor",
"ark",
"ark/Konqueror Plugin",
"arts",
"arts/artsbuilder",
"arts/artscontrol",
"arts/artsd",
"arts/kcmarts",
"arts/knotify",
"arts/libartskde",
"arts/xine_artsplugin",
"artwork",
"atlantik",
"atlantik/monopd",
"atlantikdesigner",
"binaries",
"binaries/cygwin",
"binaries/dpkg",
"binaries/pkgs",
"binaries/rpms",
"bindings",
"boson",
"boson/Editor",
"boson/Graphics",
"boson/Packages",
"brahms",
"bugs.kde.org",
"cdbakeoven",
"cervisia",
"configure",
"dcop",
"dcop/dcopserver",
"dcop/kdcop",
"digikam",
"digikam/Camera GUI",
"digikam/Image Editor",
"digikamimageplugins",
"digikamimageplugins/AdjustLevels",
"digikamimageplugins/Charcoal",
"digikamimageplugins/Despeckle",
"digikamimageplugins/Emboss",
"digikamimageplugins/Filmgrain",
"digikamimageplugins/General",
"digikamimageplugins/OilPaint",
"digikamimageplugins/Raindrops",
"digikamimageplugins/SolarizeImage",
"digikamimageplugins/Unsharp",
"docs",
"docs/Corrections",
"docs/Missing Content",
"docs/Screenshots",
"docs/ksgmltools",
"drkonqi",
"flashkard",
"geheimnis",
"gofai",
"gwenview",
"i18n",
"i18n/af",
"i18n/bg",
"i18n/br",
"i18n/ca",
"i18n/cs",
"i18n/cy",
"i18n/da",
"i18n/de",
"i18n/el",
"i18n/en_GB",
"i18n/eo",
"i18n/es",
"i18n/et",
"i18n/eu",
"i18n/fi",
"i18n/fr",
"i18n/ga",
"i18n/gl",
"i18n/gu",
"i18n/he",
"i18n/hr",
"i18n/hu",
"i18n/is",
"i18n/it",
"i18n/ja",
"i18n/ko",
"i18n/lt",
"i18n/lv",
"i18n/mk",
"i18n/nb",
"i18n/nl",
"i18n/nn",
"i18n/oc",
"i18n/pl",
"i18n/pt",
"i18n/pt-BR",
"i18n/ro",
"i18n/ru",
"i18n/sk",
"i18n/sl",
"i18n/sr",
"i18n/sv",
"i18n/ta",
"i18n/th",
"i18n/tr",
"i18n/uk",
"i18n/wa",
"i18n/zh-CN.GB2312",
"i18n/zh-TW.Big5",
"juk",
"k3b",
"kab",
"kaboodle",
"kaboodle/icons",
"kaddressbook",
"kafka",
"kalamaris",
"kalarm",
"kalzium",
"kandy",
"kappfinder",
"kapptemplate",
"karbon",
"karchie",
"karchiver",
"karm",
"karm/reporting",
"kasteroids",
"katalog",
"kate",
"kate/kwrite",
"kate/part",
"kate/syntax",
"katomic",
"kaudiocreator",
"kbabel",
"kbabel/CatalogManager",
"kbabel/KBabel editor",
"kbabel/KBabelDict",
"kbabel/db search engine",
"kbackgammon",
"kbattleship",
"kbear",
"kbiff",
"kblackbox",
"kbounce",
"kbruch",
"kbugbuster",
"kcachegrind",
"kcalc",
"kcharselect",
"kchart",
"kchat",
"kconfigure",
"kcontrol",
"kcontrol/kcmaccess",
"kcontrol/kcmaccessibility",
"kcontrol/kcmaudiocd",
"kcontrol/kcmbackground",
"kcontrol/kcmbell",
"kcontrol/kcmclock",
"kcontrol/kcmcolors",
"kcontrol/kcmcrypto",
"kcontrol/kcmemail",
"kcontrol/kcmenergy",
"kcontrol/kcmfiletypes",
"kcontrol/kcmfontinst",
"kcontrol/kcmfonts",
"kcontrol/kcmicons",
"kcontrol/kcminfo",
"kcontrol/kcminit",
"kcontrol/kcminput",
"kcontrol/kcmioslaveinfo",
"kcontrol/kcmkabldapconfig",
"kcontrol/kcmkded",
"kcontrol/kcmkdm",
"kcontrol/kcmkeyboard",
"kcontrol/kcmkeys",
"kcontrol/kcmkmix",
"kcontrol/kcmknotify",
"kcontrol/kcmkonq",
"kcontrol/kcmkonqhtml",
"kcontrol/kcmksplash",
"kcontrol/kcmkurifilt",
"kcontrol/kcmkwindecoration",
"kcontrol/kcmkwinoptions",
"kcontrol/kcmlanbrowser",
"kcontrol/kcmlaptop",
"kcontrol/kcmlilo",
"kcontrol/kcmlinuz",
"kcontrol/kcmlocale",
"kcontrol/kcmmidi",
"kcontrol/kcmmouse",
"kcontrol/kcmnotify",
"kcontrol/kcmpanel",
"kcontrol/kcmpasswords",
"kcontrol/kcmprintmgr",
"kcontrol/kcmprivacy",
"kcontrol/kcmproxy",
"kcontrol/kcmsamba",
"kcontrol/kcmscreensaver",
"kcontrol/kcmshell",
"kcontrol/kcmsmserver",
"kcontrol/kcmspellchecking",
"kcontrol/kcmstyle",
"kcontrol/kcmtaskbar",
"kcontrol/kcmuseragent",
"kcontrol/kcmuserinfo",
"kcontrol/krdb",
"kcontrol/kthememanager",
"kcontrol/kthememgr",
"kcpuload",
"kcron",
"kdat",
"kde-bluetooth",
"kde-bluetooth/kbemusedsrv",
"kde-bluetooth/kbluelock",
"kde-bluetooth/kbluetoothd",
"kde-bluetooth/kbthandsfree",
"kde-bluetooth/kbtobexclient",
"kde-bluetooth/kbtobexsrv",
"kde-bluetooth/kbtserialchat",
"kde-bluetooth/khciconfig",
"kde-bluetooth/kio_bluetooth",
"kde-bluetooth/kio_obex",
"kde-bluetooth/kio_sdp",
"kde",
"kde/clipboard",
"kde/dualhead",
"kde/xinerama",
"kdeaddons",
"kdeaddons/dirfilter-plugin",
"kdeaddons/khtmlsettings-plugin",
"kdeaddons/useragent-plugin",
"kdebugdialog",
"kdelibs",
"kdelibs/kbugreport",
"kdelibs/kcertpart",
"kdelibs/kded",
"kdelibs/kdeinit",
"kdelibs/kdesasl",
"kdelibs/kedittoolbar",
"kdelibs/kimgio",
"kdelibs/klauncher",
"kdelibs/klocale",
"kdelibs/kmdi",
"kdelibs/knotify",
"kdelibs/kspell",
"kdelibs/kstyle",
"kdelibs/ksycoca",
"kdelibs/kwallet",
"kdelibs/libkdegames",
"kdelibs/qt",
"kdelirc",
"kdelirc/General",
"kdelirc/irkick",
"kdelirc/kcmlirc",
"kdemultimedia",
"kdepasswd",
"kdeprint",
"kdeprint/kdeprintfax",
"kdeprint/kjobviewer",
"kdesktop",
"kdesktop/icons",
"kdesktop/minicli",
"kdesktop/wallpaper",
"kdessh",
"kdesu",
"kdesu/kdesu",
"kdesu/kdesud",
"kdetv",
"kdevelop",
"kdevelop/UI: IDEAl",
"kdevelop/UI: all modes",
"kdevelop/UI: childframe window",
"kdevelop/UI: tabbed pages",
"kdevelop/UI: toplevel window",
"kdevelop/abbreviation plugin",
"kdevelop/all build tools",
"kdevelop/all editors",
"kdevelop/ant project",
"kdevelop/appwizard",
"kdevelop/astyle",
"kdevelop/autoproject",
"kdevelop/bookmarks part",
"kdevelop/classview",
"kdevelop/code completion",
"kdevelop/cpp-parser",
"kdevelop/cppsupport",
"kdevelop/ctags part",
"kdevelop/customproject",
"kdevelop/cvs part",
"kdevelop/debugger",
"kdevelop/distpart",
"kdevelop/doctreeview",
"kdevelop/documentation viewer",
"kdevelop/file create",
"kdevelop/file groups",
"kdevelop/file selector",
"kdevelop/file tree",
"kdevelop/grep frontend",
"kdevelop/javasupport",
"kdevelop/kate integration",
"kdevelop/kdevelop 2.x (obsolete)",
"kdevelop/konsole part",
"kdevelop/lang: Python",
"kdevelop/lang: perl",
"kdevelop/outputviews",
"kdevelop/partexplorer",
"kdevelop/php support",
"kdevelop/problem reporter",
"kdevelop/qeditor",
"kdevelop/replace part",
"kdevelop/scriptproject",
"kdevelop/trollproject",
"kdf",
"kdialog",
"kdict",
"kdiff3",
"kdiff3/KDiff3Part",
"kdm",
"kdm/kdmdesktop",
"kdm/krootimage",
"kdoc",
"kdvi",
"kedit",
"keditbookmarks",
"keduca",
"kenolaba",
"kexi",
"keystone",
"kfax",
"kfile-plugins",
"kfile-plugins/OOo",
"kfile-plugins/PNG",
"kfile-plugins/avi",
"kfile-plugins/exr",
"kfile-plugins/jpeg",
"kfile-plugins/mp3",
"kfile-plugins/ogg",
"kfile-plugins/ps",
"kfilereplace",
"kfind",
"kfinger",
"kfloppy",
"kformula",
"kformula/filters",
"kfortune",
"kfouleggs",
"kgeo",
"kget",
"kghostview",
"kghostview/Ghostscript",
"kgoldrunner",
"kgoodstuff",
"kgpg",
"khangman",
"khelpcenter",
"khexedit",
"khexedit2",
"khexedit2/KPart",
"khexedit2/Standalone application",
"khexedit2/designer plugin",
"khexedit2/interface",
"khexedit2/library",
"khotkeys",
"kicker",
"kicker/Drag &apos;n Drop",
"kicker/Panel Strut Management",
"kicker/appletproxy",
"kicker/devicesapplet",
"kicker/dockbar",
"kicker/kasbar",
"kicker/kbinaryclock",
"kicker/kclockapplet",
"kicker/mediaapplet",
"kicker/minipagerapplet",
"kicker/multiscreen",
"kicker/naughtyapplet",
"kicker/quicklauncher",
"kicker/sidebar",
"kicker/systemtray",
"kicker/taskbarapplet",
"kicker/transparency",
"kicker/trashapplet",
"kiconedit",
"kig",
"kile",
"kile/editor",
"kile/user interface",
"kim",
"kimagemapeditor",
"kimdaba",
"kinkatta",
"kio",
"kio/audiocd",
"kio/devices",
"kio/file",
"kio/fish",
"kio/floppy",
"kio/ftp",
"kio/gopher",
"kio/help",
"kio/http",
"kio/imap",
"kio/info",
"kio/kamera",
"kio/kfile",
"kio/kioslave",
"kio/kssl",
"kio/man",
"kio/media",
"kio/nfs",
"kio/nntp",
"kio/pop3",
"kio/settings",
"kio/sftp",
"kio/sieve",
"kio/smb",
"kio/smbro",
"kio/smtp",
"kio/svn",
"kio/tar",
"kio/thumbnail",
"kio/uiserver",
"kio/webdav",
"kio/zip",
"kiosk",
"kiosk/kiosktool",
"kipiplugins",
"kipiplugins/acquireimages",
"kipiplugins/batchprocessimages",
"kipiplugins/calendar",
"kipiplugins/cdarchiving",
"kipiplugins/commentseditor",
"kipiplugins/diroperations",
"kipiplugins/findimages",
"kipiplugins/gammacalibration",
"kipiplugins/imagesgallery",
"kipiplugins/jpeglossless",
"kipiplugins/kameraklient",
"kipiplugins/mpegencoder",
"kipiplugins/printwizard",
"kipiplugins/rawconverter",
"kipiplugins/sendimages",
"kipiplugins/slideshow",
"kipiplugins/timeadjust",
"kipiplugins/wallpaper",
"kit",
"kit/icons",
"kitchensync",
"kiten",
"kivio",
"kjots",
"kjsembed",
"kjsembed/Core",
"kjsembed/Docs and examples",
"kjsembed/Plugins",
"kjukebox",
"kjumpingcube",
"klaptopdaemon",
"klatin",
"klegacyimport",
"kless",
"klettres",
"klickety",
"klines",
"klinkstatus",
"klipper",
"klyx",
"kmag",
"kmago",
"kmahjongg",
"kmail",
"kmail/IMAP",
"kmail/addressbook",
"kmail/composer",
"kmail/disconnected IMAP",
"kmail/display",
"kmail/encryption",
"kmail/filtering",
"kmail/kde31compatibility",
"kmail/keys and menus",
"kmail/kmailcvt",
"kmail/messageviewer",
"kmail/mime",
"kmail/pop3",
"kmail/search",
"kmameleon",
"kmameleon/interface",
"kmameleon/tools",
"kmapnotify",
"kmenuedit",
"kmerlin",
"kmessedwords",
"kmid",
"kmidi",
"kmilo",
"kmilo/Asus",
"kmilo/Generic MM module",
"kmilo/Powerbook2 module",
"kmilo/Thinkpad",
"kmilo/vaio",
"kmines",
"kmix",
"kmix/KMix Panel Applet",
"kmix/KMix Panel Docking",
"kmldonkey",
"kmldonkey/libkmldonkey",
"kmoon",
"kmousetool",
"kmouth",
"kmplayer",
"kmplot",
"kmrml",
"kmtrace",
"kmymoney2",
"knapster2",
"knetload",
"knetload/Linux Statistics",
"knewmail",
"knewsticker",
"knode",
"knorskverbs",
"knotes",
"knu",
"kodo",
"koffice",
"koffice/filters",
"kolf",
"kolourpaint",
"kommander",
"kommander/kommander editor",
"kommander/kommander executor",
"kompare",
"kompare/navigationpart",
"kompare/parser",
"kompare/viewpart",
"koncd",
"konqueror",
"konqueror/bookmarks",
"konqueror/file icon view",
"konqueror/file list view",
"konqueror/fsview",
"konqueror/imagerotation",
"konqueror/kcookiejar",
"konqueror/khtml ecma",
"konqueror/khtml event",
"konqueror/khtml forms",
"konqueror/khtml parsing",
"konqueror/khtml part",
"konqueror/khtml renderer",
"konqueror/khtml xml",
"konqueror/khtml",
"konqueror/khtmlimage",
"konqueror/kimgalleryplugin",
"konqueror/kjava",
"konqueror/kjs",
"konqueror/konq-e",
"konqueror/kuick",
"konqueror/nsplugins",
"konqueror/nspluginscan",
"konqueror/nspluginviewer",
"konqueror/reaktivate",
"konqueror/rellinks",
"konqueror/searchbarplugin",
"konqueror/servicemenus",
"konqueror/sidebar media player",
"konqueror/sidebar newsticker",
"konqueror/sidebar",
"konqueror/tabbing",
"konqueror/webarchiverplugin",
"konquest",
"konsole",
"konsole/kwrited",
"konsolekalendar",
"konstruct",
"kontact",
"kontact/calendar",
"kontact/contacts",
"kontact/mail",
"kontact/news",
"kontact/newsticker",
"kontact/notes",
"kontact/summary",
"kontact/todo",
"kontour",
"kontour/filters",
"konversation",
"kooka",
"kooka/libkscan",
"kopennap",
"kopete",
"kopete/Add Contact Wizard",
"kopete/Alias Plugin",
"kopete/Auto-Away Plugin",
"kopete/Autoreplace plugin",
"kopete/Bookmarks plugin",
"kopete/Chat Window",
"kopete/Chatwindow Styles",
"kopete/Connection Status Plugin",
"kopete/Contact list",
"kopete/Cryptography Plugin",
"kopete/DCOP Interface",
"kopete/Gadu-Gadu Plugin",
"kopete/History Plugin",
"kopete/ICQ and AIM Plugins",
"kopete/IRC Plugin",
"kopete/Importer plugin",
"kopete/Jabber Plugin",
"kopete/Latex Plugin",
"kopete/Lotus Sametime Plugin",
"kopete/MSN Plugin",
"kopete/Main Application",
"kopete/New plugin wishes",
"kopete/Novell GroupWise Messenger Plugin",
"kopete/Now Listening Plugin",
"kopete/SMS Plugin",
"kopete/SpellCheck Plugin",
"kopete/Texteffect Plugin",
"kopete/Translator Plugin",
"kopete/Web Presence Plugin",
"kopete/WinPopup Plugin",
"kopete/Yahoo Plugin",
"kopete/libkopete",
"korganizer",
"korganizer/alarmd",
"korganizer/embedded",
"korganizer/exchangeplugin",
"korganizer/groupware",
"korganizer/kalarmd",
"korn",
"koshell",
"kpackage",
"kpager",
"kpaint",
"kpat",
"kpdf",
"kpercentage",
"kpersonalizer",
"kpf",
"kpilot",
"kpilot/Internal editors",
"kpilot/Memo conduit (KNotes)",
"kpilot/Other conduits",
"kpilot/addressbook conduit",
"kpilot/calendar conduits",
"kpilot/kpilotDaemon",
"kplato",
"kpm",
"kpoker",
"kpovmodeler",
"kppp",
"kpresenter",
"kpresenter/filters",
"kquick",
"krandr",
"krandr/control center",
"krandr/krandrtray",
"krdc",
"kreatecd",
"krec",
"krec/mp3_export",
"krec/ogg_export",
"krec/wave_export",
"krecord",
"kregexpeditor",
"kreversi",
"krfb",
"krichtexteditor",
"krita",
"kruler",
"krusader",
"ksame",
"kscd",
"kscreensaver",
"kscreensaver/kcheckpass",
"kscreensaver/kpartsaver",
"kscreensaver/ktux",
"kscreensaver/kxsrun",
"kscreensaver/screensavers",
"kshisen",
"ksim",
"ksirc",
"ksirtet",
"ksmiletris",
"ksmserver",
"ksnake",
"ksnapshot",
"ksokoban",
"kspaceduel",
"ksplash",
"kspread",
"kspread/filters",
"kst",
"kst/datasources",
"kst/elog extension",
"kst/equations",
"kst/i18n",
"kst/plotting",
"kst/plugins",
"kst/ui",
"kst/view objects",
"kstars",
"kstart",
"kstartperf",
"ksteak",
"kstockticker",
"ksvg",
"ksvg/Animations",
"ksvg/JavaScript",
"ksysctrl",
"ksysguard",
"ksysv",
"ktalk",
"ktalkd",
"kteatime",
"ktelnet2",
"kthesaurus",
"ktimemon",
"ktip",
"ktnef",
"ktop",
"ktouch",
"ktron",
"kttsd",
"kttsd/festival plugin",
"kttsd/kcmkttsmgr",
"kttsd/kttsd",
"kttsd/kttsmgr",
"kttt",
"ktuberling",
"kturtle",
"kugar",
"kugar/kudesigner",
"kuickshow",
"kuiviewer",
"kuser",
"kverbos",
"kvidmode",
"kview",
"kview/kviewcanvas",
"kview/kviewviewer",
"kview/plugins",
"kviewerpart",
"kviewshell",
"kvim",
"kvim/Vim KPart",
"kvoctrain",
"kwalletmanager",
"kweather",
"kwebget",
"kwikdisk",
"kwin",
"kwin/compatibility",
"kwin/decorations",
"kwin/multihead",
"kwin4",
"kwintv",
"kwireless",
"kword",
"kword/filters",
"kword/tables",
"kwordquiz",
"kworldclock",
"kwuftpd",
"kxconfig",
"kxkb",
"kxmlrpcd",
"lanbrowsing",
"libkcddb",
"libkdegames",
"libkdegames/General",
"lilo-config",
"lskat",
"mediacontrol",
"megami",
"mp3kult",
"mpeglib",
"noatun",
"noatun/Young Hickory",
"noatun/dub",
"noatun/excellent",
"noatun/hayes",
"noatun/htmlexport",
"noatun/infrared",
"noatun/kjofol-skin",
"noatun/metatag",
"noatun/simple",
"noatun/split",
"noatun/winskin",
"pixieplus",
"qca",
"quanta",
"quanta/VPL",
"sanetracker",
"slicker",
"taglib",
"umbrello",
"unknown",
"www.kde.org",
0 };
