#! /usr/bin/perl
# little script to extract the text from the tips file
# and output it, so xgettext can add the tips to the po file
#
# 2000 by Matthias Kiefer <matthias.kiefer@gmx.de>

sub printText
{
	my $text = $_[0];
	
	if ( $text cmp "" )
	{

	# replace \ with \\
	$text =~ s/\\/\\\\/g;

	# replace " with \"
	$text =~ s/"/\\"/g;
			
	print "\"$text\\n\"\n";
	}
}

open(FILE,"<","tips") or die "unable to open tips file";
if ( $^V ge v5.8.0 ) {
  binmode(FILE,":utf8");
  binmode(STDOUT,":utf8");
} else {
  print "WARNING: NOT using utf8! Upgrade to perl >= 5.8.0.\n";
}

$inTip=0;

while(<FILE>)
{
	chomp;

	# tip starts with <html>
	if(/^\s*<html>(.*)/io)
	{
		$inTip=1;
		print "//i18n file tips.cpp line $.\n";
		print "i18n(\n";
		printText($1);
		next;
	}	

	if($inTip!=0)
	{
		# tip ends with </html>
		if(/^(.*)\s*<\/html>/io)
		{
			printText($1);
			print ");\n\n";
			$inTip=0;
		}
		else
		{
			printText($_);
		}
	}   
}

close(FILE);
