#! /usr/bin/env python

Import('env')
env.subdirs('tests');

ui_files="""
ksharedpixmap.cpp
kmenu.cpp ktoolbar.cpp kaction.cpp kstdaction.cpp
kactioncollection.cpp kactionclasses.cpp
kurllabel.cpp kmenubar.cpp kinputdialog.cpp
knuminput.cpp klineedit.cpp klistview.cpp kprogress.cpp
kcolordialog.cpp kselect.cpp kdatepicker.cpp
kdatetbl.cpp kfontrequester.cpp kfontdialog.cpp ktabctl.cpp
kstatusbar.cpp kmainwindow.cpp
keditlistbox.cpp kscrollview.cpp
kseparator.cpp krestrictedline.cpp
kcolorbutton.cpp ksystemtray.cpp
kbuttonbox.cpp keditcl1.cpp keditcl2.cpp kled.cpp
kshortcutdialog_simple.ui3 kshortcutdialog_advanced.ui3
kshortcutdialog.cpp kkeybutton.cpp kkeydialog.cpp
kruler.cpp kcursor.cpp
kcharselect.cpp kcolormimedata.cpp
knumvalidator.cpp kdialog.cpp kdialogbase.cpp
kjanuswidget.cpp kaboutdialog.cpp
kauthicon.cpp kmessagebox.cpp kdualcolorbutton.cpp
ktoolbarradiogroup.cpp ktoolbarbutton.cpp
ktextbrowser.cpp khelpmenu.cpp
kcmenumngr.cpp
kiconview.cpp klistbox.cpp kwordwrap.cpp kbugreport.cpp
kcombobox.cpp kpassdlg.cpp kxmlguiclient.cpp kxmlguifactory.cpp
kxmlguifactory_p.cpp kxmlguibuilder.cpp kedittoolbar.cpp
kanimwidget.cpp kaboutkde.cpp
kaboutapplication.cpp kdcopactionproxy.cpp
kcolorcombo.cpp kpushbutton.cpp
kcompletionbox.cpp ksqueezedtextlabel.cpp kcmodule.cpp
kcommand.cpp kwindowlistmenu.cpp kfontcombo.cpp ktip.cpp
kdatewidget.cpp karrowbutton.cpp kmainwindowiface.cpp
kmainwindowiface.skel kguiitem.cpp kstdguiitem.cpp
kstringvalidator.cpp kactivelabel.cpp
kwindowinfo.cpp ktextedit.cpp kwizard.cpp kpassivepopup.cpp
ktoolbarhandler.cpp kdatetimewidget.cpp ktimezonewidget.cpp
ksconfig.cpp kspelldlg.cpp
kspell.cpp ksyntaxhighlighter.cpp ktabbar.cpp ktabwidget.cpp
ksplashscreen.cpp kspellui.ui kconfigdialog.cpp
kactionselector.cpp klanguagebutton.cpp klistviewsearchline.cpp
kpixmapregionselectorwidget.cpp kpixmapregionselectordialog.cpp
kwhatsthismanager.cpp kiconviewsearchline.cpp
ktoolbarlabelaction.cpp khbox.cpp kvbox.cpp kconfigdialogmanager.cpp
kpixmapio.cpp krootpixmap.cpp knotification.cpp knotificationmanager.cpp
knotificationmanager.skel
"""

install_headers = """
kprogress.h kcolordialog.h kselect.h 
kdatepicker.h kdatetbl.h kdatetable.h kfontdialog.h kmenu.h kfontrequester.h ktabctl.h 
kstatusbar.h kmainwindow.h kmainwindowiface.h ktoolbar.h kmenubar.h knuminput.h 
kseparator.h klineedit.h krestrictedline.h kcolorbutton.h ksystemtray.h 
kbuttonbox.h keditcl.h kled.h keditlistbox.h kwizard.h kkeydialog.h kkeybutton.h 
kurllabel.h kruler.h kcursor.h kinputdialog.h kactivelabel.h kcharselect.h 
kcolormimedata.h knumvalidator.h kdialog.h kdialogbase.h kjanuswidget.h kaboutdialog.h 
kauthicon.h kmessagebox.h ksharedpixmap.h kdualcolorbutton.h 
ktoolbarbutton.h ktoolbarradiogroup.h ktextbrowser.h kaction.h kactioncollection.h 
kactionclasses.h khelpmenu.h kcmodule.h kcmenumngr.h kactionshortcutlist.h kstdaction.h 
kcombobox.h kiconview.h klistview.h klistbox.h kbugreport.h kpassdlg.h 
kxmlguiclient.h kxmlguibuilder.h kxmlguifactory.h kpixmapio.h kwordwrap.h 
kedittoolbar.h kanimwidget.h krootpixmap.h kaboutkde.h kaboutapplication.h 
kpushbutton.h kdcopactionproxy.h kcolorcombo.h kcompletionbox.h ksqueezedtextlabel.h 
kcommand.h kwindowlistmenu.h kfontcombo.h kaccelgen.h ktip.h kdatewidget.h 
karrowbutton.h kguiitem.h kstdguiitem.h kstringvalidator.h kwindowinfo.h ktextedit.h 
kpassivepopup.h kdatetimewidget.h ktimezonewidget.h kscrollview.h kspell.h ksconfig.h 
kspelldlg.h ksyntaxhighlighter.h ktabbar.h ktabwidget.h ksplashscreen.h 
kconfigdialog.h kactionselector.h klanguagebutton.h klistviewsearchline.h 
kpixmapregionselectorwidget.h kpixmapregionselectordialog.h kiconviewsearchline.h 
ktoolbarlabelaction.h kshortcutdialog.h khbox.h kvbox.h 
kconfigdialogmanager.h knotification.h
"""

# TODO: could this be replaced with install_headers ?  - no it's about non-installed headers
for i in "kaboutdialog_private.h kcursor_private.h kdialogbase_priv.h keditcl.h klistviewlineedit.h kdatetable.h kwhatsthismanager_p.h kstdaction_p.h kcharselect_p.h".split():
       env.Moc(i)

obj = env.kdeobj('shlib', env)
obj.vnum     = '6.0.2'
obj.target   = 'kdeui'
obj.source   = ui_files
obj.uselib   = 'QT QTCORE QTGUI QTXML QT3SUPPORT KDE4'
obj.libpaths = '../kdecore/ ../kdefx/ ../dcop'
obj.libs     = 'kdecore kdefx DCOP'
obj.ccflags += ' -DMAKE_KDEUI_LIB ' # todo: will be generated automatically
if env['WINDOWS']:
	obj.libpaths += ' ../win'
	obj.libs     += ' kdewin32'
obj.iskdelib = 1
obj.execute()

env.Depends('libkdeui.so.6.0.2', '../kdefx/libkdefx.so')

env.bksys_insttype( 'KDEINCLUDE', '', install_headers )
