
#! /usr/bin/env python

Import('env')

obj = env.qt4obj('shlib', env)
obj.vnum     = '6.0.2'
obj.target   = 'libkdesu'
obj.source   = "client.cpp process.cpp kcookie.cpp su.cpp ssh.cpp stub.cpp kdesu_pty.cpp"
obj.uselib   = 'QT QTCORE QTGUI QT3SUPPORT KDE4'
obj.libpaths = '../kdecore ../dcop'
obj.libs     = 'kdecore DCOP'
obj.execute()

stubobj = env.qt4obj('program', env)
stubobj.target = 'kdesu_stub'
stubobj.source = 'kdesu_stub.c'
stubobj.execute()
