
#! /usr/bin/env python

Import('env')

install_headers="""
defaults.h 
client.h 
process.h 
kdesu_pty.h 
kcookie.h 
su.h 
ssh.h 
stub.h
"""

obj = env.qt4obj('shlib', env)
obj.vnum     = '4.2.0'
obj.target   = 'libkdesu'
obj.source   = "client.cpp process.cpp kcookie.cpp su.cpp ssh.cpp stub.cpp kdesu_pty.cpp"
obj.uselib   = 'QT QTCORE QTGUI QT3SUPPORT KDE4'
obj.libpaths = '../kdecore ../dcop'
obj.libs     = 'kdecore DCOP'
obj.execute()

env.Depends('libkdesu.so.4.2.0','../kdecore/libkdecore.so')


stubobj = env.qt4obj('program', env)
stubobj.target = 'kdesu_stub'
stubobj.source = 'kdesu_stub.c'
stubobj.includes = '../kdecore'
stubobj.execute()

env.bksys_insttype( 'KDEINCLUDE', 'kdesu', install_headers )

