
#! /usr/bin/env python

Import('env')

obj = env.qt4obj('shlib', env)
obj.vnum     = '6.0.2'
obj.target   = 'libkdesu'
obj.source   = "client.cpp process.cpp kcookie.cpp su.cpp ssh.cpp stub.cpp kdesu_pty.cpp"
obj.uselib   = 'QT QTCORE QTGUI QT3SUPPORT KDE4'
obj.libs     = '../kdecore/libkdecore.la'
obj.execute()

obj = env.qt4obj('program', env)
obj.target = 'kdesu_stub'
obj.source = 'kdesu_stub.c'
