#! /usr/bin/env python

Import('env')


ice_sources="""
accept.c
authutil.c
connect.c
error.c
getauth.c
globals.c
iceauth.c
listen.c
listenwk.c
locking.c
misc.c
ping.c
process.c
protosetup.c
register.c
replywait.c
setauth.c
shutdown.c
transport.c
watch.c
"""

if env['WINDOWS']:
	obj          = env.genobj('shlib', env)
	obj.ccflags  ="-DICE_t -DTRANS_SERVER -DTRANS_CLIENT -DTCPCONN -DANSICPP"
	obj.libpaths = '../../win '
	obj.libs     = 'kdewin32 ws2_32'
	# (rh) this is required because genobj does not know anything about KDE installation pathes
	obj.instdir  = env['KDELIB']
	# (js)
	if env['CC'] == 'cl':
		obj.ccflags += " /FI./../../win/include/kdelibs_export_win.h -DWIN32_LEAN_AND_MEAN " 
else:
	obj          = env.genobj('convenience', env)
	obj.ccflags  ="-DICE_t -DTRANS_SERVER -DTRANS_CLIENT -DUNIXCONN -DANSICPP "

obj.target   = 'kICE'
obj.source   = ice_sources
obj.includes = '. ..'
obj.execute()

