#! /usr/bin/env python

Import('env')

ice_flags="-DICE_t -DTRANS_SERVER -DTRANS_CLIENT -DUNIXCONN -DANSICPP"

ice_sources="""
accept.c
authutil.c
connect.c
error.c
getauth.c
iceauth.c
listen.c
listenwk.c
locking.c
misc.c
ping.c
process.c
protosetup.c
register.c
replywait.c
setauth.c
shutdown.c
watch.c
transport.c
globals.c
"""

obj          = env.genobj('convenience', env)
obj.target   = 'libkICE.a'
obj.source   = ice_sources
obj.includes = '#/ ./ ..'
obj.ccflags = ice_flags
obj.execute()

