# KUNITCONVERSION_FOUND - system has lib conversion
# KUNITCONVERSION_INCLUDE_DIR - conversion include directory
# KUNITCONVERSION_LIBRARIES - library needed to use conversion

if (KUNITCONVERSION_INCLUDE_DIR AND KUNITCONVERSION_LIBRARIES)
   set(KUNITCONVERSION_FIND_QUIETLY TRUE)
endif (KUNITCONVERSION_INCLUDE_DIR AND KUNITCONVERSION_LIBRARIES)

find_path(KUNITCONVERSION_INCLUDE_DIR NAMES converter.h PATH_SUFFIXES kunitconversion)
find_library(KUNITCONVERSION_LIBRARIES NAMES kunitconversion)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(KUNITCONVERSION DEFAULT_MSG KUNITCONVERSION_INCLUDE_DIR KUNITCONVERSION_LIBRARIES)