#! /usr/bin/env python

Import('env')

obj = env.qt4obj('shlib',env)
obj.vnum     = '6.0.2'
obj.target   = 'libkdefx'
obj.source   = 'kpixmap.cpp kpixmapsplitter.cpp kpixmapeffect.cpp kimageeffect.cpp kdrawutil.cpp kstyle.cpp kcpuinfo.cpp'
obj.uselib   = 'QTCORE QT QT3SUPPORT XRENDER KDE4'
#obj.cxxflags = '-DHAVE_CONFIG_H -fno-exceptions -fno-check-new -fno-common -fvisibility=hidden -fvisibility-inlines-hidden -DQT_CLEAN_NAMESPACE -DQT_NO_CAST_TO_ASCII -DQT_NO_STL -DQT_NO_COMPAT -DQT_NO_TRANSLATION -DQT3_SUPPORT'
obj.execute()


"""INCLUDES= $(all_includes)

lib_LTLIBRARIES = libkdefx.la
libkdefx_la_LDFLAGS = $(KDE_RPATH) $(KDE_MT_LDFLAGS) $(all_libraries) -no-undefined -version-info 6:0:2
libkdefx_la_LIBADD = $(LIB_QT) $(LIB_XRENDER)
libkdefx_la_NMCHECK = $(srcdir)/libkdefx.nmcheck
libkdefx_la_NMCHECKWEAK = $(srcdir)/libkdefx_weak.nmcheck $(top_srcdir)/kdecore/libqt-mt_weak.nmcheck \
	$(top_srcdir)/kdecore/standard_weak.nmcheck

include_HEADERS = kpixmap.h kpixmapsplitter.h \
	kpixmapeffect.h kimageeffect.h kdrawutil.h kstyle.h kcpuinfo.h

libkdefx_la_SOURCES = kpixmap.cpp kpixmapsplitter.cpp \
		kpixmapeffect.cpp kimageeffect.cpp kdrawutil.cpp kstyle.cpp \
		kcpuinfo.cpp

METASOURCES = AUTO

EXTRA_DIST = Mainpage.dox

DOXYGEN_REFERENCES = kdecore
include ../admin/Doxyfile.am
"""
