#!/bin/sh

trap "rm -f dcopidlng.stderr.$$" 0 1 2 15

if test -z "$KDECONFIG"; then
    KDECONFIG=kde-config
fi
LIBDIR="`$KDECONFIG --install data --expandvars`/dcopidlng"
perl -I"$LIBDIR" "$LIBDIR/kalyptus" --allow_k_dcop_accessors -f dcopidl $1 2> dcopidlng.stderr.$$
RET=$?
if [ $RET -ne 0 ]
then
   cat dcopidlng.stderr.$$ >&2
fi
exit $RET
